/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 07e2dbbff84a
 */

import { agentsGetFullAgent } from "../../funcs/agentsGetFullAgent.js";
import { GetFullAgentRequest$zodSchema } from "../../models/getfullagentop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetFullAgentRequest$zodSchema,
};

export const tool$agentsGetFullAgent: ToolDefinition<typeof args> = {
  name: "agents-get-full-agent",
  description: `Get Full Agent

Retrieve a complete agent definition with all agents, tools, and relationships`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await agentsGetFullAgent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
