/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 412b3c40bd75
 */

import { appsCreateAppAuthKey } from "../../funcs/appsCreateAppAuthKey.js";
import { CreateAppAuthKeyRequest$zodSchema } from "../../models/createappauthkeyop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateAppAuthKeyRequest$zodSchema,
};

export const tool$appsCreateAppAuthKey: ToolDefinition<typeof args> = {
  name: "apps-create-app-auth-key",
  description: `Add Public Key

Add a public key for app authentication`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await appsCreateAppAuthKey(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
