/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 188a796f2ef0
 */

import { artifactComponentsGetArtifactComponentById } from "../../funcs/artifactComponentsGetArtifactComponentById.js";
import { GetArtifactComponentByIdRequest$zodSchema } from "../../models/getartifactcomponentbyidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetArtifactComponentByIdRequest$zodSchema,
};

export const tool$artifactComponentsGetArtifactComponentById: ToolDefinition<
  typeof args
> = {
  name: "artifact-components-get-artifact-component-by-id",
  description: `Get Artifact Component`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await artifactComponentsGetArtifactComponentById(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
