/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 564aefd3fbe7
 */

import { authGetPowChallenge } from "../../funcs/authGetPowChallenge.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$authGetPowChallenge: ToolDefinition = {
  name: "auth-get-pow-challenge",
  description: `Get PoW Challenge

Fetch an ALTCHA Proof-of-Work challenge. Returns 404 when PoW is not enabled on the server.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await authGetPowChallenge(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
