/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ef680f5e25ec
 */

import { branchesMergePreview } from "../../funcs/branchesMergePreview.js";
import { MergePreviewRequestRequest$zodSchema } from "../../models/mergepreviewop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: MergePreviewRequestRequest$zodSchema,
};

export const tool$branchesMergePreview: ToolDefinition<typeof args> = {
  name: "branches-merge-preview",
  description: `Preview Merge

Preview a merge between two branches, returning diff summary and any conflicts.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await branchesMergePreview(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
