/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { capabilities } from "../../funcs/capabilities.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$capabilities: ToolDefinition = {
  name: "capabilities",
  description: `Get server capabilities

Get information about optional server-side capabilities and configuration.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result, apiCall] = await capabilities(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
