/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 81c738af13b3
 */

import { cliGetManageApiCLIMe } from "../../funcs/cliGetManageApiCLIMe.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$cliGetManageApiCLIMe: ToolDefinition = {
  name: "cli-get-manage-api-cli-me",
  description: `Get CLI user info

Get the current authenticated user and their organization for CLI usage`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result, apiCall] = await cliGetManageApiCLIMe(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
