/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6088eca4f46f
 */

import { credentialStoresListCredentialStores } from "../../funcs/credentialStoresListCredentialStores.js";
import { ListCredentialStoresRequest$zodSchema } from "../../models/listcredentialstoresop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListCredentialStoresRequest$zodSchema,
};

export const tool$credentialStoresListCredentialStores: ToolDefinition<
  typeof args
> = {
  name: "credential-stores-list-credential-stores",
  description: `List Credential Stores`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await credentialStoresListCredentialStores(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
