/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cbe98e180e68
 */

import { dataComponentsDeleteDataComponent } from "../../funcs/dataComponentsDeleteDataComponent.js";
import { DeleteDataComponentRequest$zodSchema } from "../../models/deletedatacomponentop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteDataComponentRequest$zodSchema,
};

export const tool$dataComponentsDeleteDataComponent: ToolDefinition<
  typeof args
> = {
  name: "data-components-delete-data-component",
  description: `Delete Data Component`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await dataComponentsDeleteDataComponent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
