/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f46b91baf351
 */

import { evaluationsListEvaluatorAgents } from "../../funcs/evaluationsListEvaluatorAgents.js";
import { ListEvaluatorAgentsRequest$zodSchema } from "../../models/listevaluatoragentsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListEvaluatorAgentsRequest$zodSchema,
};

export const tool$evaluationsListEvaluatorAgents: ToolDefinition<typeof args> =
  {
    name: "evaluations-list-evaluator-agents",
    description: `List Agents for Evaluator`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await evaluationsListEvaluatorAgents(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
