/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b7ba36595e82
 */

import { feedbackUpdateFeedback } from "../../funcs/feedbackUpdateFeedback.js";
import { UpdateFeedbackRequest$zodSchema } from "../../models/updatefeedbackop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateFeedbackRequest$zodSchema,
};

export const tool$feedbackUpdateFeedback: ToolDefinition<typeof args> = {
  name: "feedback-update-feedback",
  description: `Update Feedback

Update an existing feedback entry`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await feedbackUpdateFeedback(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
