/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7c2dcd816603
 */

import { feedbackListFeedback } from "../../funcs/feedbackListFeedback.js";
import { ListFeedbackRequest$zodSchema } from "../../models/listfeedbackop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListFeedbackRequest$zodSchema,
};

export const tool$feedbackListFeedback: ToolDefinition<typeof args> = {
  name: "feedback-list-feedback",
  description: `List Feedback

List feedback for a project, optionally filtered by conversation or message`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await feedbackListFeedback(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
