/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oAuthMcpOauthCallback } from "../../funcs/oAuthMcpOauthCallback.js";
import { McpOauthCallbackRequest$zodSchema } from "../../models/mcpoauthcallbackop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: McpOauthCallbackRequest$zodSchema,
};

export const tool$oAuthMcpOauthCallback: ToolDefinition<typeof args> = {
  name: "O-auth-mcp-oauth-callback",
  description: `MCP OAuth authorization callback

Handles OAuth authorization codes for MCP tools and completes the authentication flow`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await oAuthMcpOauthCallback(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
