/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4d278bbe86e4
 */

import { projectMembersUpdateProjectMember } from "../../funcs/projectMembersUpdateProjectMember.js";
import { UpdateProjectMemberRequest$zodSchema } from "../../models/updateprojectmemberop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateProjectMemberRequest$zodSchema,
};

export const tool$projectMembersUpdateProjectMember: ToolDefinition<
  typeof args
> = {
  name: "project-members-update-project-member",
  description: `Update Project Member Role

Update a project member's role. Include previousRole to specify which role to revoke.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await projectMembersUpdateProjectMember(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
