/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 70b4c286bf40
 */

import { scheduledTriggersUpdateScheduledTrigger } from "../../funcs/scheduledTriggersUpdateScheduledTrigger.js";
import { UpdateScheduledTriggerRequest$zodSchema } from "../../models/updatescheduledtriggerop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateScheduledTriggerRequest$zodSchema,
};

export const tool$scheduledTriggersUpdateScheduledTrigger: ToolDefinition<
  typeof args
> = {
  name: "scheduled-triggers-update-scheduled-trigger",
  description: `Update Scheduled Trigger`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await scheduledTriggersUpdateScheduledTrigger(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
