/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d592e4b53e66
 */

import { scheduledTriggersRemoveScheduledTriggerUser } from "../../funcs/scheduledTriggersRemoveScheduledTriggerUser.js";
import { RemoveScheduledTriggerUserRequest$zodSchema } from "../../models/removescheduledtriggeruserop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RemoveScheduledTriggerUserRequest$zodSchema,
};

export const tool$scheduledTriggersRemoveScheduledTriggerUser: ToolDefinition<
  typeof args
> = {
  name: "scheduled-triggers-remove-scheduled-trigger-user",
  description: `Remove User from Scheduled Trigger`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await scheduledTriggersRemoveScheduledTriggerUser(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
