/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ccc5a8aca34a
 */

import { skillsDeleteSubagentSkill } from "../../funcs/skillsDeleteSubagentSkill.js";
import { DeleteSubagentSkillRequest$zodSchema } from "../../models/deletesubagentskillop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteSubagentSkillRequest$zodSchema,
};

export const tool$skillsDeleteSubagentSkill: ToolDefinition<typeof args> = {
  name: "skills-delete-subagent-skill",
  description: `Detach Skill from Sub-Agent`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await skillsDeleteSubagentSkill(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
