/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fa342d0cc897
 */

import { skillsGetSkillFile } from "../../funcs/skillsGetSkillFile.js";
import { GetSkillFileRequest$zodSchema } from "../../models/getskillfileop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetSkillFileRequest$zodSchema,
};

export const tool$skillsGetSkillFile: ToolDefinition<typeof args> = {
  name: "skills-get-skill-file",
  description: `Get Skill File`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await skillsGetSkillFile(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
