/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 471fe1fd5f5d
 */

import { subAgentsListSubAgentTeamAgentRelations } from "../../funcs/subAgentsListSubAgentTeamAgentRelations.js";
import { ListSubAgentTeamAgentRelationsRequest$zodSchema } from "../../models/listsubagentteamagentrelationsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListSubAgentTeamAgentRelationsRequest$zodSchema,
};

export const tool$subAgentsListSubAgentTeamAgentRelations: ToolDefinition<
  typeof args
> = {
  name: "sub-agents-list-sub-agent-team-agent-relations",
  description: `List Sub Agent Team Agent Relations`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await subAgentsListSubAgentTeamAgentRelations(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
