/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: adc7a7c6d096
 */

import { subAgentsDeleteSubAgentTeamAgentRelation } from "../../funcs/subAgentsDeleteSubAgentTeamAgentRelation.js";
import { DeleteSubAgentTeamAgentRelationRequest$zodSchema } from "../../models/deletesubagentteamagentrelationop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteSubAgentTeamAgentRelationRequest$zodSchema,
};

export const tool$subAgentsDeleteSubAgentTeamAgentRelation: ToolDefinition<
  typeof args
> = {
  name: "sub-agents-delete-sub-agent-team-agent-relation",
  description: `Delete Sub Agent Team Agent Relation`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await subAgentsDeleteSubAgentTeamAgentRelation(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
