/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3e6a85e674ae
 */

import { subAgentsListSubAgentExternalAgentRelations } from "../../funcs/subAgentsListSubAgentExternalAgentRelations.js";
import { ListSubAgentExternalAgentRelationsRequest$zodSchema } from "../../models/listsubagentexternalagentrelationsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListSubAgentExternalAgentRelationsRequest$zodSchema,
};

export const tool$subAgentsListSubAgentExternalAgentRelations: ToolDefinition<
  typeof args
> = {
  name: "sub-agents-list-sub-agent-external-agent-relations",
  description: `List Sub Agent External Agent Relations`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await subAgentsListSubAgentExternalAgentRelations(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
