/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: be90e22a6d74
 */

import { subAgentsDeleteSubagent } from "../../funcs/subAgentsDeleteSubagent.js";
import { DeleteSubagentRequest$zodSchema } from "../../models/deletesubagentop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteSubagentRequest$zodSchema,
};

export const tool$subAgentsDeleteSubagent: ToolDefinition<typeof args> = {
  name: "sub-agents-delete-subagent",
  description: `Delete SubAgent`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await subAgentsDeleteSubagent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
