/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5efde8f852c5
 */

import { toolsGetMcpToolGithubAccess } from "../../funcs/toolsGetMcpToolGithubAccess.js";
import { GetMcpToolGithubAccessRequest$zodSchema } from "../../models/getmcptoolgithubaccessop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetMcpToolGithubAccessRequest$zodSchema,
};

export const tool$toolsGetMcpToolGithubAccess: ToolDefinition<typeof args> = {
  name: "tools-get-mcp-tool-github-access",
  description: `Get MCP tool GitHub repository access

Returns the current GitHub repository access configuration for an MCP tool. If mode is "all", the tool has access to all repositories the project can access. If mode is "selected", the tool is scoped to specific repositories. `,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await toolsGetMcpToolGithubAccess(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
