/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d4e1b5e661d8
 */

import { userProjectMembershipsListUserProjectMemberships } from "../../funcs/userProjectMembershipsListUserProjectMemberships.js";
import { ListUserProjectMembershipsRequest$zodSchema } from "../../models/listuserprojectmembershipsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListUserProjectMembershipsRequest$zodSchema,
};

export const tool$userProjectMembershipsListUserProjectMemberships:
  ToolDefinition<typeof args> = {
    name: "user-project-memberships-list-user-project-88a",
    description: `List User Project Memberships

List all projects a user has explicit access to and their role in each. Requires authz to be enabled.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await userProjectMembershipsListUserProjectMemberships(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
