/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8d1b034572d0
 */

import { workAppsSlackLinkStatus } from "../../funcs/workAppsSlackLinkStatus.js";
import { SlackLinkStatusRequest$zodSchema } from "../../models/slacklinkstatusop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: SlackLinkStatusRequest$zodSchema,
};

export const tool$workAppsSlackLinkStatus: ToolDefinition<typeof args> = {
  name: "work-apps-slack-link-status",
  description: `Check Link Status

Check if a Slack user is linked to an Inkeep account`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await workAppsSlackLinkStatus(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
