/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: af0121adb8af
 */

import { workAppsSlackTestMessage } from "../../funcs/workAppsSlackTestMessage.js";
import { SlackTestMessageRequest$zodSchema } from "../../models/slacktestmessageop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: SlackTestMessageRequest$zodSchema,
};

export const tool$workAppsSlackTestMessage: ToolDefinition<typeof args> = {
  name: "work-apps-slack-test-message",
  description: `Send Test Message

Send a test message to verify the bot is working correctly.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await workAppsSlackTestMessage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
