/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4e2c3e092f06
 */

import { workAppsSlackUpdateJoinFromWorkspace } from "../../funcs/workAppsSlackUpdateJoinFromWorkspace.js";
import { SlackUpdateJoinFromWorkspaceRequest$zodSchema } from "../../models/slackupdatejoinfromworkspaceop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: SlackUpdateJoinFromWorkspaceRequest$zodSchema,
};

export const tool$workAppsSlackUpdateJoinFromWorkspace: ToolDefinition<
  typeof args
> = {
  name: "work-apps-slack-update-join-from-workspace",
  description: `Update Join From Workspace Setting

Enable or disable join from workspace for the workspace`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await workAppsSlackUpdateJoinFromWorkspace(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
