/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 86a092b96b0f
 */

import { workAppsSlackListLinkedUsers } from "../../funcs/workAppsSlackListLinkedUsers.js";
import { SlackListLinkedUsersRequest$zodSchema } from "../../models/slacklistlinkedusersop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: SlackListLinkedUsersRequest$zodSchema,
};

export const tool$workAppsSlackListLinkedUsers: ToolDefinition<typeof args> = {
  name: "work-apps-slack-list-linked-users",
  description: `List Linked Users

List all users linked to Inkeep in this workspace`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await workAppsSlackListLinkedUsers(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
