//agents-core/src/db/manage/slack-schema.ts
import {
  pgTable,
  text,
  timestamp,
  boolean,
  index,
  uniqueIndex,
} from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';

/**
 * Slack Workspaces
 * 
 * KEY FIELD: nangoConnectionId
 * This is the Nango-generated connection ID (random string).
 * We do NOT derive it from teamId - it's stored when Nango sends
 * the webhook after OAuth completion.
 */
export const slackWorkspaces = pgTable(
  'slack_workspaces',
  {
    id: text('id').primaryKey(),
    tenantId: text('tenant_id').notNull(),
    projectId: text('project_id').notNull(),

    // Slack workspace info
    teamId: text('team_id').notNull(),
    teamName: text('team_name').notNull(),
    teamDomain: text('team_domain'),

    // Installation info
    installedBy: text('installed_by').notNull(),
    botUserId: text('bot_user_id').notNull(),
    scopes: text('scopes').notNull(),

    // Nango connection reference
    // This is randomly generated by Nango, NOT derived from teamId
    nangoConnectionId: text('nango_connection_id').notNull(),

    // Future: user-level OAuth connection
    // nangoAuthedUserConnectionId: text('nango_authed_user_connection_id'),

    // Status
    isActive: boolean('is_active').notNull().default(true),

    // Timestamps
    createdAt: timestamp('created_at', { mode: 'string' }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { mode: 'string' }).notNull().defaultNow(),
  },
  (table) => ({
    tenantProjectIdx: index('slack_workspaces_tenant_project_idx').on(
      table.tenantId,
      table.projectId
    ),
    teamIdIdx: uniqueIndex('slack_workspaces_team_id_idx').on(table.teamId),
    nangoConnectionIdx: index('slack_workspaces_nango_connection_idx').on(
      table.nangoConnectionId
    ),
  })
);

/**
 * Slack Channels
 */
export const slackChannels = pgTable(
  'slack_channels',
  {
    id: text('id').primaryKey(),
    tenantId: text('tenant_id').notNull(),
    projectId: text('project_id').notNull(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => slackWorkspaces.id, { onDelete: 'cascade' }),

    channelId: text('channel_id').notNull(),
    channelName: text('channel_name').notNull(),
    channelType: text('channel_type').notNull(),

    isEnabled: boolean('is_enabled').notNull().default(true),
    respondToMentions: boolean('respond_to_mentions').notNull().default(true),
    respondToDirectMessages: boolean('respond_to_direct_messages').notNull().default(true),
    respondToThreads: boolean('respond_to_threads').notNull().default(true),

    agentId: text('agent_id'),

    createdAt: timestamp('created_at', { mode: 'string' }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { mode: 'string' }).notNull().defaultNow(),
  },
  (table) => ({
    tenantProjectIdx: index('slack_channels_tenant_project_idx').on(
      table.tenantId,
      table.projectId
    ),
    workspaceChannelIdx: uniqueIndex('slack_channels_workspace_channel_idx').on(
      table.workspaceId,
      table.channelId
    ),
  })
);

/**
 * Slack User Mappings
 * Links Slack users to internal Inkeep users
 */
export const slackUserMappings = pgTable(
  'slack_user_mappings',
  {
    id: text('id').primaryKey(),
    tenantId: text('tenant_id').notNull(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => slackWorkspaces.id, { onDelete: 'cascade' }),

    slackUserId: text('slack_user_id').notNull(),
    slackUserName: text('slack_user_name'),
    slackEmail: text('slack_email'),

    // Link to internal Inkeep user
    internalUserId: text('internal_user_id'),

    // Future: user-level Nango connection
    // nangoUserConnectionId: text('nango_user_connection_id'),

    createdAt: timestamp('created_at', { mode: 'string' }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { mode: 'string' }).notNull().defaultNow(),
  },
  (table) => ({
    tenantIdx: index('slack_user_mappings_tenant_idx').on(table.tenantId),
    workspaceUserIdx: uniqueIndex('slack_user_mappings_workspace_user_idx').on(
      table.workspaceId,
      table.slackUserId
    ),
  })
);

// Relations
export const slackWorkspacesRelations = relations(slackWorkspaces, ({ many }) => ({
  channels: many(slackChannels),
  userMappings: many(slackUserMappings),
}));

export const slackChannelsRelations = relations(slackChannels, ({ one }) => ({
  workspace: one(slackWorkspaces, {
    fields: [slackChannels.workspaceId],
    references: [slackWorkspaces.id],
  }),
}));

export const slackUserMappingsRelations = relations(slackUserMappings, ({ one }) => ({
  workspace: one(slackWorkspaces, {
    fields: [slackUserMappings.workspaceId],
    references: [slackWorkspaces.id],
  }),
}));

// Types
export type SlackWorkspace = typeof slackWorkspaces.$inferSelect;
export type SlackWorkspaceInsert = typeof slackWorkspaces.$inferInsert;
export type SlackChannel = typeof slackChannels.$inferSelect;
export type SlackChannelInsert = typeof slackChannels.$inferInsert;
export type SlackUserMapping = typeof slackUserMappings.$inferSelect;
export type SlackUserMappingInsert = typeof slackUserMappings.$inferInsert;
