packages:
  - agents-api
  - agents-manage-ui
  - agents-cli
  - agents-ui
  - agents-docs
  - agents-cookbook
  - test-agents
  - "packages/*"

catalog:
  better-auth: 1.4.19
  "@better-auth/sso": 1.4.19
  "@opentelemetry/api": ^1.9.0
  "@opentelemetry/auto-instrumentations-node": ^0.70.0
  "@opentelemetry/baggage-span-processor": ^0.5.0
  "@opentelemetry/context-async-hooks": ^2.5.1
  "@opentelemetry/core": ^2.5.1
  "@opentelemetry/exporter-trace-otlp-http": ^0.212.0
  "@opentelemetry/resources": ^2.5.1
  "@opentelemetry/sdk-node": ^0.212.0
  "@opentelemetry/sdk-trace-base": ^2.5.1
  "@opentelemetry/semantic-conventions": ^1.39.0

publicHoistPattern:
  - "@types/react"
  - "@types/react-dom"

ignorePatchFailures: false

patchedDependencies:
  "@changesets/assemble-release-plan@6.0.9": patches/@changesets__assemble-release-plan.patch
  fumadocs-core: patches/fumadocs-core.patch

overrides:
  next: ^16.1.6 # https://github.com/advisories/GHSA-5f7q-jpqc-wp7h
  esbuild: 0.25.9 # we pin it for Cypress
  "@modelcontextprotocol/sdk>zod": ^3.25.7
  "@anthropic-ai/mcpb>zod": ^3.25.7
  preact: "-" # we don't use preact, this removes pnpm audit warnings from posthog-js>preact
