packages:
  - agents-manage-api
  - agents-run-api
  - agents-manage-ui
  - agents-cli
  - agents-ui
  - examples
  - agents-docs
  - langfuse-script
  - packages/agents-core
  - packages/agents-sdk
onlyBuiltDependencies:
  - keytar
