packages:
  - agents-manage-api
  - agents-run-api
  - agents-manage-ui
  - agents-cli
  - agents-ui
  - examples
  - agents-docs
  - packages/agents-core
  - packages/agents-sdk
  - packages/create-agents
onlyBuiltDependencies:
  - keytar
