packages:
  - agents-manage-api
  - agents-run-api
  - agents-manage-ui
  - agents-cli
  - agents-ui
  - agents-docs
  - agents-cookbook
  - test-agents
  - "packages/*"

catalog:
  better-auth: ^1.4.0
  "@better-auth/sso": ^1.4.0