import {
  DEFAULT_INKEEP_AGENTS_API_URL,
  DEFAULT_NANGO_CONNECT_BASE_URL,
  DEFAULT_NANGO_SERVER_URL,
  DEFAULT_SIGNOZ_URL,
} from '@/lib/runtime-config/defaults';

export function getRuntimeConfig() {
  return {
    PUBLIC_INKEEP_AGENTS_RUN_API_BYPASS_SECRET:
      process.env.PUBLIC_INKEEP_AGENTS_RUN_API_BYPASS_SECRET ||
      process.env.NEXT_PUBLIC_INKEEP_AGENTS_RUN_API_BYPASS_SECRET,
    PUBLIC_INKEEP_AGENTS_API_URL:
      process.env.PUBLIC_INKEEP_AGENTS_API_URL ||
      process.env.NEXT_PUBLIC_INKEEP_AGENTS_API_URL ||
      DEFAULT_INKEEP_AGENTS_API_URL,
    PUBLIC_SIGNOZ_URL:
      process.env.PUBLIC_SIGNOZ_URL || process.env.NEXT_PUBLIC_SIGNOZ_URL || DEFAULT_SIGNOZ_URL,
    PUBLIC_NANGO_SERVER_URL:
      process.env.PUBLIC_NANGO_SERVER_URL ||
      process.env.NEXT_PUBLIC_NANGO_SERVER_URL ||
      DEFAULT_NANGO_SERVER_URL,
    PUBLIC_NANGO_CONNECT_BASE_URL:
      process.env.PUBLIC_NANGO_CONNECT_BASE_URL ||
      process.env.NEXT_PUBLIC_NANGO_CONNECT_BASE_URL ||
      DEFAULT_NANGO_CONNECT_BASE_URL,
    PUBLIC_INKEEP_COPILOT_APP_ID:
      process.env.PUBLIC_INKEEP_COPILOT_APP_ID || process.env.NEXT_PUBLIC_INKEEP_COPILOT_APP_ID,
    PUBLIC_GOOGLE_CLIENT_ID:
      process.env.PUBLIC_GOOGLE_CLIENT_ID || process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,
    PUBLIC_MICROSOFT_CLIENT_ID:
      process.env.PUBLIC_MICROSOFT_CLIENT_ID || process.env.NEXT_PUBLIC_MICROSOFT_CLIENT_ID,
    PUBLIC_IS_INKEEP_CLOUD_DEPLOYMENT:
      process.env.PUBLIC_IS_INKEEP_CLOUD_DEPLOYMENT ||
      process.env.NEXT_PUBLIC_IS_INKEEP_CLOUD_DEPLOYMENT ||
      'false',
    PUBLIC_POSTHOG_KEY: process.env.PUBLIC_POSTHOG_KEY || process.env.NEXT_PUBLIC_POSTHOG_KEY,
    PUBLIC_POSTHOG_HOST: process.env.PUBLIC_POSTHOG_HOST || process.env.NEXT_PUBLIC_POSTHOG_HOST,
    PUBLIC_POSTHOG_SITE_TAG:
      process.env.PUBLIC_POSTHOG_SITE_TAG || process.env.NEXT_PUBLIC_POSTHOG_SITE_TAG,
    PUBLIC_IS_SMTP_CONFIGURED:
      process.env.PUBLIC_IS_SMTP_CONFIGURED ||
      process.env.NEXT_PUBLIC_IS_SMTP_CONFIGURED ||
      ((process.env.RESEND_API_KEY || process.env.SMTP_HOST) && process.env.SMTP_FROM_ADDRESS
        ? 'true'
        : undefined),
  };
}
