export interface RuntimeConfig {
  PUBLIC_INKEEP_AGENTS_MANAGE_API_URL: string;
  PUBLIC_INKEEP_AGENTS_RUN_API_URL: string;
  PUBLIC_INKEEP_AGENTS_RUN_API_BYPASS_SECRET?: string;
  PUBLIC_SIGNOZ_URL: string;
  PUBLIC_NANGO_SERVER_URL?: string;
  PUBLIC_NANGO_CONNECT_BASE_URL?: string;
  PUBLIC_INKEEP_COPILOT_AGENT_ID?: string;
  PUBLIC_INKEEP_COPILOT_PROJECT_ID?: string;
  PUBLIC_INKEEP_COPILOT_TENANT_ID?: string;
}
