export interface RuntimeConfig {
  PUBLIC_INKEEP_AGENTS_API_URL: string;
  PUBLIC_INKEEP_AGENTS_RUN_API_BYPASS_SECRET?: string;
  PUBLIC_SIGNOZ_URL: string;
  PUBLIC_NANGO_SERVER_URL?: string;
  PUBLIC_NANGO_CONNECT_BASE_URL?: string;
  PUBLIC_INKEEP_COPILOT_AGENT_ID?: string;
  PUBLIC_INKEEP_COPILOT_PROJECT_ID?: string;
  PUBLIC_INKEEP_COPILOT_TENANT_ID?: string;
  PUBLIC_AUTH0_DOMAIN?: string;
  PUBLIC_GOOGLE_CLIENT_ID?: string;
  PUBLIC_IS_INKEEP_CLOUD_DEPLOYMENT?: string;
  PUBLIC_POSTHOG_KEY?: string;
  PUBLIC_POSTHOG_HOST?: string;
  PUBLIC_POSTHOG_SITE_TAG?: string;
  PUBLIC_IS_SMTP_CONFIGURED?: string;
}
