/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 974220f53fe6
 */

import { credentialsCreateCredential } from "../../funcs/credentialsCreateCredential.js";
import { CreateCredentialRequest$zodSchema } from "../../models/createcredentialop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateCredentialRequest$zodSchema,
};

export const tool$credentialsCreateCredential: ToolDefinition<typeof args> = {
  name: "credentials-create-credential",
  description: `Create Credential`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await credentialsCreateCredential(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
