/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 39baff4aa7a3
 */

import { projectsSetProjectGithubAccess } from "../../funcs/projectsSetProjectGithubAccess.js";
import { SetProjectGithubAccessRequest$zodSchema } from "../../models/setprojectgithubaccessop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: SetProjectGithubAccessRequest$zodSchema,
};

export const tool$projectsSetProjectGithubAccess: ToolDefinition<typeof args> =
  {
    name: "projects-set-project-github-access",
    description: `Set project GitHub repository access

Configures which GitHub repositories a project can access. When mode is "all", the project has access to all repositories from tenant GitHub installations. When mode is "selected", the project is scoped to specific repositories (repositoryIds required). This replaces any existing access configuration.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await projectsSetProjectGithubAccess(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
