/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 25e8dde65a5c
 */

import { scheduledTriggersListScheduledTriggerInvocations } from "../../funcs/scheduledTriggersListScheduledTriggerInvocations.js";
import { ListScheduledTriggerInvocationsRequest$zodSchema } from "../../models/listscheduledtriggerinvocationsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListScheduledTriggerInvocationsRequest$zodSchema,
};

export const tool$scheduledTriggersListScheduledTriggerInvocations:
  ToolDefinition<typeof args> = {
    name: "scheduled-triggers-list-scheduled-trigger-61d",
    description: `List Scheduled Trigger Invocations`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await scheduledTriggersListScheduledTriggerInvocations(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
