/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 925ce925142b
 */

import { userProfileUpsertUserProfile } from "../../funcs/userProfileUpsertUserProfile.js";
import { UpsertUserProfileRequest$zodSchema } from "../../models/upsertuserprofileop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpsertUserProfileRequest$zodSchema,
};

export const tool$userProfileUpsertUserProfile: ToolDefinition<typeof args> = {
  name: "user-profile-upsert-user-profile",
  description: `Upsert User Profile

Create or update the profile for a specific user. Users can only update their own profile.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await userProfileUpsertUserProfile(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
