receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Redact auth header on spans
  attributes:
    actions:
      - key: http.request.header.authorization
        value: "[REDACTED]"
        action: update

  # Development: "immediate" batching (very small timeout/batch)
  batch/development:
    timeout: ${env:OTEL_TIMEOUT:-100ms}
    send_batch_size: ${env:OTEL_SEND_BATCH_SIZE:-1}
    send_batch_max_size: ${env:OTEL_SEND_BATCH_MAX_SIZE:-10}

  # Default/other: "standard" batching (larger, efficient)
  batch/production:
    timeout: ${env:OTEL_TIMEOUT_STANDARD:-10000ms}
    send_batch_size: ${env:OTEL_SEND_BATCH_SIZE_STANDARD:-512}
    send_batch_max_size: ${env:OTEL_SEND_BATCH_MAX_SIZE_STANDARD:-1024}

exporters:
  # Export to Jaeger
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  
  # Export to SigNoz OTEL collector
  otlp/signoz:
    endpoint: signoz-otel-collector:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors:
        - attributes
        - "batch/${env:ENVIRONMENT:-development}"
      exporters: [otlp/jaeger, otlp/signoz]