name: 'Cypress E2E Tests'
description: 'Run Cypress end-to-end tests with API and Dashboard'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22.x'
  pnpm-version:
    description: 'pnpm version to use'
    required: false
    default: '10.10.0'

runs:
  using: 'composite'
  steps:
    # --- Phase 1: Cache + install (no dependencies) ---
    - name: Setup Cypress cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/Cypress
        key: ${{ runner.os }}-cypress-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-cypress-

    - name: Install Cypress binary
      shell: bash
      run: cd agents-manage-ui && pnpm exec cypress install

    # --- Phase 2: Build while DB initializes ---
    - name: Build agents-core (required by setup-dev.js)
      shell: bash
      run: pnpm exec turbo run build --filter=@inkeep/agents-core

    - name: Wait for DoltGres to be fully initialized
      shell: bash
      run: |
        echo "Waiting for DoltGres system tables to be available..."
        for i in $(seq 1 30); do
          if PGPASSWORD=password psql -h localhost -p 5432 -U appuser -d inkeep_agents -c 'SELECT count(*) FROM dolt_status' 2>/dev/null; then
            echo "DoltGres is ready!"
            break
          fi
          if [ $i -eq 30 ]; then
            echo "Timeout waiting for DoltGres after 60 seconds"
            exit 1
          fi
          echo "  Attempt $i/30..."
          sleep 2
        done

    # --- Phase 3: DB setup ---
    - name: Setup development environment
      shell: bash
      env:
        ENVIRONMENT: development
      run: pnpm setup-dev --skip-push

    # --- Phase 4: Dashboard build + API startup (reordered) ---
    - name: Build dashboard and monorepo dependencies
      shell: bash
      run: pnpm exec turbo build --filter='@inkeep/agents-manage-ui' --filter='@inkeep/agents-cli' --filter='@inkeep/agents-sdk'

    - name: Start backend API server
      shell: bash
      env:
        ENVIRONMENT: development
        INKEEP_AGENTS_MANAGE_API_BYPASS_SECRET: ${{ env.INKEEP_AGENTS_MANAGE_API_BYPASS_SECRET }}
        BETTER_AUTH_SECRET: ${{ env.BETTER_AUTH_SECRET }}
      run: pnpm exec turbo dev --filter='@inkeep/agents-api' &

    - name: Wait for API server to be ready
      shell: bash
      run: |
        echo "Waiting for API server to be ready on port 3002..."
        timeout=120
        elapsed=0
        while true; do
          status_code=$(curl -s -o /dev/null -w '%{http_code}' http://localhost:3002/health 2>/dev/null || echo "000")
          if [ "$status_code" = "204" ] || [ "$status_code" = "200" ]; then
            echo "API server is ready! (HTTP $status_code)"
            break
          fi
          if [ $elapsed -ge $timeout ]; then
            echo "Timeout waiting for API server (last status: $status_code)"
            exit 1
          fi
          echo "Waiting... ($elapsed seconds, status: $status_code)"
          sleep 2
          elapsed=$((elapsed + 2))
        done

    # --- Phase 5: Diagnostics + Seed + test ---
    - name: Diagnostic - Log environment variable presence
      shell: bash
      run: |
        echo "=== Environment Variable Diagnostics ==="
        echo "ENVIRONMENT=${ENVIRONMENT:-<unset>}"
        echo "INKEEP_AGENTS_MANAGE_DATABASE_URL set: $([ -n "$INKEEP_AGENTS_MANAGE_DATABASE_URL" ] && echo "yes (${#INKEEP_AGENTS_MANAGE_DATABASE_URL} chars)" || echo "no")"
        echo "INKEEP_AGENTS_RUN_DATABASE_URL set: $([ -n "$INKEEP_AGENTS_RUN_DATABASE_URL" ] && echo "yes (${#INKEEP_AGENTS_RUN_DATABASE_URL} chars)" || echo "no")"
        echo "INKEEP_AGENTS_MANAGE_API_BYPASS_SECRET set: $([ -n "$INKEEP_AGENTS_MANAGE_API_BYPASS_SECRET" ] && echo "yes (${#INKEEP_AGENTS_MANAGE_API_BYPASS_SECRET} chars, starts with '${INKEEP_AGENTS_MANAGE_API_BYPASS_SECRET:0:4}...')" || echo "no")"
        echo "BETTER_AUTH_SECRET set: $([ -n "$BETTER_AUTH_SECRET" ] && echo "yes (${#BETTER_AUTH_SECRET} chars)" || echo "no")"
        echo "SPICEDB_PRESHARED_KEY set: $([ -n "$SPICEDB_PRESHARED_KEY" ] && echo "yes" || echo "no")"
        echo "OTEL_SDK_DISABLED=${OTEL_SDK_DISABLED:-<unset>}"
        echo "NODE_OPTIONS=${NODE_OPTIONS:-<unset>}"
        echo "INKEEP_API_KEY set: $([ -n "$INKEEP_API_KEY" ] && echo "yes" || echo "no")"

    - name: Push Activities Planner Project
      shell: bash
      env:
        INKEEP_API_KEY: ${{ env.INKEEP_AGENTS_MANAGE_API_BYPASS_SECRET }}
      run: |
        max_attempts=3
        attempt=1
        while [ $attempt -le $max_attempts ]; do
          echo "Push attempt $attempt/$max_attempts..."
          if cd agents-cookbook/template-projects && npx inkeep push --project activities-planner; then
            echo "Push succeeded on attempt $attempt"
            break
          fi
          if [ $attempt -eq $max_attempts ]; then
            echo "Push failed after $max_attempts attempts"
            exit 1
          fi
          echo "Push failed, retrying in $((attempt * 5)) seconds..."
          sleep $((attempt * 5))
          cd "$GITHUB_WORKSPACE"
          attempt=$((attempt + 1))
        done

    - name: Diagnostic - Verify seed data in DoltgreSQL
      shell: bash
      run: |
        echo "=== DoltgreSQL Seed Data Verification ==="

        echo ""
        echo "--- Dolt branches ---"
        PGPASSWORD=password psql -h localhost -p 5432 -U appuser -d inkeep_agents -c "SELECT * FROM dolt_branches;" 2>&1 || echo "Failed to query dolt_branches"

        echo ""
        echo "--- Dolt status (uncommitted changes) ---"
        PGPASSWORD=password psql -h localhost -p 5432 -U appuser -d inkeep_agents -c "SELECT * FROM dolt_status;" 2>&1 || echo "Failed to query dolt_status"

        echo ""
        echo "--- Projects on default branch ---"
        PGPASSWORD=password psql -h localhost -p 5432 -U appuser -d inkeep_agents -c "SELECT id, name, tenant_id FROM projects;" 2>&1 || echo "Failed to query projects"

        echo ""
        echo "--- Agents on default branch ---"
        PGPASSWORD=password psql -h localhost -p 5432 -U appuser -d inkeep_agents -c "SELECT id, name, project_id, tenant_id FROM agents;" 2>&1 || echo "Failed to query agents"

        echo ""
        echo "--- Sub-agents on default branch ---"
        PGPASSWORD=password psql -h localhost -p 5432 -U appuser -d inkeep_agents -c "SELECT id, name, agent_id, project_id, tenant_id FROM sub_agents;" 2>&1 || echo "Failed to query sub_agents"

        echo ""
        echo "--- Check project-scoped branch ---"
        PGPASSWORD=password psql -h localhost -p 5432 -U appuser -d inkeep_agents -c "
          SELECT name FROM dolt_branches WHERE name LIKE '%activities%' OR name LIKE '%default%';
        " 2>&1 || echo "Failed to query for project branches"

        echo ""
        echo "--- Try querying project branch for agents ---"
        PGPASSWORD=password psql -h localhost -p 5432 -U appuser -d inkeep_agents -c "
          CALL dolt_checkout('default_activities-planner_main');
          SELECT id, name, project_id FROM agents;
        " 2>&1 || echo "Failed to checkout project branch (may not exist)"

        echo ""
        echo "--- Try querying project branch for sub-agents ---"
        PGPASSWORD=password psql -h localhost -p 5432 -U appuser -d inkeep_agents -c "
          CALL dolt_checkout('default_activities-planner_main');
          SELECT id, name, agent_id, project_id FROM sub_agents;
        " 2>&1 || echo "Failed to query sub_agents on project branch"

        echo ""
        echo "--- Dolt log (recent commits) ---"
        PGPASSWORD=password psql -h localhost -p 5432 -U appuser -d inkeep_agents -c "
          SELECT commit_hash, committer, message FROM dolt_log LIMIT 10;
        " 2>&1 || echo "Failed to query dolt_log"

    - name: Diagnostic - Verify API returns full agent data
      shell: bash
      run: |
        echo "=== API Full Agent Response Diagnostic ==="

        echo ""
        echo "--- GET /manage/tenants/default/projects ---"
        curl -s -w "\nHTTP Status: %{http_code}\n" \
          -H "Authorization: Bearer ${INKEEP_AGENTS_MANAGE_API_BYPASS_SECRET}" \
          http://localhost:3002/manage/tenants/default/projects 2>&1 | head -100

        echo ""
        echo "--- GET full agent definition ---"
        RESPONSE=$(curl -s -w "\n---HTTP_STATUS:%{http_code}---" \
          -H "Authorization: Bearer ${INKEEP_AGENTS_MANAGE_API_BYPASS_SECRET}" \
          http://localhost:3002/manage/tenants/default/projects/activities-planner/agent/activities-planner 2>&1)
        HTTP_STATUS=$(echo "$RESPONSE" | grep -o '---HTTP_STATUS:[0-9]*---' | grep -o '[0-9]*')
        BODY=$(echo "$RESPONSE" | sed 's/---HTTP_STATUS:[0-9]*---//')
        echo "HTTP Status: $HTTP_STATUS"
        echo "Response body (first 2000 chars):"
        echo "$BODY" | head -c 2000
        echo ""

        if [ "$HTTP_STATUS" = "200" ]; then
          echo ""
          echo "--- Checking subAgents in response ---"
          echo "$BODY" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    sub_agents = data.get('subAgents', {})
    print(f'subAgents count: {len(sub_agents)}')
    for key, val in sub_agents.items():
        name = val.get('name', '<no name>') if isinstance(val, dict) else '<not a dict>'
        print(f'  - {key}: {name}')
    default_sub = data.get('defaultSubAgentId', '<not set>')
    print(f'defaultSubAgentId: {default_sub}')
except Exception as e:
    print(f'Failed to parse JSON: {e}')
" 2>&1 || echo "Failed to parse response JSON"
        fi

    - name: Run Cypress E2E Tests
      shell: bash
      run: timeout 600 pnpm --filter @inkeep/agents-manage-ui test:e2e:ci

    - name: Upload Cypress Screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-screenshots
        path: agents-manage-ui/cypress/screenshots
        if-no-files-found: ignore
        retention-days: 7

    - name: Upload Cypress Videos
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-videos
        path: agents-manage-ui/cypress/videos
        if-no-files-found: ignore
        retention-days: 7
