name: 'Cypress E2E Tests'
description: 'Run Cypress end-to-end tests with API and Dashboard'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22.x'
  pnpm-version:
    description: 'pnpm version to use'
    required: false
    default: '10.10.0'

runs:
  using: 'composite'
  steps:
    - name: Setup Cypress cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/Cypress
        key: ${{ runner.os }}-cypress-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-cypress-

    - name: Install Cypress binary
      shell: bash
      run: cd agents-manage-ui && npx cypress install

    - run: pnpm setup-dev
      shell: bash

    - name: Start backend API server
      shell: bash
      env:
        INKEEP_AGENTS_MANAGE_API_BYPASS_SECRET: ${{ env.INKEEP_AGENTS_MANAGE_API_BYPASS_SECRET }}
        BETTER_AUTH_SECRET: ${{ env.BETTER_AUTH_SECRET }}
      run: pnpm dev --filter='@inkeep/agents-api' & # & means run job in background

    - name: Wait for API server to be ready
      shell: bash
      run: |
        echo "Waiting for API server to be ready on port 3002..."
        timeout=120
        elapsed=0
        while true; do
          status_code=$(curl -s -o /dev/null -w '%{http_code}' http://localhost:3002/health 2>/dev/null || echo "000")
          if [ "$status_code" = "204" ] || [ "$status_code" = "200" ]; then
            echo "API server is ready! (HTTP $status_code)"
            break
          fi
          if [ $elapsed -ge $timeout ]; then
            echo "Timeout waiting for API server (last status: $status_code)"
            exit 1
          fi
          echo "Waiting... ($elapsed seconds, status: $status_code)"
          sleep 2
          elapsed=$((elapsed + 2))
        done

    - name: Build dashboard and cookbook monorepo dependencies
      shell: bash
      run: npx turbo build --filter='@inkeep/agents-manage-ui' --filter='@inkeep/agents-cli' --filter='@inkeep/agents-core' --filter='@inkeep/agents-sdk'

    - name: Push Weather Example Project
      shell: bash
      env:
        INKEEP_API_KEY: ${{ env.INKEEP_AGENTS_MANAGE_API_BYPASS_SECRET }}
      run: |
        max_attempts=3
        attempt=1
        while [ $attempt -le $max_attempts ]; do
          echo "Push attempt $attempt/$max_attempts..."
          if cd agents-cookbook/template-projects && npx inkeep push --project weather-project; then
            echo "Push succeeded on attempt $attempt"
            break
          fi
          if [ $attempt -eq $max_attempts ]; then
            echo "Push failed after $max_attempts attempts"
            exit 1
          fi
          echo "Push failed, retrying in $((attempt * 5)) seconds..."
          sleep $((attempt * 5))
          cd "$GITHUB_WORKSPACE"
          attempt=$((attempt + 1))
        done

    - name: Run Cypress E2E Tests
      shell: bash
      run: pnpm --filter @inkeep/agents-manage-ui test:e2e:ci

    - name: Upload Cypress Screenshots
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-screenshots
        path: agents-manage-ui/cypress/screenshots
        retention-days: 7

    - name: Upload Cypress Videos
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-videos
        path: agents-manage-ui/cypress/videos
        retention-days: 7
