name: 'Cypress E2E Tests'
description: 'Run Cypress end-to-end tests with backend and frontend services'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22.x'
  pnpm-version:
    description: 'pnpm version to use'
    required: false
    default: '10.10.0'

runs:
  using: 'composite'
  steps:
    - name: Setup Cypress cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/Cypress
        key: ${{ runner.os }}-cypress-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-cypress-

    - name: Install Cypress binary
      shell: bash
      run: cd agents-manage-ui && npx cypress install

    - run: pnpm setup-dev
      shell: bash

    - name: Start Backend API Server
      shell: bash
      run: npx turbo dev --filter='@inkeep/agents-manage-api' &
      env:
        INKEEP_AGENTS_JWT_SIGNING_SECRET: "01234567890123456789012345678901"

    - name: Build Dashboard
      shell: bash
      run: npx turbo build --filter='@inkeep/agents-manage-ui'

    - name: Push Weather Example Project
      shell: bash
      run: cd examples && npx inkeep push --project weather-project
      env:
        INKEEP_AGENTS_JWT_SIGNING_SECRET: "01234567890123456789012345678901"

    - name: Run Cypress E2E Tests
      shell: bash
      run: pnpm --filter @inkeep/agents-manage-ui test:e2e:ci

    - name: Upload Cypress Screenshots
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-screenshots
        path: agents-manage-ui/cypress/screenshots
        retention-days: 7

    - name: Upload Cypress Videos
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-videos
        path: agents-manage-ui/cypress/videos
        retention-days: 7

    - name: Create E2E Test Summary
      if: always()
      shell: bash
      run: |
        echo "## Cypress E2E Test Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ **All Cypress E2E tests passed successfully!**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The validation test completed without errors." >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ **Cypress E2E tests failed**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "One or more E2E tests failed. Review the logs above for details." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Screenshots and videos have been uploaded as artifacts for debugging." >> $GITHUB_STEP_SUMMARY
        fi
