/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { InkeepAgentsCore } from '../core.js';
import { encodeSimple } from '../lib/encodings.js';
import * as M from '../lib/matchers.js';
import { compactMap } from '../lib/primitives.js';
import { safeParse } from '../lib/schemas.js';
import { RequestOptions } from '../lib/sdks.js';
import { pathToFunc } from '../lib/url.js';
import {
  DeleteArtifactComponentRequest,
  DeleteArtifactComponentRequest$zodSchema,
  DeleteArtifactComponentResponse,
  DeleteArtifactComponentResponse$zodSchema,
} from '../models/deleteartifactcomponentop.js';
import { APIError } from '../models/errors/apierror.js';
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from '../models/errors/httpclienterrors.js';
import { SDKValidationError } from '../models/errors/sdkvalidationerror.js';
import { APICall, APIPromise } from '../types/async.js';
import { Result } from '../types/fp.js';

/**
 * Delete Artifact Component
 */
export function artifactComponentDeleteArtifactComponent(
  client$: InkeepAgentsCore,
  request: DeleteArtifactComponentRequest,
  options?: RequestOptions
): APIPromise<
  Result<
    DeleteArtifactComponentResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(client$, request, options));
}

async function $do(
  client$: InkeepAgentsCore,
  request: DeleteArtifactComponentRequest,
  options?: RequestOptions
): Promise<
  [
    Result<
      DeleteArtifactComponentResponse,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) => DeleteArtifactComponentRequest$zodSchema.parse(value$),
    'Input validation failed'
  );
  if (!parsed$.ok) {
    return [parsed$, { status: 'invalid' }];
  }
  const payload$ = parsed$.value;
  const body$ = null;

  const pathParams$ = {
    id: encodeSimple('id', payload$.id, {
      explode: false,
      charEncoding: 'percent',
    }),
    projectId: encodeSimple('projectId', payload$.projectId, {
      explode: false,
      charEncoding: 'percent',
    }),
    tenantId: encodeSimple('tenantId', payload$.tenantId, {
      explode: false,
      charEncoding: 'percent',
    }),
  };
  const path$ = pathToFunc('/tenants/{tenantId}/projects/{projectId}/artifact-components/{id}')(
    pathParams$
  );

  const headers$ = new Headers(
    compactMap({
      Accept: 'application/json',
    })
  );

  const context = {
    options: client$._options,
    baseURL: options?.serverURL ?? client$._baseURL ?? '',
    operationID: 'delete-artifact-component',
    oAuth2Scopes: null,
    resolvedSecurity: null,
    securitySource: null,
    retryConfig: options?.retries || client$._options.retryConfig || { strategy: 'none' },
    retryCodes: options?.retryCodes || ['429', '500', '502', '503', '504'],
  };

  const requestRes = client$._createRequest(
    context,
    {
      method: 'DELETE',
      baseURL: options?.serverURL,
      path: path$,
      headers: headers$,
      body: body$,
      userAgent: client$._options.userAgent,
      timeoutMs: options?.timeoutMs || client$._options.timeoutMs || -1,
    },
    options
  );
  if (!requestRes.ok) {
    return [requestRes, { status: 'invalid' }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: 'request-error', request: req$ }];
  }
  const response = doResult.value;
  const responseFields$ = {
    HttpMeta: { Response: response, Request: req$ },
  };

  const [result$] = await M.match<
    DeleteArtifactComponentResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.nil(204, DeleteArtifactComponentResponse$zodSchema),
    M.json(404, DeleteArtifactComponentResponse$zodSchema, {
      key: 'ErrorResponse',
    })
  )(response, req$, { extraFields: responseFields$ });

  return [result$, { status: 'complete', request: req$, response }];
}
