/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import type { InkeepAgentsCore } from '../core.js';
import { encodeJSON, encodeSimple } from '../lib/encodings.js';
import * as M from '../lib/matchers.js';
import { compactMap } from '../lib/primitives.js';
import { safeParse } from '../lib/schemas.js';
import type { RequestOptions } from '../lib/sdks.js';
import { pathToFunc } from '../lib/url.js';
import {
  type CreateToolRequest,
  CreateToolRequest$zodSchema,
  type CreateToolResponse,
  CreateToolResponse$zodSchema,
} from '../models/createtoolop.js';
import type { APIError } from '../models/errors/apierror.js';
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from '../models/errors/httpclienterrors.js';
import type { SDKValidationError } from '../models/errors/sdkvalidationerror.js';
import { type APICall, APIPromise } from '../types/async.js';
import type { Result } from '../types/fp.js';

export enum CreateToolAcceptEnum {
  applicationJsonAccept = 'application/json',
  applicationProblemPlusJsonAccept = 'application/problem+json',
}

/**
 * Create Tool
 */
export function toolsCreateTool(
  client$: InkeepAgentsCore,
  request: CreateToolRequest,
  options?: RequestOptions
): APIPromise<
  Result<
    CreateToolResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(client$, request, options));
}

async function $do(
  client$: InkeepAgentsCore,
  request: CreateToolRequest,
  options?: RequestOptions & { acceptHeaderOverride?: CreateToolAcceptEnum }
): Promise<
  [
    Result<
      CreateToolResponse,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) => CreateToolRequest$zodSchema.parse(value$),
    'Input validation failed'
  );
  if (!parsed$.ok) {
    return [parsed$, { status: 'invalid' }];
  }
  const payload$ = parsed$.value;
  const body$ = encodeJSON('body', payload$.body, { explode: true });

  const pathParams$ = {
    projectId: encodeSimple('projectId', payload$.projectId, {
      explode: false,
      charEncoding: 'percent',
    }),
    tenantId: encodeSimple('tenantId', payload$.tenantId, {
      explode: false,
      charEncoding: 'percent',
    }),
  };
  const path$ = pathToFunc('/tenants/{tenantId}/projects/{projectId}/tools')(pathParams$);

  const headers$ = new Headers(
    compactMap({
      'Content-Type': 'application/json',
      Accept: options?.acceptHeaderOverride || 'application/json;q=1, application/problem+json;q=0',
    })
  );

  const context = {
    options: client$._options,
    baseURL: options?.serverURL ?? client$._baseURL ?? '',
    operationID: 'create-tool',
    oAuth2Scopes: null,
    resolvedSecurity: null,
    securitySource: null,
    retryConfig: options?.retries || client$._options.retryConfig || { strategy: 'none' },
    retryCodes: options?.retryCodes || ['429', '500', '502', '503', '504'],
  };

  const requestRes = client$._createRequest(
    context,
    {
      method: 'POST',
      baseURL: options?.serverURL,
      path: path$,
      headers: headers$,
      body: body$,
      userAgent: client$._options.userAgent,
      timeoutMs: options?.timeoutMs || client$._options.timeoutMs || -1,
    },
    options
  );
  if (!requestRes.ok) {
    return [requestRes, { status: 'invalid' }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: 'request-error', request: req$ }];
  }
  const response = doResult.value;
  const responseFields$ = {
    HttpMeta: { Response: response, Request: req$ },
  };

  const [result$] = await M.match<
    CreateToolResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.json(201, CreateToolResponse$zodSchema, { key: 'McpToolResponse' }),
    M.json(400, CreateToolResponse$zodSchema, {
      ctype: 'application/problem+json',
      key: 'BadRequest',
    }),
    M.json(401, CreateToolResponse$zodSchema, {
      ctype: 'application/problem+json',
      key: 'Unauthorized',
    }),
    M.json(403, CreateToolResponse$zodSchema, {
      ctype: 'application/problem+json',
      key: 'Forbidden',
    }),
    M.json(404, CreateToolResponse$zodSchema, {
      ctype: 'application/problem+json',
      key: 'NotFound',
    }),
    M.json(422, CreateToolResponse$zodSchema, {
      ctype: 'application/problem+json',
      key: 'UnprocessableEntity',
    }),
    M.json(500, CreateToolResponse$zodSchema, {
      ctype: 'application/problem+json',
      key: 'InternalServerError',
    })
  )(response, req$, { extraFields: responseFields$ });

  return [result$, { status: 'complete', request: req$, response }];
}
