/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { encodeFormQuery, encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { pathToFunc } from "../lib/url.js";
import { ListExternalAgentsRequest$zodSchema, ListExternalAgentsResponse$zodSchema, } from "../models/listexternalagentsop.js";
import { APIPromise } from "../types/async.js";
export var ListExternalAgentsAcceptEnum;
(function (ListExternalAgentsAcceptEnum) {
    ListExternalAgentsAcceptEnum["applicationJsonAccept"] = "application/json";
    ListExternalAgentsAcceptEnum["applicationProblemPlusJsonAccept"] = "application/problem+json";
})(ListExternalAgentsAcceptEnum || (ListExternalAgentsAcceptEnum = {}));
/**
 * List External Agents
 */
export function externalAgentsListExternalAgents(client$, request, options) {
    return new APIPromise($do(client$, request, options));
}
async function $do(client$, request, options) {
    const parsed$ = safeParse(request, (value$) => ListExternalAgentsRequest$zodSchema.parse(value$), "Input validation failed");
    if (!parsed$.ok) {
        return [parsed$, { status: "invalid" }];
    }
    const payload$ = parsed$.value;
    const body$ = null;
    const pathParams$ = {
        projectId: encodeSimple("projectId", payload$.projectId, {
            explode: false,
            charEncoding: "percent",
        }),
        tenantId: encodeSimple("tenantId", payload$.tenantId, {
            explode: false,
            charEncoding: "percent",
        }),
    };
    const path$ = pathToFunc("/tenants/{tenantId}/projects/{projectId}/external-agents")(pathParams$);
    const query$ = encodeFormQuery({
        "limit": payload$.limit,
        "page": payload$.page,
    });
    const headers$ = new Headers(compactMap({
        Accept: options?.acceptHeaderOverride
            || "application/json;q=1, application/problem+json;q=0",
    }));
    const context = {
        options: client$._options,
        baseURL: options?.serverURL ?? client$._baseURL ?? "",
        operationID: "list-external-agents",
        oAuth2Scopes: null,
        resolvedSecurity: null,
        securitySource: null,
        retryConfig: options?.retries
            || client$._options.retryConfig
            || { strategy: "none" },
        retryCodes: options?.retryCodes || [
            "429",
            "500",
            "502",
            "503",
            "504",
        ],
    };
    const requestRes = client$._createRequest(context, {
        method: "GET",
        baseURL: options?.serverURL,
        path: path$,
        headers: headers$,
        query: query$,
        body: body$,
        userAgent: client$._options.userAgent,
        timeoutMs: options?.timeoutMs || client$._options.timeoutMs
            || -1,
    }, options);
    if (!requestRes.ok) {
        return [requestRes, { status: "invalid" }];
    }
    const req$ = requestRes.value;
    const doResult = await client$._do(req$, {
        context,
        errorCodes: [],
        retryConfig: context.retryConfig,
        retryCodes: context.retryCodes,
    });
    if (!doResult.ok) {
        return [doResult, { status: "request-error", request: req$ }];
    }
    const response = doResult.value;
    const responseFields$ = {
        HttpMeta: { Response: response, Request: req$ },
    };
    const [result$] = await M.match(M.json(200, ListExternalAgentsResponse$zodSchema, {
        key: "ExternalAgentListResponse",
    }), M.json(400, ListExternalAgentsResponse$zodSchema, {
        ctype: "application/problem+json",
        key: "BadRequest",
    }), M.json(401, ListExternalAgentsResponse$zodSchema, {
        ctype: "application/problem+json",
        key: "Unauthorized",
    }), M.json(403, ListExternalAgentsResponse$zodSchema, {
        ctype: "application/problem+json",
        key: "Forbidden",
    }), M.json(404, ListExternalAgentsResponse$zodSchema, {
        ctype: "application/problem+json",
        key: "NotFound",
    }), M.json(422, ListExternalAgentsResponse$zodSchema, {
        ctype: "application/problem+json",
        key: "UnprocessableEntity",
    }), M.json(500, ListExternalAgentsResponse$zodSchema, {
        ctype: "application/problem+json",
        key: "InternalServerError",
    }))(response, req$, { extraFields: responseFields$ });
    return [result$, { status: "complete", request: req$, response }];
}
//# sourceMappingURL=externalAgentsListExternalAgents.js.map