/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { encodeJSON, encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { pathToFunc } from "../lib/url.js";
import { CreateFunctionToolRequest$zodSchema, CreateFunctionToolResponse$zodSchema, } from "../models/createfunctiontoolop.js";
import { APIPromise } from "../types/async.js";
export var CreateFunctionToolAcceptEnum;
(function (CreateFunctionToolAcceptEnum) {
    CreateFunctionToolAcceptEnum["applicationJsonAccept"] = "application/json";
    CreateFunctionToolAcceptEnum["applicationProblemPlusJsonAccept"] = "application/problem+json";
})(CreateFunctionToolAcceptEnum || (CreateFunctionToolAcceptEnum = {}));
/**
 * Create Function Tool
 */
export function functionToolsCreateFunctionTool(client$, request, options) {
    return new APIPromise($do(client$, request, options));
}
async function $do(client$, request, options) {
    const parsed$ = safeParse(request, (value$) => CreateFunctionToolRequest$zodSchema.parse(value$), "Input validation failed");
    if (!parsed$.ok) {
        return [parsed$, { status: "invalid" }];
    }
    const payload$ = parsed$.value;
    const body$ = encodeJSON("body", payload$.body, { explode: true });
    const pathParams$ = {
        agentId: encodeSimple("agentId", payload$.agentId, {
            explode: false,
            charEncoding: "percent",
        }),
        projectId: encodeSimple("projectId", payload$.projectId, {
            explode: false,
            charEncoding: "percent",
        }),
        tenantId: encodeSimple("tenantId", payload$.tenantId, {
            explode: false,
            charEncoding: "percent",
        }),
    };
    const path$ = pathToFunc("/tenants/{tenantId}/projects/{projectId}/agents/{agentId}/function-tools")(pathParams$);
    const headers$ = new Headers(compactMap({
        "Content-Type": "application/json",
        Accept: options?.acceptHeaderOverride
            || "application/json;q=1, application/problem+json;q=0",
    }));
    const context = {
        options: client$._options,
        baseURL: options?.serverURL ?? client$._baseURL ?? "",
        operationID: "create-function-tool",
        oAuth2Scopes: null,
        resolvedSecurity: null,
        securitySource: null,
        retryConfig: options?.retries
            || client$._options.retryConfig
            || { strategy: "none" },
        retryCodes: options?.retryCodes || [
            "429",
            "500",
            "502",
            "503",
            "504",
        ],
    };
    const requestRes = client$._createRequest(context, {
        method: "POST",
        baseURL: options?.serverURL,
        path: path$,
        headers: headers$,
        body: body$,
        userAgent: client$._options.userAgent,
        timeoutMs: options?.timeoutMs || client$._options.timeoutMs
            || -1,
    }, options);
    if (!requestRes.ok) {
        return [requestRes, { status: "invalid" }];
    }
    const req$ = requestRes.value;
    const doResult = await client$._do(req$, {
        context,
        errorCodes: [],
        retryConfig: context.retryConfig,
        retryCodes: context.retryCodes,
    });
    if (!doResult.ok) {
        return [doResult, { status: "request-error", request: req$ }];
    }
    const response = doResult.value;
    const responseFields$ = {
        HttpMeta: { Response: response, Request: req$ },
    };
    const [result$] = await M.match(M.json(201, CreateFunctionToolResponse$zodSchema, {
        key: "FunctionToolResponse",
    }), M.json(400, CreateFunctionToolResponse$zodSchema, {
        ctype: "application/problem+json",
        key: "BadRequest",
    }), M.json(401, CreateFunctionToolResponse$zodSchema, {
        ctype: "application/problem+json",
        key: "Unauthorized",
    }), M.json(403, CreateFunctionToolResponse$zodSchema, {
        ctype: "application/problem+json",
        key: "Forbidden",
    }), M.json(404, CreateFunctionToolResponse$zodSchema, {
        ctype: "application/problem+json",
        key: "NotFound",
    }), M.json(422, CreateFunctionToolResponse$zodSchema, {
        ctype: "application/problem+json",
        key: "UnprocessableEntity",
    }), M.json(500, CreateFunctionToolResponse$zodSchema, {
        ctype: "application/problem+json",
        key: "InternalServerError",
    }))(response, req$, { extraFields: responseFields$ });
    return [result$, { status: "complete", request: req$, response }];
}
//# sourceMappingURL=functionToolsCreateFunctionTool.js.map