/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3d946981cd16
 */

import { InkeepAgentsCore } from "../core.js";
import { encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import {
  InitiateToolOauthLoginRequest,
  InitiateToolOauthLoginRequest$zodSchema,
  InitiateToolOauthLoginResponse,
  InitiateToolOauthLoginResponse$zodSchema,
} from "../models/initiatetooloauthloginop.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Initiate OAuth login for MCP tool
 *
 * @remarks
 * Detects OAuth requirements and redirects to the authorization server for the specified tool
 */
export function toolsInitiateToolOauthLogin(
  client$: InkeepAgentsCore,
  request: InitiateToolOauthLoginRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    InitiateToolOauthLoginResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    request,
    options,
  ));
}

async function $do(
  client$: InkeepAgentsCore,
  request: InitiateToolOauthLoginRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      InitiateToolOauthLoginResponse,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) => InitiateToolOauthLoginRequest$zodSchema.parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = null;

  const pathParams$ = {
    id: encodeSimple("id", payload$.id, {
      explode: false,
      charEncoding: "percent",
    }),
    projectId: encodeSimple("projectId", payload$.projectId, {
      explode: false,
      charEncoding: "percent",
    }),
    tenantId: encodeSimple("tenantId", payload$.tenantId, {
      explode: false,
      charEncoding: "percent",
    }),
  };
  const path$ = pathToFunc(
    "/manage/tenants/{tenantId}/projects/{projectId}/tools/{id}/oauth/login",
  )(
    pathParams$,
  );

  const headers$ = new Headers(compactMap({
    Accept: "text/html",
  }));
  const securityInput = await extractSecurity(client$._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client$._options,
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "initiate-tool-oauth-login",
    oAuth2Scopes: null,
    resolvedSecurity: requestSecurity,
    securitySource: client$._options.security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    body: body$,
    userAgent: client$._options.userAgent,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  const response = doResult.value;
  const responseFields$ = {
    HttpMeta: { Response: response, Request: req$ },
  };

  const [result$] = await M.match<
    InitiateToolOauthLoginResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.nil(302, InitiateToolOauthLoginResponse$zodSchema),
    M.text(400, InitiateToolOauthLoginResponse$zodSchema, {
      ctype: "text/html",
      key: "fourHundredTextHtmlRes",
    }),
    M.text(404, InitiateToolOauthLoginResponse$zodSchema, {
      ctype: "text/html",
      key: "fourHundredAndFourTextHtmlRes",
    }),
    M.text(500, InitiateToolOauthLoginResponse$zodSchema, {
      ctype: "text/html",
      key: "fiveHundredTextHtmlRes",
    }),
  )(response, req$, { extraFields: responseFields$ });

  return [result$, { status: "complete", request: req$, response }];
}
