name: "Install"
description: "Sets up Node.js and runs install"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@c5ba7f7862a0f64c1b1a05fbac13e0b8e86ba08c # v4

    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: 22
        registry-url: "https://registry.npmjs.org"
        cache: "pnpm"

    - name: Setup Git User
      shell: bash
      run: |
        git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
        git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"

    - name: Install dependencies
      shell: bash
      run: pnpm install
      env:
        HUSKY: 0
