import {
  A2A_BACKOFF_EXPONENT,
  A2A_BACKOFF_INITIAL_INTERVAL_MS,
  A2A_BACKOFF_MAX_ELAPSED_TIME_MS,
  A2A_BACKOFF_MAX_INTERVAL_MS,
  AGENT_EXECUTION_MAX_CONSECUTIVE_ERRORS,
  AGENT_EXECUTION_TRANSFER_COUNT_DEFAULT,
  ARTIFACT_GENERATION_BACKOFF_INITIAL_MS,
  ARTIFACT_GENERATION_BACKOFF_MAX_MS,
  ARTIFACT_GENERATION_MAX_RETRIES,
  ARTIFACT_SESSION_MAX_PENDING,
  ARTIFACT_SESSION_MAX_PREVIOUS_SUMMARIES,
  CONVERSATION_HISTORY_DEFAULT_LIMIT,
  DELEGATION_TOOL_BACKOFF_EXPONENT,
  DELEGATION_TOOL_BACKOFF_INITIAL_INTERVAL_MS,
  DELEGATION_TOOL_BACKOFF_MAX_ELAPSED_TIME_MS,
  DELEGATION_TOOL_BACKOFF_MAX_INTERVAL_MS,
  FUNCTION_TOOL_EXECUTION_TIMEOUT_MS_DEFAULT,
  FUNCTION_TOOL_SANDBOX_CLEANUP_INTERVAL_MS,
  FUNCTION_TOOL_SANDBOX_MAX_OUTPUT_SIZE_BYTES,
  FUNCTION_TOOL_SANDBOX_MAX_USE_COUNT,
  FUNCTION_TOOL_SANDBOX_POOL_TTL_MS,
  FUNCTION_TOOL_SANDBOX_QUEUE_WAIT_TIMEOUT_MS,
  FUNCTION_TOOL_SANDBOX_VCPUS_DEFAULT,
  LLM_GENERATION_FIRST_CALL_TIMEOUT_MS_NON_STREAMING,
  LLM_GENERATION_FIRST_CALL_TIMEOUT_MS_STREAMING,
  LLM_GENERATION_MAX_ALLOWED_TIMEOUT_MS,
  LLM_GENERATION_SUBSEQUENT_CALL_TIMEOUT_MS,
  loadEnvironmentFiles,
  MCP_TOOL_CONNECTION_TIMEOUT_MS,
  MCP_TOOL_INITIAL_RECONNECTION_DELAY_MS,
  MCP_TOOL_MAX_RECONNECTION_DELAY_MS,
  MCP_TOOL_MAX_RETRIES,
  MCP_TOOL_RECONNECTION_DELAY_GROWTH_FACTOR,
  MCP_TOOL_REQUEST_TIMEOUT_MS_DEFAULT,
  SESSION_CLEANUP_INTERVAL_MS,
  SESSION_TOOL_RESULT_CACHE_TIMEOUT_MS,
  STATUS_UPDATE_DEFAULT_INTERVAL_SECONDS,
  STATUS_UPDATE_DEFAULT_NUM_EVENTS,
  STREAM_BUFFER_MAX_SIZE_BYTES,
  STREAM_MAX_LIFETIME_MS,
  STREAM_PARSER_MAX_COLLECTED_PARTS,
  STREAM_PARSER_MAX_SNAPSHOT_SIZE,
  STREAM_PARSER_MAX_STREAMED_SIZE,
  STREAM_TEXT_GAP_THRESHOLD_MS,
  SUB_AGENT_TURN_GENERATION_STEPS_DEFAULT,
} from '@inkeep/agents-core';
import { z } from 'zod';

// Load all environment files using shared logic
loadEnvironmentFiles();

const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'production', 'test']).optional(),
  ENVIRONMENT: z
    .enum(['development', 'production', 'pentest', 'test'])
    .optional()
    .default('development'),
  DB_FILE_NAME: z.string().optional(),
  TURSO_DATABASE_URL: z.string().optional(),
  TURSO_AUTH_TOKEN: z.string().optional(),
  AGENTS_RUN_API_URL: z.string().optional().default('http://localhost:3003'),
  LOG_LEVEL: z.enum(['trace', 'debug', 'info', 'warn', 'error']).optional().default('debug'),
  NANGO_SERVER_URL: z.string().optional().default('https://api.nango.dev'),
  NANGO_SECRET_KEY: z.string().optional(),
  ANTHROPIC_API_KEY: z.string(),
  OPENAI_API_KEY: z.string().optional(),
  GOOGLE_GENERATIVE_AI_API_KEY: z.string().optional(),
  INKEEP_AGENTS_RUN_API_BYPASS_SECRET: z.string().optional(),
  OTEL_BSP_SCHEDULE_DELAY: z.coerce.number().optional().default(500),
  OTEL_BSP_MAX_EXPORT_BATCH_SIZE: z.coerce.number().optional().default(64),
});

const parseEnv = () => {
  try {
    const parsedEnv = envSchema.parse(process.env);

    return parsedEnv;
  } catch (error) {
    if (error instanceof z.ZodError) {
      const missingVars = error.issues.map((issue) => issue.path.join('.'));
      throw new Error(
        `❌ Invalid environment variables: ${missingVars.join(', ')}\n${error.message}`
      );
    }
    throw error;
  }
};

export const env = parseEnv();
export type Env = z.infer<typeof envSchema>;

/**
 * Runtime Configuration Schema for Execution Constants
 * These constants control agent runtime behavior during execution.
 * They are defaults used when user configuration is null/undefined.
 * All values are optional and default to constants defined in agents-core.
 */
const runtimeConfigSchema = z.object({
  // Agent Execution Loop
  AGENTS_EXECUTION_TRANSFER_COUNT_DEFAULT: z.coerce.number().optional(),
  AGENTS_EXECUTION_MAX_CONSECUTIVE_ERRORS: z.coerce.number().optional(),

  // Sub-Agent Turn Execution
  AGENTS_SUB_AGENT_TURN_GENERATION_STEPS_DEFAULT: z.coerce.number().optional(),

  // LLM Generation Timeouts
  AGENTS_LLM_GENERATION_FIRST_CALL_TIMEOUT_MS_STREAMING: z.coerce.number().optional(),
  AGENTS_LLM_GENERATION_FIRST_CALL_TIMEOUT_MS_NON_STREAMING: z.coerce.number().optional(),
  AGENTS_LLM_GENERATION_SUBSEQUENT_CALL_TIMEOUT_MS: z.coerce.number().optional(),
  AGENTS_LLM_GENERATION_MAX_ALLOWED_TIMEOUT_MS: z.coerce.number().optional(),

  // Function Tool Execution (Sandbox)
  AGENTS_FUNCTION_TOOL_EXECUTION_TIMEOUT_MS_DEFAULT: z.coerce.number().optional(),
  AGENTS_FUNCTION_TOOL_SANDBOX_VCPUS_DEFAULT: z.coerce.number().optional(),
  AGENTS_FUNCTION_TOOL_SANDBOX_POOL_TTL_MS: z.coerce.number().optional(),
  AGENTS_FUNCTION_TOOL_SANDBOX_MAX_USE_COUNT: z.coerce.number().optional(),
  AGENTS_FUNCTION_TOOL_SANDBOX_MAX_OUTPUT_SIZE_BYTES: z.coerce.number().optional(),
  AGENTS_FUNCTION_TOOL_SANDBOX_QUEUE_WAIT_TIMEOUT_MS: z.coerce.number().optional(),
  AGENTS_FUNCTION_TOOL_SANDBOX_CLEANUP_INTERVAL_MS: z.coerce.number().optional(),

  // MCP Tool Execution
  AGENTS_MCP_TOOL_REQUEST_TIMEOUT_MS_DEFAULT: z.coerce.number().optional(),
  AGENTS_MCP_TOOL_CONNECTION_TIMEOUT_MS: z.coerce.number().optional(),
  AGENTS_MCP_TOOL_MAX_RETRIES: z.coerce.number().optional(),
  AGENTS_MCP_TOOL_MAX_RECONNECTION_DELAY_MS: z.coerce.number().optional(),
  AGENTS_MCP_TOOL_INITIAL_RECONNECTION_DELAY_MS: z.coerce.number().optional(),
  AGENTS_MCP_TOOL_RECONNECTION_DELAY_GROWTH_FACTOR: z.coerce.number().optional(),

  // Delegation Tool Execution
  AGENTS_DELEGATION_TOOL_BACKOFF_INITIAL_INTERVAL_MS: z.coerce.number().optional(),
  AGENTS_DELEGATION_TOOL_BACKOFF_MAX_INTERVAL_MS: z.coerce.number().optional(),
  AGENTS_DELEGATION_TOOL_BACKOFF_EXPONENT: z.coerce.number().optional(),
  AGENTS_DELEGATION_TOOL_BACKOFF_MAX_ELAPSED_TIME_MS: z.coerce.number().optional(),

  // General A2A Communication
  AGENTS_A2A_BACKOFF_INITIAL_INTERVAL_MS: z.coerce.number().optional(),
  AGENTS_A2A_BACKOFF_MAX_INTERVAL_MS: z.coerce.number().optional(),
  AGENTS_A2A_BACKOFF_EXPONENT: z.coerce.number().optional(),
  AGENTS_A2A_BACKOFF_MAX_ELAPSED_TIME_MS: z.coerce.number().optional(),

  // Artifact Processing
  AGENTS_ARTIFACT_GENERATION_MAX_RETRIES: z.coerce.number().optional(),
  AGENTS_ARTIFACT_SESSION_MAX_PENDING: z.coerce.number().optional(),
  AGENTS_ARTIFACT_SESSION_MAX_PREVIOUS_SUMMARIES: z.coerce.number().optional(),
  AGENTS_ARTIFACT_GENERATION_BACKOFF_INITIAL_MS: z.coerce.number().optional(),
  AGENTS_ARTIFACT_GENERATION_BACKOFF_MAX_MS: z.coerce.number().optional(),

  // Session & Cache Management
  AGENTS_SESSION_TOOL_RESULT_CACHE_TIMEOUT_MS: z.coerce.number().optional(),
  AGENTS_SESSION_CLEANUP_INTERVAL_MS: z.coerce.number().optional(),

  // Status Updates & Streaming
  AGENTS_STATUS_UPDATE_DEFAULT_NUM_EVENTS: z.coerce.number().optional(),
  AGENTS_STATUS_UPDATE_DEFAULT_INTERVAL_SECONDS: z.coerce.number().optional(),

  // Stream Buffer Limits
  AGENTS_STREAM_PARSER_MAX_SNAPSHOT_SIZE: z.coerce.number().optional(),
  AGENTS_STREAM_PARSER_MAX_STREAMED_SIZE: z.coerce.number().optional(),
  AGENTS_STREAM_PARSER_MAX_COLLECTED_PARTS: z.coerce.number().optional(),
  AGENTS_STREAM_BUFFER_MAX_SIZE_BYTES: z.coerce.number().optional(),
  AGENTS_STREAM_TEXT_GAP_THRESHOLD_MS: z.coerce.number().optional(),
  AGENTS_STREAM_MAX_LIFETIME_MS: z.coerce.number().optional(),

  // Conversation History
  AGENTS_CONVERSATION_HISTORY_DEFAULT_LIMIT: z.coerce.number().optional(),
});

const parseRuntimeConfig = () => {
  const envOverrides = runtimeConfigSchema.parse(process.env);

  return {
    // Agent Execution Loop
    AGENT_EXECUTION_TRANSFER_COUNT_DEFAULT:
      envOverrides.AGENTS_EXECUTION_TRANSFER_COUNT_DEFAULT ?? AGENT_EXECUTION_TRANSFER_COUNT_DEFAULT,
    AGENT_EXECUTION_MAX_CONSECUTIVE_ERRORS:
      envOverrides.AGENTS_EXECUTION_MAX_CONSECUTIVE_ERRORS ?? AGENT_EXECUTION_MAX_CONSECUTIVE_ERRORS,

    // Sub-Agent Turn Execution
    SUB_AGENT_TURN_GENERATION_STEPS_DEFAULT:
      envOverrides.AGENTS_SUB_AGENT_TURN_GENERATION_STEPS_DEFAULT ??
      SUB_AGENT_TURN_GENERATION_STEPS_DEFAULT,

    // LLM Generation Timeouts
    LLM_GENERATION_FIRST_CALL_TIMEOUT_MS_STREAMING:
      envOverrides.AGENTS_LLM_GENERATION_FIRST_CALL_TIMEOUT_MS_STREAMING ??
      LLM_GENERATION_FIRST_CALL_TIMEOUT_MS_STREAMING,
    LLM_GENERATION_FIRST_CALL_TIMEOUT_MS_NON_STREAMING:
      envOverrides.AGENTS_LLM_GENERATION_FIRST_CALL_TIMEOUT_MS_NON_STREAMING ??
      LLM_GENERATION_FIRST_CALL_TIMEOUT_MS_NON_STREAMING,
    LLM_GENERATION_SUBSEQUENT_CALL_TIMEOUT_MS:
      envOverrides.AGENTS_LLM_GENERATION_SUBSEQUENT_CALL_TIMEOUT_MS ??
      LLM_GENERATION_SUBSEQUENT_CALL_TIMEOUT_MS,
    LLM_GENERATION_MAX_ALLOWED_TIMEOUT_MS:
      envOverrides.AGENTS_LLM_GENERATION_MAX_ALLOWED_TIMEOUT_MS ??
      LLM_GENERATION_MAX_ALLOWED_TIMEOUT_MS,

    // Function Tool Execution (Sandbox)
    FUNCTION_TOOL_EXECUTION_TIMEOUT_MS_DEFAULT:
      envOverrides.AGENTS_FUNCTION_TOOL_EXECUTION_TIMEOUT_MS_DEFAULT ??
      FUNCTION_TOOL_EXECUTION_TIMEOUT_MS_DEFAULT,
    FUNCTION_TOOL_SANDBOX_VCPUS_DEFAULT:
      envOverrides.AGENTS_FUNCTION_TOOL_SANDBOX_VCPUS_DEFAULT ??
      FUNCTION_TOOL_SANDBOX_VCPUS_DEFAULT,
    FUNCTION_TOOL_SANDBOX_POOL_TTL_MS:
      envOverrides.AGENTS_FUNCTION_TOOL_SANDBOX_POOL_TTL_MS ?? FUNCTION_TOOL_SANDBOX_POOL_TTL_MS,
    FUNCTION_TOOL_SANDBOX_MAX_USE_COUNT:
      envOverrides.AGENTS_FUNCTION_TOOL_SANDBOX_MAX_USE_COUNT ??
      FUNCTION_TOOL_SANDBOX_MAX_USE_COUNT,
    FUNCTION_TOOL_SANDBOX_MAX_OUTPUT_SIZE_BYTES:
      envOverrides.AGENTS_FUNCTION_TOOL_SANDBOX_MAX_OUTPUT_SIZE_BYTES ??
      FUNCTION_TOOL_SANDBOX_MAX_OUTPUT_SIZE_BYTES,
    FUNCTION_TOOL_SANDBOX_QUEUE_WAIT_TIMEOUT_MS:
      envOverrides.AGENTS_FUNCTION_TOOL_SANDBOX_QUEUE_WAIT_TIMEOUT_MS ??
      FUNCTION_TOOL_SANDBOX_QUEUE_WAIT_TIMEOUT_MS,
    FUNCTION_TOOL_SANDBOX_CLEANUP_INTERVAL_MS:
      envOverrides.AGENTS_FUNCTION_TOOL_SANDBOX_CLEANUP_INTERVAL_MS ??
      FUNCTION_TOOL_SANDBOX_CLEANUP_INTERVAL_MS,

    // MCP Tool Execution
    MCP_TOOL_REQUEST_TIMEOUT_MS_DEFAULT:
      envOverrides.AGENTS_MCP_TOOL_REQUEST_TIMEOUT_MS_DEFAULT ??
      MCP_TOOL_REQUEST_TIMEOUT_MS_DEFAULT,
    MCP_TOOL_CONNECTION_TIMEOUT_MS:
      envOverrides.AGENTS_MCP_TOOL_CONNECTION_TIMEOUT_MS ?? MCP_TOOL_CONNECTION_TIMEOUT_MS,
    MCP_TOOL_MAX_RETRIES: envOverrides.AGENTS_MCP_TOOL_MAX_RETRIES ?? MCP_TOOL_MAX_RETRIES,
    MCP_TOOL_MAX_RECONNECTION_DELAY_MS:
      envOverrides.AGENTS_MCP_TOOL_MAX_RECONNECTION_DELAY_MS ??
      MCP_TOOL_MAX_RECONNECTION_DELAY_MS,
    MCP_TOOL_INITIAL_RECONNECTION_DELAY_MS:
      envOverrides.AGENTS_MCP_TOOL_INITIAL_RECONNECTION_DELAY_MS ??
      MCP_TOOL_INITIAL_RECONNECTION_DELAY_MS,
    MCP_TOOL_RECONNECTION_DELAY_GROWTH_FACTOR:
      envOverrides.AGENTS_MCP_TOOL_RECONNECTION_DELAY_GROWTH_FACTOR ??
      MCP_TOOL_RECONNECTION_DELAY_GROWTH_FACTOR,

    // Delegation Tool Execution
    DELEGATION_TOOL_BACKOFF_INITIAL_INTERVAL_MS:
      envOverrides.AGENTS_DELEGATION_TOOL_BACKOFF_INITIAL_INTERVAL_MS ??
      DELEGATION_TOOL_BACKOFF_INITIAL_INTERVAL_MS,
    DELEGATION_TOOL_BACKOFF_MAX_INTERVAL_MS:
      envOverrides.AGENTS_DELEGATION_TOOL_BACKOFF_MAX_INTERVAL_MS ??
      DELEGATION_TOOL_BACKOFF_MAX_INTERVAL_MS,
    DELEGATION_TOOL_BACKOFF_EXPONENT:
      envOverrides.AGENTS_DELEGATION_TOOL_BACKOFF_EXPONENT ?? DELEGATION_TOOL_BACKOFF_EXPONENT,
    DELEGATION_TOOL_BACKOFF_MAX_ELAPSED_TIME_MS:
      envOverrides.AGENTS_DELEGATION_TOOL_BACKOFF_MAX_ELAPSED_TIME_MS ??
      DELEGATION_TOOL_BACKOFF_MAX_ELAPSED_TIME_MS,

    // General A2A Communication
    A2A_BACKOFF_INITIAL_INTERVAL_MS:
      envOverrides.AGENTS_A2A_BACKOFF_INITIAL_INTERVAL_MS ?? A2A_BACKOFF_INITIAL_INTERVAL_MS,
    A2A_BACKOFF_MAX_INTERVAL_MS:
      envOverrides.AGENTS_A2A_BACKOFF_MAX_INTERVAL_MS ?? A2A_BACKOFF_MAX_INTERVAL_MS,
    A2A_BACKOFF_EXPONENT: envOverrides.AGENTS_A2A_BACKOFF_EXPONENT ?? A2A_BACKOFF_EXPONENT,
    A2A_BACKOFF_MAX_ELAPSED_TIME_MS:
      envOverrides.AGENTS_A2A_BACKOFF_MAX_ELAPSED_TIME_MS ?? A2A_BACKOFF_MAX_ELAPSED_TIME_MS,

    // Artifact Processing
    ARTIFACT_GENERATION_MAX_RETRIES:
      envOverrides.AGENTS_ARTIFACT_GENERATION_MAX_RETRIES ?? ARTIFACT_GENERATION_MAX_RETRIES,
    ARTIFACT_SESSION_MAX_PENDING:
      envOverrides.AGENTS_ARTIFACT_SESSION_MAX_PENDING ?? ARTIFACT_SESSION_MAX_PENDING,
    ARTIFACT_SESSION_MAX_PREVIOUS_SUMMARIES:
      envOverrides.AGENTS_ARTIFACT_SESSION_MAX_PREVIOUS_SUMMARIES ??
      ARTIFACT_SESSION_MAX_PREVIOUS_SUMMARIES,
    ARTIFACT_GENERATION_BACKOFF_INITIAL_MS:
      envOverrides.AGENTS_ARTIFACT_GENERATION_BACKOFF_INITIAL_MS ??
      ARTIFACT_GENERATION_BACKOFF_INITIAL_MS,
    ARTIFACT_GENERATION_BACKOFF_MAX_MS:
      envOverrides.AGENTS_ARTIFACT_GENERATION_BACKOFF_MAX_MS ?? ARTIFACT_GENERATION_BACKOFF_MAX_MS,

    // Session & Cache Management
    SESSION_TOOL_RESULT_CACHE_TIMEOUT_MS:
      envOverrides.AGENTS_SESSION_TOOL_RESULT_CACHE_TIMEOUT_MS ??
      SESSION_TOOL_RESULT_CACHE_TIMEOUT_MS,
    SESSION_CLEANUP_INTERVAL_MS:
      envOverrides.AGENTS_SESSION_CLEANUP_INTERVAL_MS ?? SESSION_CLEANUP_INTERVAL_MS,

    // Status Updates & Streaming
    STATUS_UPDATE_DEFAULT_NUM_EVENTS:
      envOverrides.AGENTS_STATUS_UPDATE_DEFAULT_NUM_EVENTS ?? STATUS_UPDATE_DEFAULT_NUM_EVENTS,
    STATUS_UPDATE_DEFAULT_INTERVAL_SECONDS:
      envOverrides.AGENTS_STATUS_UPDATE_DEFAULT_INTERVAL_SECONDS ??
      STATUS_UPDATE_DEFAULT_INTERVAL_SECONDS,

    // Stream Buffer Limits
    STREAM_PARSER_MAX_SNAPSHOT_SIZE:
      envOverrides.AGENTS_STREAM_PARSER_MAX_SNAPSHOT_SIZE ?? STREAM_PARSER_MAX_SNAPSHOT_SIZE,
    STREAM_PARSER_MAX_STREAMED_SIZE:
      envOverrides.AGENTS_STREAM_PARSER_MAX_STREAMED_SIZE ?? STREAM_PARSER_MAX_STREAMED_SIZE,
    STREAM_PARSER_MAX_COLLECTED_PARTS:
      envOverrides.AGENTS_STREAM_PARSER_MAX_COLLECTED_PARTS ?? STREAM_PARSER_MAX_COLLECTED_PARTS,
    STREAM_BUFFER_MAX_SIZE_BYTES:
      envOverrides.AGENTS_STREAM_BUFFER_MAX_SIZE_BYTES ?? STREAM_BUFFER_MAX_SIZE_BYTES,
    STREAM_TEXT_GAP_THRESHOLD_MS:
      envOverrides.AGENTS_STREAM_TEXT_GAP_THRESHOLD_MS ?? STREAM_TEXT_GAP_THRESHOLD_MS,
    STREAM_MAX_LIFETIME_MS: envOverrides.AGENTS_STREAM_MAX_LIFETIME_MS ?? STREAM_MAX_LIFETIME_MS,

    // Conversation History
    CONVERSATION_HISTORY_DEFAULT_LIMIT:
      envOverrides.AGENTS_CONVERSATION_HISTORY_DEFAULT_LIMIT ?? CONVERSATION_HISTORY_DEFAULT_LIMIT,
  };
};

/**
 * Runtime configuration object that merges environment variable overrides with default constants.
 * Use this instead of importing constants directly to respect environment variable overrides.
 */
export const runtimeConfig = parseRuntimeConfig();
