/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { agentArtifactComponentRelationsGetArtifactComponentsForAgent } from "../../funcs/agentArtifactComponentRelationsGetArtifactComponentsForAgent.js";
import { GetArtifactComponentsForAgentRequest$zodSchema } from "../../models/getartifactcomponentsforagentop.js";
import { formatResult } from "../tools.js";
const args = {
    request: GetArtifactComponentsForAgentRequest$zodSchema,
};
export const tool$agentArtifactComponentRelationsGetArtifactComponentsForAgent = {
    name: "agent-artifact-component-relations-get-artifact-components-for-agent",
    description: `Get Artifact Components for Agent`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result, apiCall] = await agentArtifactComponentRelationsGetArtifactComponentsForAgent(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        const value = result.value;
        return formatResult(value, apiCall);
    },
};
//# sourceMappingURL=agentArtifactComponentRelationsGetArtifactComponentsForAgent.js.map