/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { credentialStoreCreateCredentialInStore } from "../../funcs/credentialStoreCreateCredentialInStore.js";
import { CreateCredentialInStoreRequestRequest$zodSchema } from "../../models/createcredentialinstoreop.js";
import { formatResult } from "../tools.js";
const args = {
    request: CreateCredentialInStoreRequestRequest$zodSchema,
};
export const tool$credentialStoreCreateCredentialInStore = {
    name: "credential-store-create-credential-in-store",
    description: `Create Credential in Store`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result, apiCall] = await credentialStoreCreateCredentialInStore(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        const value = result.value;
        return formatResult(value, apiCall);
    },
};
//# sourceMappingURL=credentialStoreCreateCredentialInStore.js.map