/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { credentialGetCredentialById } from "../../funcs/credentialGetCredentialById.js";
import { GetCredentialByIdRequest$zodSchema } from "../../models/getcredentialbyidop.js";
import { formatResult } from "../tools.js";
const args = {
    request: GetCredentialByIdRequest$zodSchema,
};
export const tool$credentialGetCredentialById = {
    name: "credential-get-credential-by-id",
    description: `Get Credential`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result, apiCall] = await credentialGetCredentialById(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        const value = result.value;
        return formatResult(value, apiCall);
    },
};
//# sourceMappingURL=credentialGetCredentialById.js.map