/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { dataComponentGetDataComponentById } from "../../funcs/dataComponentGetDataComponentById.js";
import { GetDataComponentByIdRequest$zodSchema } from "../../models/getdatacomponentbyidop.js";
import { formatResult } from "../tools.js";
const args = {
    request: GetDataComponentByIdRequest$zodSchema,
};
export const tool$dataComponentGetDataComponentById = {
    name: "data-component-get-data-component-by-id",
    description: `Get Data Component`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result, apiCall] = await dataComponentGetDataComponentById(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        const value = result.value;
        return formatResult(value, apiCall);
    },
};
//# sourceMappingURL=dataComponentGetDataComponentById.js.map