/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { dataComponentUpdateDataComponent } from "../../funcs/dataComponentUpdateDataComponent.js";
import { UpdateDataComponentRequest$zodSchema } from "../../models/updatedatacomponentop.js";
import { formatResult } from "../tools.js";
const args = {
    request: UpdateDataComponentRequest$zodSchema,
};
export const tool$dataComponentUpdateDataComponent = {
    name: "data-component-update-data-component",
    description: `Update Data Component`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result, apiCall] = await dataComponentUpdateDataComponent(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        const value = result.value;
        return formatResult(value, apiCall);
    },
};
//# sourceMappingURL=dataComponentUpdateDataComponent.js.map