/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { functionToolsGetFunctionTool } from "../../funcs/functionToolsGetFunctionTool.js";
import { GetFunctionToolRequest$zodSchema } from "../../models/getfunctiontoolop.js";
import { formatResult } from "../tools.js";
const args = {
    request: GetFunctionToolRequest$zodSchema,
};
export const tool$functionToolsGetFunctionTool = {
    name: "function-tools-get-function-tool",
    description: `Get Function Tool by ID`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result, apiCall] = await functionToolsGetFunctionTool(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        const value = result.value;
        return formatResult(value, apiCall);
    },
};
//# sourceMappingURL=functionToolsGetFunctionTool.js.map