/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { functionsUpdateFunction } from "../../funcs/functionsUpdateFunction.js";
import { UpdateFunctionRequest$zodSchema } from "../../models/updatefunctionop.js";
import { formatResult } from "../tools.js";
const args = {
    request: UpdateFunctionRequest$zodSchema,
};
export const tool$functionsUpdateFunction = {
    name: "functions-update-function",
    description: `Update Function`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result, apiCall] = await functionsUpdateFunction(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        const value = result.value;
        return formatResult(value, apiCall);
    },
};
//# sourceMappingURL=functionsUpdateFunction.js.map