/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { functionsListFunctions } from "../../funcs/functionsListFunctions.js";
import { ListFunctionsRequest$zodSchema } from "../../models/listfunctionsop.js";
import { formatResult } from "../tools.js";
const args = {
    request: ListFunctionsRequest$zodSchema,
};
export const tool$functionsListFunctions = {
    name: "functions-list-functions",
    description: `List Functions`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result, apiCall] = await functionsListFunctions(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        const value = result.value;
        return formatResult(value, apiCall);
    },
};
//# sourceMappingURL=functionsListFunctions.js.map