/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { health } from "../../funcs/health.js";
import { formatResult } from "../tools.js";
export const tool$health = {
    name: "health",
    description: `Health check

Check if the management service is healthy`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": true,
    },
    tool: async (client, ctx) => {
        const [result, apiCall] = await health(client, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(void 0, apiCall);
    },
};
//# sourceMappingURL=health.js.map