/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { projectsListProjects } from "../../funcs/projectsListProjects.js";
import { ListProjectsRequest$zodSchema } from "../../models/listprojectsop.js";
import { formatResult } from "../tools.js";
const args = {
    request: ListProjectsRequest$zodSchema,
};
export const tool$projectsListProjects = {
    name: "projects-list-projects",
    description: `List Projects

List all projects within a tenant with pagination`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result, apiCall] = await projectsListProjects(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        const value = result.value;
        return formatResult(value, apiCall);
    },
};
//# sourceMappingURL=projectsListProjects.js.map