/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { subAgentToolRelationsGetSubagentToolRelation } from "../../funcs/subAgentToolRelationsGetSubagentToolRelation.js";
import { GetSubagentToolRelationRequest$zodSchema } from "../../models/getsubagenttoolrelationop.js";
import { formatResult } from "../tools.js";
const args = {
    request: GetSubagentToolRelationRequest$zodSchema,
};
export const tool$subAgentToolRelationsGetSubagentToolRelation = {
    name: "sub-agent-tool-relations-get-subagent-tool-relation",
    description: `Get SubAgent Tool Relation`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result, apiCall] = await subAgentToolRelationsGetSubagentToolRelation(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        const value = result.value;
        return formatResult(value, apiCall);
    },
};
//# sourceMappingURL=subAgentToolRelationsGetSubagentToolRelation.js.map