/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { subAgentToolRelationsDeleteSubagentToolRelation } from "../../funcs/subAgentToolRelationsDeleteSubagentToolRelation.js";
import { DeleteSubagentToolRelationRequest$zodSchema } from "../../models/deletesubagenttoolrelationop.js";
import { formatResult } from "../tools.js";
const args = {
    request: DeleteSubagentToolRelationRequest$zodSchema,
};
export const tool$subAgentToolRelationsDeleteSubagentToolRelation = {
    name: "sub-agent-tool-relations-delete-subagent-tool-relation",
    description: `Delete SubAgent Tool Relation`,
    annotations: {
        "title": "",
        "destructiveHint": true,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result, apiCall] = await subAgentToolRelationsDeleteSubagentToolRelation(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        const value = result.value;
        return formatResult(value, apiCall);
    },
};
//# sourceMappingURL=subAgentToolRelationsDeleteSubagentToolRelation.js.map