/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { subAgentTeamAgentRelationsDeleteSubAgentTeamAgentRelation } from "../../funcs/subAgentTeamAgentRelationsDeleteSubAgentTeamAgentRelation.js";
import { DeleteSubAgentTeamAgentRelationRequest$zodSchema } from "../../models/deletesubagentteamagentrelationop.js";
import { formatResult } from "../tools.js";
const args = {
    request: DeleteSubAgentTeamAgentRelationRequest$zodSchema,
};
export const tool$subAgentTeamAgentRelationsDeleteSubAgentTeamAgentRelation = {
    name: "sub-agent-team-agent-relations-delete-sub-agent-team-agent-relation",
    description: `Delete Sub Agent Team Agent Relation`,
    annotations: {
        "title": "",
        "destructiveHint": true,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result, apiCall] = await subAgentTeamAgentRelationsDeleteSubAgentTeamAgentRelation(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        const value = result.value;
        return formatResult(value, apiCall);
    },
};
//# sourceMappingURL=subAgentTeamAgentRelationsDeleteSubAgentTeamAgentRelation.js.map