/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { subAgentCreateSubagent } from "../../funcs/subAgentCreateSubagent.js";
import { CreateSubagentRequest$zodSchema } from "../../models/createsubagentop.js";
import { formatResult } from "../tools.js";
const args = {
    request: CreateSubagentRequest$zodSchema,
};
export const tool$subAgentCreateSubagent = {
    name: "sub-agent-create-subagent",
    description: `Create SubAgent`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result, apiCall] = await subAgentCreateSubagent(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        const value = result.value;
        return formatResult(value, apiCall);
    },
};
//# sourceMappingURL=subAgentCreateSubagent.js.map