/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const Agent$zodSchema = z
    .object({
    contextConfigId: z.string().nullable(),
    createdAt: z.string(),
    defaultSubAgentId: z.string().nullable(),
    description: z.string().nullable(),
    id: z.string(),
    models: z.any().nullable().optional(),
    name: z.string(),
    prompt: z.string().nullable(),
    statusUpdates: z.any().nullable().optional(),
    stopWhen: z.any().nullable().optional(),
    updatedAt: z.string(),
});
//# sourceMappingURL=agent.js.map