/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const AgentStopWhen$zodSchema = z.object({
    transferCountIs: z.number().optional(),
});
//# sourceMappingURL=agentstopwhen.js.map