/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { Agent$zodSchema } from "./agent.js";
import { Pagination$zodSchema } from "./pagination.js";
export const AgentListResponse$zodSchema = z.object({
    data: z.array(Agent$zodSchema),
    pagination: Pagination$zodSchema,
});
//# sourceMappingURL=agentlistresponse.js.map