/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { ApiKey$zodSchema } from "./apikey.js";
import { Pagination$zodSchema } from "./pagination.js";
export const ApiKeyListResponse$zodSchema = z.object({
    data: z.array(ApiKey$zodSchema),
    pagination: Pagination$zodSchema,
});
//# sourceMappingURL=apikeylistresponse.js.map