/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const ApiKeyUpdate$zodSchema = z.object({
    agentId: z.string().optional(),
    expiresAt: z.string().nullable().optional(),
    lastUsedAt: z.string().nullable().optional(),
    name: z.string().nullable().optional(),
    updatedAt: z.string().optional(),
});
//# sourceMappingURL=apikeyupdate.js.map