/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const ArtifactComponentCreate$zodSchema = z.object({
    description: z.string(),
    id: z.string(),
    name: z.string(),
    props: z.any().nullable().optional(),
});
//# sourceMappingURL=artifactcomponentcreate.js.map