/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { ArtifactComponent$zodSchema, } from "./artifactcomponent.js";
export const ArtifactComponentArrayResponse$zodSchema = z.object({
    data: z.array(ArtifactComponent$zodSchema),
});
//# sourceMappingURL=artifactcomponentarrayresponse.js.map