/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
/**
 * A short code indicating the error code returned.
 */
export const BadRequestCode1$zodSchema = z.enum([
    "bad_request",
]).describe("A short code indicating the error code returned.");
/**
 * A short code indicating the error code returned.
 */
export const BadRequestCode2$zodSchema = z.enum([
    "bad_request",
]).describe("A short code indicating the error code returned.");
export const BadRequestError$zodSchema = z.object({
    code: BadRequestCode2$zodSchema,
    message: z.string(),
}).describe("Legacy error format for backward compatibility.");
export const BadRequest$zodSchema = z.object({
    code: BadRequestCode1$zodSchema,
    detail: z.string(),
    error: z.lazy(() => BadRequestError$zodSchema),
    instance: z.string().optional(),
    requestId: z.string().optional(),
    status: z.number().int(),
    title: z.string(),
});
//# sourceMappingURL=badrequest.js.map