/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const CredentialStoreType$zodSchema = z.enum([
    "memory",
    "keychain",
    "nango",
]);
export const CredentialStore$zodSchema = z.object({
    available: z.boolean(),
    id: z.string(),
    reason: z.string().nullable(),
    type: CredentialStoreType$zodSchema,
});
//# sourceMappingURL=credentialstore.js.map