/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { DataComponent$zodSchema } from "./datacomponent.js";
export const DataComponentResponse$zodSchema = z.object({
    data: DataComponent$zodSchema,
});
//# sourceMappingURL=datacomponentresponse.js.map