/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const ExternalAgent$zodSchema = z.object({
    baseUrl: z.string(),
    createdAt: z.string(),
    credentialReferenceId: z.string().nullable().optional(),
    description: z.string(),
    id: z.string(),
    name: z.string(),
    updatedAt: z.string(),
});
//# sourceMappingURL=externalagent.js.map