/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const FunctionToolCreate$zodSchema = z.object({
    createdAt: z.string().optional(),
    description: z.string().nullable().optional(),
    functionId: z.string(),
    id: z.string(),
    name: z.string(),
    updatedAt: z.string().optional(),
});
//# sourceMappingURL=functiontoolcreate.js.map