/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { FunctionT$zodSchema } from "./function.js";
import { Pagination$zodSchema } from "./pagination.js";
export const FunctionListResponse$zodSchema = z.object({
    data: z.array(FunctionT$zodSchema),
    pagination: Pagination$zodSchema,
});
//# sourceMappingURL=functionlistresponse.js.map