/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden$zodSchema } from "./forbidden.js";
import { InternalServerError$zodSchema, } from "./internalservererror.js";
import { NotFound$zodSchema } from "./notfound.js";
import { RelatedAgentInfoListResponse$zodSchema, } from "./relatedagentinfolistresponse.js";
import { Unauthorized$zodSchema } from "./unauthorized.js";
import { UnprocessableEntity$zodSchema, } from "./unprocessableentity.js";
export const GetRelatedAgentInfosRequest$zodSchema = z.object({
    agentId: z.string().describe("Agent identifier"),
    projectId: z.string().describe("Project identifier"),
    subAgentId: z.string().describe("Sub-agent identifier"),
    tenantId: z.string().describe("Tenant identifier"),
});
export const GetRelatedAgentInfosResponse$zodSchema = z.object({
    BadRequest: BadRequest$zodSchema.optional(),
    ContentType: z.string(),
    Forbidden: Forbidden$zodSchema.optional(),
    InternalServerError: InternalServerError$zodSchema.optional(),
    NotFound: NotFound$zodSchema.optional(),
    RawResponse: z.instanceof(Response),
    RelatedAgentInfoListResponse: RelatedAgentInfoListResponse$zodSchema
        .optional(),
    StatusCode: z.number().int(),
    Unauthorized: Unauthorized$zodSchema.optional(),
    UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
//# sourceMappingURL=getrelatedagentinfosop.js.map