/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden$zodSchema } from "./forbidden.js";
import { InternalServerError$zodSchema, } from "./internalservererror.js";
import { NotFound$zodSchema } from "./notfound.js";
import { SubAgentRelationResponse$zodSchema, } from "./subagentrelationresponse.js";
import { Unauthorized$zodSchema } from "./unauthorized.js";
import { UnprocessableEntity$zodSchema, } from "./unprocessableentity.js";
export const GetSubAgentRelationByIdRequest$zodSchema = z.object({
    agentId: z.string().describe("Agent identifier"),
    id: z.string().describe("Resource identifier"),
    projectId: z.string().describe("Project identifier"),
    tenantId: z.string().describe("Tenant identifier"),
});
export const GetSubAgentRelationByIdResponse$zodSchema = z.object({
    BadRequest: BadRequest$zodSchema.optional(),
    ContentType: z.string(),
    Forbidden: Forbidden$zodSchema.optional(),
    InternalServerError: InternalServerError$zodSchema.optional(),
    NotFound: NotFound$zodSchema.optional(),
    RawResponse: z.instanceof(Response),
    StatusCode: z.number().int(),
    SubAgentRelationResponse: SubAgentRelationResponse$zodSchema.optional(),
    Unauthorized: Unauthorized$zodSchema.optional(),
    UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
//# sourceMappingURL=getsubagentrelationbyidop.js.map