/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { BadRequest$zodSchema } from "./badrequest.js";
import { CredentialStoreListResponse$zodSchema, } from "./credentialstorelistresponse.js";
import { Forbidden$zodSchema } from "./forbidden.js";
import { InternalServerError$zodSchema, } from "./internalservererror.js";
import { NotFound$zodSchema } from "./notfound.js";
import { Unauthorized$zodSchema } from "./unauthorized.js";
import { UnprocessableEntity$zodSchema, } from "./unprocessableentity.js";
export const ListCredentialStoresRequest$zodSchema = z.object({
    projectId: z.string().describe("Project identifier"),
    tenantId: z.string().describe("Tenant identifier"),
});
export const ListCredentialStoresResponse$zodSchema = z.object({
    BadRequest: BadRequest$zodSchema.optional(),
    ContentType: z.string(),
    CredentialStoreListResponse: CredentialStoreListResponse$zodSchema.optional(),
    Forbidden: Forbidden$zodSchema.optional(),
    InternalServerError: InternalServerError$zodSchema.optional(),
    NotFound: NotFound$zodSchema.optional(),
    RawResponse: z.instanceof(Response),
    StatusCode: z.number().int(),
    Unauthorized: Unauthorized$zodSchema.optional(),
    UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
//# sourceMappingURL=listcredentialstoresop.js.map