/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden$zodSchema } from "./forbidden.js";
import { InternalServerError$zodSchema, } from "./internalservererror.js";
import { NotFound$zodSchema } from "./notfound.js";
import { SubAgentListResponse$zodSchema, } from "./subagentlistresponse.js";
import { Unauthorized$zodSchema } from "./unauthorized.js";
import { UnprocessableEntity$zodSchema, } from "./unprocessableentity.js";
export const ListSubagentsRequest$zodSchema = z.object({
    agentId: z.string().describe("Agent identifier"),
    limit: z.number().default(10),
    page: z.number().default(1),
    projectId: z.string().describe("Project identifier"),
    tenantId: z.string().describe("Tenant identifier"),
});
export const ListSubagentsResponse$zodSchema = z.object({
    BadRequest: BadRequest$zodSchema.optional(),
    ContentType: z.string(),
    Forbidden: Forbidden$zodSchema.optional(),
    InternalServerError: InternalServerError$zodSchema.optional(),
    NotFound: NotFound$zodSchema.optional(),
    RawResponse: z.instanceof(Response),
    StatusCode: z.number().int(),
    SubAgentListResponse: SubAgentListResponse$zodSchema.optional(),
    Unauthorized: Unauthorized$zodSchema.optional(),
    UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
//# sourceMappingURL=listsubagentsop.js.map