/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const ModelSettings$zodSchema = z.object({
    model: z.string().optional(),
    providerOptions: z.record(z.any().nullable()).optional(),
});
//# sourceMappingURL=modelsettings.js.map