/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { Pagination$zodSchema } from "./pagination.js";
import { RelatedAgentInfo$zodSchema, } from "./relatedagentinfo.js";
export const RelatedAgentInfoListResponse$zodSchema = z.object({
    data: z.array(RelatedAgentInfo$zodSchema),
    pagination: Pagination$zodSchema,
});
//# sourceMappingURL=relatedagentinfolistresponse.js.map