/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const RemovedResponse$zodSchema = z.object({
    message: z.string(),
    removed: z.boolean(),
});
//# sourceMappingURL=removedresponse.js.map