/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { Model$zodSchema } from "./model.js";
export const SubAgentCreate$zodSchema = z.object({
    conversationHistoryConfig: z.any().nullable().optional(),
    createdAt: z.string().optional(),
    description: z.string(),
    id: z.string(),
    models: Model$zodSchema.optional(),
    name: z.string(),
    prompt: z.string(),
    stopWhen: z.any().nullable().optional(),
    updatedAt: z.string().optional(),
});
//# sourceMappingURL=subagentcreate.js.map