/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const SubAgentTeamAgentRelation$zodSchema = z.object({
    createdAt: z.string(),
    headers: z.any().nullable().optional(),
    id: z.string(),
    subAgentId: z.string(),
    targetAgentId: z.string(),
    updatedAt: z.string(),
});
//# sourceMappingURL=subagentteamagentrelation.js.map