/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
/**
 * A short code indicating the error code returned.
 */
export const UnauthorizedCode1$zodSchema = z.enum([
    "unauthorized",
]).describe("A short code indicating the error code returned.");
/**
 * A short code indicating the error code returned.
 */
export const UnauthorizedCode2$zodSchema = z.enum([
    "unauthorized",
]).describe("A short code indicating the error code returned.");
export const UnauthorizedError$zodSchema = z.object({
    code: UnauthorizedCode2$zodSchema,
    message: z.string(),
}).describe("Legacy error format for backward compatibility.");
export const Unauthorized$zodSchema = z.object({
    code: UnauthorizedCode1$zodSchema,
    detail: z.string(),
    error: z.lazy(() => UnauthorizedError$zodSchema),
    instance: z.string().optional(),
    requestId: z.string().optional(),
    status: z.number().int(),
    title: z.string(),
});
//# sourceMappingURL=unauthorized.js.map