/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden$zodSchema } from "./forbidden.js";
import { FunctionToolResponse$zodSchema, } from "./functiontoolresponse.js";
import { FunctionToolUpdate$zodSchema, } from "./functiontoolupdate.js";
import { InternalServerError$zodSchema, } from "./internalservererror.js";
import { NotFound$zodSchema } from "./notfound.js";
import { Unauthorized$zodSchema } from "./unauthorized.js";
import { UnprocessableEntity$zodSchema, } from "./unprocessableentity.js";
export const UpdateFunctionToolRequest$zodSchema = z.object({
    agentId: z.string().describe("Agent identifier"),
    body: FunctionToolUpdate$zodSchema.optional(),
    id: z.string().describe("Resource identifier"),
    projectId: z.string().describe("Project identifier"),
    tenantId: z.string().describe("Tenant identifier"),
});
export const UpdateFunctionToolResponse$zodSchema = z.object({
    BadRequest: BadRequest$zodSchema.optional(),
    ContentType: z.string(),
    Forbidden: Forbidden$zodSchema.optional(),
    FunctionToolResponse: FunctionToolResponse$zodSchema.optional(),
    InternalServerError: InternalServerError$zodSchema.optional(),
    NotFound: NotFound$zodSchema.optional(),
    RawResponse: z.instanceof(Response),
    StatusCode: z.number().int(),
    Unauthorized: Unauthorized$zodSchema.optional(),
    UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
//# sourceMappingURL=updatefunctiontoolop.js.map