/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 15dd3124a32c
 */

import * as z from "zod";
import { Agent, Agent$zodSchema } from "./agent.js";
import { Pagination, Pagination$zodSchema } from "./pagination.js";

export type AgentListResponse = { data: Array<Agent>; pagination: Pagination };

export const AgentListResponse$zodSchema: z.ZodType<AgentListResponse> = z
  .object({
    data: z.array(Agent$zodSchema),
    pagination: Pagination$zodSchema,
  });
