/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';

export type Agent = {
  id: string;
  name: string;
  description: string | null;
  defaultSubAgentId: string | null;
  contextConfigId: string | null;
  models?: any | null | undefined;
  statusUpdates?: any | null | undefined;
  prompt: string | null;
  stopWhen?: any | null | undefined;
  createdAt: string;
  updatedAt: string;
};

export const Agent$zodSchema: z.ZodType<Agent, z.ZodTypeDef, unknown> = z.object({
  contextConfigId: z.string().nullable(),
  createdAt: z.string(),
  defaultSubAgentId: z.string().nullable(),
  description: z.string().nullable(),
  id: z.string(),
  models: z.any().nullable().optional(),
  name: z.string(),
  prompt: z.string().nullable(),
  statusUpdates: z.any().nullable().optional(),
  stopWhen: z.any().nullable().optional(),
  updatedAt: z.string(),
});
