/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';

export type ApiKeyUpdate = {
  agentId?: string | undefined;
  name?: string | null | undefined;
  lastUsedAt?: string | null | undefined;
  expiresAt?: string | null | undefined;
  updatedAt?: string | undefined;
};

export const ApiKeyUpdate$zodSchema: z.ZodType<ApiKeyUpdate, z.ZodTypeDef, unknown> = z.object({
  agentId: z.string().optional(),
  expiresAt: z.string().nullable().optional(),
  lastUsedAt: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
  updatedAt: z.string().optional(),
});
