/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';

export type ApiKey = {
  id: string;
  agentId: string;
  publicId: string;
  keyPrefix: string;
  name: string | null;
  lastUsedAt: string | null;
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string;
};

export const ApiKey$zodSchema: z.ZodType<ApiKey, z.ZodTypeDef, unknown> = z.object({
  agentId: z.string(),
  createdAt: z.string(),
  expiresAt: z.string().nullable(),
  id: z.string(),
  keyPrefix: z.string(),
  lastUsedAt: z.string().nullable(),
  name: z.string().nullable(),
  publicId: z.string(),
  updatedAt: z.string(),
});
