/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ArtifactComponent,
  ArtifactComponent$zodSchema,
} from "./artifactcomponent.js";

export type ArtifactComponentArrayResponse = { data: Array<ArtifactComponent> };

export const ArtifactComponentArrayResponse$zodSchema: z.ZodType<
  ArtifactComponentArrayResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(ArtifactComponent$zodSchema),
});
