/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';

/**
 * A short code indicating the error code returned.
 */
export const BadRequestCode1$zodSchema = z
  .enum(['bad_request'])
  .describe('A short code indicating the error code returned.');

export type BadRequestCode1 = z.infer<typeof BadRequestCode1$zodSchema>;

/**
 * A short code indicating the error code returned.
 */
export const BadRequestCode2$zodSchema = z
  .enum(['bad_request'])
  .describe('A short code indicating the error code returned.');

export type BadRequestCode2 = z.infer<typeof BadRequestCode2$zodSchema>;

/**
 * Legacy error format for backward compatibility.
 */
export type BadRequestError = { code: BadRequestCode2; message: string };

export const BadRequestError$zodSchema: z.ZodType<BadRequestError, z.ZodTypeDef, unknown> = z
  .object({
    code: BadRequestCode2$zodSchema,
    message: z.string(),
  })
  .describe('Legacy error format for backward compatibility.');

export type BadRequest = {
  title: string;
  status: number;
  detail: string;
  instance?: string | undefined;
  requestId?: string | undefined;
  code: BadRequestCode1;
  error: BadRequestError;
};

export const BadRequest$zodSchema: z.ZodType<BadRequest, z.ZodTypeDef, unknown> = z.object({
  code: BadRequestCode1$zodSchema,
  detail: z.string(),
  error: z.lazy(() => BadRequestError$zodSchema),
  instance: z.string().optional(),
  requestId: z.string().optional(),
  status: z.number().int(),
  title: z.string(),
});
