/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9e21d07f35c6
 */

import * as z from "zod";

export type ComponentAssociation = { subAgentId: string; createdAt: string };

export const ComponentAssociation$zodSchema: z.ZodType<ComponentAssociation> = z
  .object({
    createdAt: z.string(),
    subAgentId: z.string(),
  });
