/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import { BadRequest, BadRequest$zodSchema } from './badrequest.js';
import { Forbidden, Forbidden$zodSchema } from './forbidden.js';
import { InternalServerError, InternalServerError$zodSchema } from './internalservererror.js';
import { NotFound, NotFound$zodSchema } from './notfound.js';
import {
  SubAgentRelationCreate,
  SubAgentRelationCreate$zodSchema,
} from './subagentrelationcreate.js';
import {
  SubAgentRelationResponse,
  SubAgentRelationResponse$zodSchema,
} from './subagentrelationresponse.js';
import { Unauthorized, Unauthorized$zodSchema } from './unauthorized.js';
import { UnprocessableEntity, UnprocessableEntity$zodSchema } from './unprocessableentity.js';

export type CreateSubAgentRelationRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
  body?: SubAgentRelationCreate | undefined;
};

export const CreateSubAgentRelationRequest$zodSchema: z.ZodType<
  CreateSubAgentRelationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  agentId: z.string().describe('Agent identifier'),
  body: SubAgentRelationCreate$zodSchema.optional(),
  projectId: z.string().describe('Project identifier'),
  tenantId: z.string().describe('Tenant identifier'),
});

export type CreateSubAgentRelationResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  SubAgentRelationResponse?: SubAgentRelationResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const CreateSubAgentRelationResponse$zodSchema: z.ZodType<
  CreateSubAgentRelationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  SubAgentRelationResponse: SubAgentRelationResponse$zodSchema.optional(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
