/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import { type BadRequest, BadRequest$zodSchema } from './badrequest.js';
import { type Forbidden, Forbidden$zodSchema } from './forbidden.js';
import { type InternalServerError, InternalServerError$zodSchema } from './internalservererror.js';
import { type NotFound, NotFound$zodSchema } from './notfound.js';
import {
  type SubAgentTeamAgentRelationCreate,
  SubAgentTeamAgentRelationCreate$zodSchema,
} from './subagentteamagentrelationcreate.js';
import {
  type SubAgentTeamAgentRelationResponse,
  SubAgentTeamAgentRelationResponse$zodSchema,
} from './subagentteamagentrelationresponse.js';
import { type Unauthorized, Unauthorized$zodSchema } from './unauthorized.js';
import { type UnprocessableEntity, UnprocessableEntity$zodSchema } from './unprocessableentity.js';

export type CreateSubAgentTeamAgentRelationRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
  subAgentId: string;
  body?: SubAgentTeamAgentRelationCreate | undefined;
};

export const CreateSubAgentTeamAgentRelationRequest$zodSchema: z.ZodType<
  CreateSubAgentTeamAgentRelationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  agentId: z.string().describe('Agent identifier'),
  body: SubAgentTeamAgentRelationCreate$zodSchema.optional(),
  projectId: z.string().describe('Project identifier'),
  subAgentId: z.string().describe('Sub-agent identifier'),
  tenantId: z.string().describe('Tenant identifier'),
});

export type CreateSubAgentTeamAgentRelationResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  SubAgentTeamAgentRelationResponse?: SubAgentTeamAgentRelationResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const CreateSubAgentTeamAgentRelationResponse$zodSchema: z.ZodType<
  CreateSubAgentTeamAgentRelationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  SubAgentTeamAgentRelationResponse: SubAgentTeamAgentRelationResponse$zodSchema.optional(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
