/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import { type BadRequest, BadRequest$zodSchema } from './badrequest.js';
import { type Forbidden, Forbidden$zodSchema } from './forbidden.js';
import { type FunctionToolCreate, FunctionToolCreate$zodSchema } from './functiontoolcreate.js';
import {
  type FunctionToolResponse,
  FunctionToolResponse$zodSchema,
} from './functiontoolresponse.js';
import { type InternalServerError, InternalServerError$zodSchema } from './internalservererror.js';
import { type NotFound, NotFound$zodSchema } from './notfound.js';
import { type Unauthorized, Unauthorized$zodSchema } from './unauthorized.js';
import { type UnprocessableEntity, UnprocessableEntity$zodSchema } from './unprocessableentity.js';

export type CreateFunctionToolRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
  body?: FunctionToolCreate | undefined;
};

export const CreateFunctionToolRequest$zodSchema: z.ZodType<
  CreateFunctionToolRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  agentId: z.string().describe('Agent identifier'),
  body: FunctionToolCreate$zodSchema.optional(),
  projectId: z.string().describe('Project identifier'),
  tenantId: z.string().describe('Tenant identifier'),
});

export type CreateFunctionToolResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  FunctionToolResponse?: FunctionToolResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const CreateFunctionToolResponse$zodSchema: z.ZodType<
  CreateFunctionToolResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  FunctionToolResponse: FunctionToolResponse$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
