/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';

export const CredentialReferenceType$zodSchema = z.enum(['memory', 'keychain', 'nango']);

export type CredentialReferenceType = z.infer<typeof CredentialReferenceType$zodSchema>;

export type Tool = {
  tenantId: string;
  id: string;
  projectId: string;
  name: string;
  description: string | null;
  config?: any | null | undefined;
  credentialReferenceId: string | null;
  headers?: any | null | undefined;
  imageUrl: string | null;
  capabilities?: any | null | undefined;
  lastError: string | null;
  createdAt: string;
  updatedAt: string;
};

export const Tool$zodSchema: z.ZodType<Tool, z.ZodTypeDef, unknown> = z.object({
  capabilities: z.any().nullable().optional(),
  config: z.any().nullable().optional(),
  createdAt: z.string(),
  credentialReferenceId: z.string().nullable(),
  description: z.string().nullable(),
  headers: z.any().nullable().optional(),
  id: z.string(),
  imageUrl: z.string().nullable(),
  lastError: z.string().nullable(),
  name: z.string(),
  projectId: z.string(),
  tenantId: z.string(),
  updatedAt: z.string(),
});

export type CredentialReferenceExternalAgent = {
  tenantId: string;
  id: string;
  projectId: string;
  name: string;
  description: string;
  baseUrl: string;
  credentialReferenceId?: string | null | undefined;
  createdAt: string;
  updatedAt: string;
};

export const CredentialReferenceExternalAgent$zodSchema: z.ZodType<
  CredentialReferenceExternalAgent,
  z.ZodTypeDef,
  unknown
> = z.object({
  baseUrl: z.string(),
  createdAt: z.string(),
  credentialReferenceId: z.string().nullable().optional(),
  description: z.string(),
  id: z.string(),
  name: z.string(),
  projectId: z.string(),
  tenantId: z.string(),
  updatedAt: z.string(),
});

export type CredentialReference = {
  id: string;
  name: string;
  type: CredentialReferenceType;
  credentialStoreId: string;
  retrievalParams?: { [k: string]: any | null } | null | undefined;
  createdAt: string;
  updatedAt: string;
  tools?: Array<Tool> | undefined;
  externalAgents?: Array<CredentialReferenceExternalAgent> | undefined;
};

export const CredentialReference$zodSchema: z.ZodType<CredentialReference, z.ZodTypeDef, unknown> =
  z.object({
    createdAt: z.string(),
    credentialStoreId: z.string(),
    externalAgents: z.array(z.lazy(() => CredentialReferenceExternalAgent$zodSchema)).optional(),
    id: z.string(),
    name: z.string(),
    retrievalParams: z.record(z.any().nullable()).nullable().optional(),
    tools: z.array(z.lazy(() => Tool$zodSchema)).optional(),
    type: CredentialReferenceType$zodSchema,
    updatedAt: z.string(),
  });
