/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0bb97540d40e
 */

import * as z from "zod";
import {
  CredentialReference,
  CredentialReference$zodSchema,
} from "./credentialreference.js";

export type CredentialReferenceResponse = { data: CredentialReference };

export const CredentialReferenceResponse$zodSchema: z.ZodType<
  CredentialReferenceResponse
> = z.object({
  data: CredentialReference$zodSchema,
});
