/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DataComponentUpdate = {
  id?: string | undefined;
  name?: string | undefined;
  description?: string | null | undefined;
  props?: any | null | undefined;
  render?: any | null | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
};

export const DataComponentUpdate$zodSchema: z.ZodType<DataComponentUpdate> = z
  .object({
    createdAt: z.string().optional(),
    description: z.string().nullable().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
    props: z.any().nullable().optional(),
    render: z.any().nullable().optional(),
    updatedAt: z.string().optional(),
  });
