/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';

export type ErrorResponse = {
  error: string;
  message?: string | undefined;
  details?: any | null | undefined;
};

export const ErrorResponse$zodSchema: z.ZodType<ErrorResponse, z.ZodTypeDef, unknown> = z.object({
  details: z.any().nullable().optional(),
  error: z.string(),
  message: z.string().optional(),
});
