/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a8385d42318b
 */

import * as z from "zod";
import { ExternalAgent, ExternalAgent$zodSchema } from "./externalagent.js";

export type ExternalAgentResponse = { data: ExternalAgent };

export const ExternalAgentResponse$zodSchema: z.ZodType<ExternalAgentResponse> =
  z.object({
    data: ExternalAgent$zodSchema,
  });
