/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import { BadRequest, BadRequest$zodSchema } from './badrequest.js';
import { Forbidden, Forbidden$zodSchema } from './forbidden.js';
import { InternalServerError, InternalServerError$zodSchema } from './internalservererror.js';
import { NotFound, NotFound$zodSchema } from './notfound.js';
import { Unauthorized, Unauthorized$zodSchema } from './unauthorized.js';
import { UnprocessableEntity, UnprocessableEntity$zodSchema } from './unprocessableentity.js';

export type GenerateDataComponentRenderSyncRequestBody = {
  instructions?: string | undefined;
  existingCode?: string | undefined;
};

export const GenerateDataComponentRenderSyncRequestBody$zodSchema: z.ZodType<
  GenerateDataComponentRenderSyncRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  existingCode: z.string().optional(),
  instructions: z.string().optional(),
});

export type GenerateDataComponentRenderSyncRequest = {
  tenantId: string;
  projectId: string;
  id: string;
  body?: GenerateDataComponentRenderSyncRequestBody | undefined;
};

export const GenerateDataComponentRenderSyncRequest$zodSchema: z.ZodType<
  GenerateDataComponentRenderSyncRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  body: z.lazy(() => GenerateDataComponentRenderSyncRequestBody$zodSchema).optional(),
  id: z.string().describe('Resource identifier'),
  projectId: z.string().describe('Project identifier'),
  tenantId: z.string().describe('Tenant identifier'),
});

/**
 * Component render generated successfully
 */
export type GenerateDataComponentRenderSyncResponseBody = {
  component: string;
  mockData?: any | null | undefined;
};

export const GenerateDataComponentRenderSyncResponseBody$zodSchema: z.ZodType<
  GenerateDataComponentRenderSyncResponseBody,
  z.ZodTypeDef,
  unknown
> = z
  .object({
    component: z.string(),
    mockData: z.any().nullable().optional(),
  })
  .describe('Component render generated successfully');

export type GenerateDataComponentRenderSyncResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: GenerateDataComponentRenderSyncResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const GenerateDataComponentRenderSyncResponse$zodSchema: z.ZodType<
  GenerateDataComponentRenderSyncResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
  object: z.lazy(() => GenerateDataComponentRenderSyncResponseBody$zodSchema).optional(),
});
