/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import {
  ArtifactComponentResponse,
  ArtifactComponentResponse$zodSchema,
} from './artifactcomponentresponse.js';
import { BadRequest, BadRequest$zodSchema } from './badrequest.js';
import { Forbidden, Forbidden$zodSchema } from './forbidden.js';
import { InternalServerError, InternalServerError$zodSchema } from './internalservererror.js';
import { NotFound, NotFound$zodSchema } from './notfound.js';
import { Unauthorized, Unauthorized$zodSchema } from './unauthorized.js';
import { UnprocessableEntity, UnprocessableEntity$zodSchema } from './unprocessableentity.js';

export type GetArtifactComponentByIdRequest = {
  tenantId: string;
  projectId: string;
  id: string;
};

export const GetArtifactComponentByIdRequest$zodSchema: z.ZodType<
  GetArtifactComponentByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().describe('Resource identifier'),
  projectId: z.string().describe('Project identifier'),
  tenantId: z.string().describe('Tenant identifier'),
});

export type GetArtifactComponentByIdResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ArtifactComponentResponse?: ArtifactComponentResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const GetArtifactComponentByIdResponse$zodSchema: z.ZodType<
  GetArtifactComponentByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ArtifactComponentResponse: ArtifactComponentResponse$zodSchema.optional(),
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
