/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';

/**
 * A short code indicating the error code returned.
 */
export const InternalServerErrorCode1$zodSchema = z
  .enum(['internal_server_error'])
  .describe('A short code indicating the error code returned.');

export type InternalServerErrorCode1 = z.infer<typeof InternalServerErrorCode1$zodSchema>;

/**
 * A short code indicating the error code returned.
 */
export const InternalServerErrorCode2$zodSchema = z
  .enum(['internal_server_error'])
  .describe('A short code indicating the error code returned.');

export type InternalServerErrorCode2 = z.infer<typeof InternalServerErrorCode2$zodSchema>;

/**
 * Legacy error format for backward compatibility.
 */
export type InternalServerErrorError = {
  code: InternalServerErrorCode2;
  message: string;
};

export const InternalServerErrorError$zodSchema: z.ZodType<
  InternalServerErrorError,
  z.ZodTypeDef,
  unknown
> = z
  .object({
    code: InternalServerErrorCode2$zodSchema,
    message: z.string(),
  })
  .describe('Legacy error format for backward compatibility.');

export type InternalServerError = {
  title: string;
  status: number;
  detail: string;
  instance?: string | undefined;
  requestId?: string | undefined;
  code: InternalServerErrorCode1;
  error: InternalServerErrorError;
};

export const InternalServerError$zodSchema: z.ZodType<InternalServerError, z.ZodTypeDef, unknown> =
  z.object({
    code: InternalServerErrorCode1$zodSchema,
    detail: z.string(),
    error: z.lazy(() => InternalServerErrorError$zodSchema),
    instance: z.string().optional(),
    requestId: z.string().optional(),
    status: z.number().int(),
    title: z.string(),
  });
