/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import { type BadRequest, BadRequest$zodSchema } from './badrequest.js';
import { type Forbidden, Forbidden$zodSchema } from './forbidden.js';
import { type InternalServerError, InternalServerError$zodSchema } from './internalservererror.js';
import { type NotFound, NotFound$zodSchema } from './notfound.js';
import {
  type SubAgentToolRelationListResponse,
  SubAgentToolRelationListResponse$zodSchema,
} from './subagenttoolrelationlistresponse.js';
import { type Unauthorized, Unauthorized$zodSchema } from './unauthorized.js';
import { type UnprocessableEntity, UnprocessableEntity$zodSchema } from './unprocessableentity.js';

export type ListSubagentToolRelationsRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
  page?: number | undefined;
  limit?: number | undefined;
  subAgentId?: string | undefined;
  toolId?: string | undefined;
};

export const ListSubagentToolRelationsRequest$zodSchema: z.ZodType<
  ListSubagentToolRelationsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  agentId: z.string().describe('Agent identifier'),
  limit: z.number().default(10),
  page: z.number().default(1),
  projectId: z.string().describe('Project identifier'),
  subAgentId: z.string().optional(),
  tenantId: z.string().describe('Tenant identifier'),
  toolId: z.string().optional(),
});

export type ListSubagentToolRelationsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  SubAgentToolRelationListResponse?: SubAgentToolRelationListResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const ListSubagentToolRelationsResponse$zodSchema: z.ZodType<
  ListSubagentToolRelationsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  SubAgentToolRelationListResponse: SubAgentToolRelationListResponse$zodSchema.optional(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
