/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import { type BadRequest, BadRequest$zodSchema } from './badrequest.js';
import {
  type CredentialStoreListResponse,
  CredentialStoreListResponse$zodSchema,
} from './credentialstorelistresponse.js';
import { type Forbidden, Forbidden$zodSchema } from './forbidden.js';
import { type InternalServerError, InternalServerError$zodSchema } from './internalservererror.js';
import { type NotFound, NotFound$zodSchema } from './notfound.js';
import { type Unauthorized, Unauthorized$zodSchema } from './unauthorized.js';
import { type UnprocessableEntity, UnprocessableEntity$zodSchema } from './unprocessableentity.js';

export type ListCredentialStoresRequest = {
  tenantId: string;
  projectId: string;
};

export const ListCredentialStoresRequest$zodSchema: z.ZodType<
  ListCredentialStoresRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectId: z.string().describe('Project identifier'),
  tenantId: z.string().describe('Tenant identifier'),
});

export type ListCredentialStoresResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  CredentialStoreListResponse?: CredentialStoreListResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const ListCredentialStoresResponse$zodSchema: z.ZodType<
  ListCredentialStoresResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  CredentialStoreListResponse: CredentialStoreListResponse$zodSchema.optional(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
