/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import { BadRequest, BadRequest$zodSchema } from './badrequest.js';
import {
  DataComponentListResponse,
  DataComponentListResponse$zodSchema,
} from './datacomponentlistresponse.js';
import { Forbidden, Forbidden$zodSchema } from './forbidden.js';
import { InternalServerError, InternalServerError$zodSchema } from './internalservererror.js';
import { NotFound, NotFound$zodSchema } from './notfound.js';
import { Unauthorized, Unauthorized$zodSchema } from './unauthorized.js';
import { UnprocessableEntity, UnprocessableEntity$zodSchema } from './unprocessableentity.js';

export type ListDataComponentsRequest = {
  tenantId: string;
  projectId: string;
  page?: number | undefined;
  limit?: number | undefined;
};

export const ListDataComponentsRequest$zodSchema: z.ZodType<
  ListDataComponentsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  limit: z.number().default(10),
  page: z.number().default(1),
  projectId: z.string().describe('Project identifier'),
  tenantId: z.string().describe('Tenant identifier'),
});

export type ListDataComponentsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  DataComponentListResponse?: DataComponentListResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const ListDataComponentsResponse$zodSchema: z.ZodType<
  ListDataComponentsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  DataComponentListResponse: DataComponentListResponse$zodSchema.optional(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
