/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0497a77c4731
 */

import * as z from "zod";
import { McpTool, McpTool$zodSchema } from "./mcptool.js";
import { Pagination, Pagination$zodSchema } from "./pagination.js";

export type McpToolListResponse = {
  data: Array<McpTool>;
  pagination: Pagination;
};

export const McpToolListResponse$zodSchema: z.ZodType<McpToolListResponse> = z
  .object({
    data: z.array(McpTool$zodSchema),
    pagination: Pagination$zodSchema,
  });
