/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import { BadRequest, BadRequest$zodSchema } from './badrequest.js';
import { Forbidden, Forbidden$zodSchema } from './forbidden.js';
import { InternalServerError, InternalServerError$zodSchema } from './internalservererror.js';
import { NotFound, NotFound$zodSchema } from './notfound.js';
import { RemovedResponse, RemovedResponse$zodSchema } from './removedresponse.js';
import { Unauthorized, Unauthorized$zodSchema } from './unauthorized.js';
import { UnprocessableEntity, UnprocessableEntity$zodSchema } from './unprocessableentity.js';

export type RemoveArtifactComponentFromAgentRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
  subAgentId: string;
  artifactComponentId: string;
};

export const RemoveArtifactComponentFromAgentRequest$zodSchema: z.ZodType<
  RemoveArtifactComponentFromAgentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  agentId: z.string().describe('Agent identifier'),
  artifactComponentId: z.string(),
  projectId: z.string().describe('Project identifier'),
  subAgentId: z.string().describe('Sub-agent identifier'),
  tenantId: z.string().describe('Tenant identifier'),
});

export type RemoveArtifactComponentFromAgentResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  RemovedResponse?: RemovedResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const RemoveArtifactComponentFromAgentResponse$zodSchema: z.ZodType<
  RemoveArtifactComponentFromAgentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  RemovedResponse: RemovedResponse$zodSchema.optional(),
  StatusCode: z.number().int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
