/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const SubAgentRelationUpdateRelationType = {
  Transfer: "transfer",
  Delegate: "delegate",
} as const;
export type SubAgentRelationUpdateRelationType = ClosedEnum<
  typeof SubAgentRelationUpdateRelationType
>;

export const SubAgentRelationUpdateRelationType$zodSchema = z.enum([
  "transfer",
  "delegate",
]);

export type SubAgentRelationUpdate = {
  id?: string | undefined;
  sourceSubAgentId?: string | undefined;
  targetSubAgentId?: string | undefined;
  relationType?: SubAgentRelationUpdateRelationType | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  externalSubAgentId?: string | undefined;
  teamSubAgentId?: string | undefined;
};

export const SubAgentRelationUpdate$zodSchema: z.ZodType<
  SubAgentRelationUpdate
> = z.object({
  createdAt: z.string().optional(),
  externalSubAgentId: z.string().optional(),
  id: z.string().optional(),
  relationType: SubAgentRelationUpdateRelationType$zodSchema.optional(),
  sourceSubAgentId: z.string().optional(),
  targetSubAgentId: z.string().optional(),
  teamSubAgentId: z.string().optional(),
  updatedAt: z.string().optional(),
});
