/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';

export type SubAgentDataComponentResponseData = {
  id: string;
  subAgentId: string;
  dataComponentId: string;
  createdAt: string;
};

export const SubAgentDataComponentResponseData$zodSchema: z.ZodType<
  SubAgentDataComponentResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  dataComponentId: z.string(),
  id: z.string(),
  subAgentId: z.string(),
});

export type SubAgentDataComponentResponse = {
  data: SubAgentDataComponentResponseData;
};

export const SubAgentDataComponentResponse$zodSchema: z.ZodType<
  SubAgentDataComponentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => SubAgentDataComponentResponseData$zodSchema),
});
