/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import { type Pagination, Pagination$zodSchema } from './pagination.js';
import { type SubAgent, SubAgent$zodSchema } from './subagent.js';

export type SubAgentListResponse = {
  data: Array<SubAgent>;
  pagination: Pagination;
};

export const SubAgentListResponse$zodSchema: z.ZodType<
  SubAgentListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(SubAgent$zodSchema),
  pagination: Pagination$zodSchema,
});
