/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import { SubAgent, SubAgent$zodSchema } from './subagent.js';

export type SubAgentResponse = { data: SubAgent };

export const SubAgentResponse$zodSchema: z.ZodType<SubAgentResponse, z.ZodTypeDef, unknown> =
  z.object({
    data: SubAgent$zodSchema,
  });
