/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import { BadRequest, BadRequest$zodSchema } from './badrequest.js';
import { Forbidden, Forbidden$zodSchema } from './forbidden.js';
import { InternalServerError, InternalServerError$zodSchema } from './internalservererror.js';
import { McpToolResponse, McpToolResponse$zodSchema } from './mcptoolresponse.js';
import { NotFound, NotFound$zodSchema } from './notfound.js';
import { ToolUpdate, ToolUpdate$zodSchema } from './toolupdate.js';
import { Unauthorized, Unauthorized$zodSchema } from './unauthorized.js';
import { UnprocessableEntity, UnprocessableEntity$zodSchema } from './unprocessableentity.js';

export type UpdateToolRequest = {
  tenantId: string;
  projectId: string;
  id: string;
  body?: ToolUpdate | undefined;
};

export const UpdateToolRequest$zodSchema: z.ZodType<UpdateToolRequest, z.ZodTypeDef, unknown> =
  z.object({
    body: ToolUpdate$zodSchema.optional(),
    id: z.string().describe('Resource identifier'),
    projectId: z.string().describe('Project identifier'),
    tenantId: z.string().describe('Tenant identifier'),
  });

export type UpdateToolResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  McpToolResponse?: McpToolResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const UpdateToolResponse$zodSchema: z.ZodType<UpdateToolResponse, z.ZodTypeDef, unknown> =
  z.object({
    BadRequest: BadRequest$zodSchema.optional(),
    ContentType: z.string(),
    Forbidden: Forbidden$zodSchema.optional(),
    InternalServerError: InternalServerError$zodSchema.optional(),
    McpToolResponse: McpToolResponse$zodSchema.optional(),
    NotFound: NotFound$zodSchema.optional(),
    RawResponse: z.instanceof(Response),
    StatusCode: z.number().int(),
    Unauthorized: Unauthorized$zodSchema.optional(),
    UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
  });
