workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Inkeep Agents Manage API:
        inputs:
            - location: openapi.json
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/inkeep/inkeep/inkeep-agents-manage-api
targets:
    inkeep-agents:
        target: mcp-typescript
        source: Inkeep Agents Manage API
