/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9e795945f7bf
 */

import { dlv } from "./dlv.js";

import * as z from "zod";

export interface Env {
  INKEEPAGENTSMANAGE_COOKIE_AUTH?: string | undefined;
  INKEEPAGENTSMANAGE_BEARER_AUTH?: string | undefined;

  INKEEPAGENTSMANAGE_DEBUG?: boolean | undefined;
}

export const envSchema: z.ZodType<Env> = z.object({
  INKEEPAGENTSMANAGE_COOKIE_AUTH: z.string().optional(),
  INKEEPAGENTSMANAGE_BEARER_AUTH: z.string().optional(),

  INKEEPAGENTSMANAGE_DEBUG: z.stringbool().optional(),
});

let envMemo: Env | undefined = undefined;
/**
 * Reads and validates environment variables.
 */
export function env(): Env {
  if (envMemo) {
    return envMemo;
  }

  envMemo = envSchema.parse(
    dlv(globalThis, "process.env") ?? dlv(globalThis, "Deno.env") ?? {},
  );
  return envMemo;
}

/**
 * Clears the cached env object. Useful for testing with a fresh environment.
 */
export function resetEnv() {
  envMemo = undefined;
}
