export const demoProject = {
  id: 'demo-project',
  name: 'demo-project',
  description: 'To demo how to build an agent',
  models: {
    base: { model: 'anthropic/claude-sonnet-4-5' },
    summarizer: { model: 'anthropic/claude-sonnet-4-5' },
    structuredOutput: { model: 'anthropic/claude-sonnet-4-5' },
  },
  stopWhen: {},
  agents: {
    'advanced-meeting-prep-agent': {
      id: 'advanced-meeting-prep-agent',
      name: 'Advanced Meeting Prep Agent',
      description: null,
      defaultSubAgentId: null,
      subAgents: {},
      tools: {},
      functionTools: {},
    },
    custodial: {
      id: 'custodial',
      name: 'Custodial',
      description: null,
      defaultSubAgentId: null,
      subAgents: {},
      tools: {},
      functionTools: {},
    },
    'kevin-mira-gong-transcripts': {
      id: 'kevin-mira-gong-transcripts',
      name: 'Kevin Mira - Gong Transcripts',
      description: null,
      defaultSubAgentId: 'inkeepgong',
      subAgents: {
        inkeepgong: {
          id: 'inkeepgong',
          name: 'InkeepGong',
          description:
            'This agent is responsible for reviewing customer calls/transcripts from Gong to create messaging based on customer language - challenges, terms, etc. ',
          prompt: '',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [],
        },
      },
      stopWhen: { transferCountIs: 10 },
      tools: {},
      functionTools: {},
    },
    'ashby-role-descriptions': {
      id: 'ashby-role-descriptions',
      name: 'Ashby-role-descriptions',
      description: null,
      defaultSubAgentId: 'role-description-generator',
      subAgents: {
        'role-description-generator': {
          id: 'role-description-generator',
          name: 'Role Description Generator',
          description:
            'Fetches open roles from Ashby and generates updated role descriptions using Inkeep knowledge base',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: 'vq890ku1bmwop8wz6bnf9',
              toolId: 'c7kdb6dt92nyb80ub2rng',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
      },
      tools: {
        c7kdb6dt92nyb80ub2rng: {
          id: 'c7kdb6dt92nyb80ub2rng',
          name: 'Inkeep Enterprise Search MCP',
          description: null,
          config: {
            mcp: {
              server: { url: 'https://test.com' },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
      },
      functionTools: {},
    },
    'customer-support': {
      id: 'customer-support',
      name: 'Customer Support',
      description:
        'Comprehensive customer support system with knowledge base and Zendesk integration',
      defaultSubAgentId: 'customer-support-coordinator',
      subAgents: {
        'customer-support-coordinator': {
          id: 'customer-support-coordinator',
          name: 'Customer Support Coordinator',
          description: 'Coordinates between knowledge base and Zendesk support',
          prompt: 'test',
          models: { base: { model: 'openai/gpt-5.2' } },
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: ['knowledge-base-agent', 'zendesk-support-agent'],
          skills: [],
          dataComponents: ['zendeskticketcard'],
          artifactComponents: [],
          canUse: [],
        },
        'knowledge-base-agent': {
          id: 'knowledge-base-agent',
          name: 'Knowledge Base Agent',
          description: 'Answers questions using the internal knowledge base',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: '78hfc4m1891z270qtdaye',
              toolId: 'c7kdb6dt92nyb80ub2rng',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
        'zendesk-support-agent': {
          id: 'zendesk-support-agent',
          name: 'Zendesk Support Agent',
          description: 'Handles customer support inquiries using Zendesk',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: '08rw7pfv33irvimi1oc2k',
              toolId: 'rjziaq0tono242cg91cvx',
              toolSelection: ['create_zendesk_ticket'],
              toolPolicies: {},
            },
            {
              agentToolRelationId: 'cab9sam632xyiy2zdw3rt',
              toolId: 'svclt7yv8fg0dgtku6wm2',
              toolSelection: ['notion-update-page'],
              headers: null,
              toolPolicies: {},
            },
          ],
        },
      },
      models: { base: { model: 'openai/gpt-5.2' } },
      statusUpdates: { numEvents: 10, timeInSeconds: 30 },
      stopWhen: { transferCountIs: 10 },
      tools: {
        svclt7yv8fg0dgtku6wm2: {
          id: 'svclt7yv8fg0dgtku6wm2',
          name: 'Notion',
          description: null,
          config: {
            mcp: {
              server: { url: 'https://test.com' },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
        rjziaq0tono242cg91cvx: {
          id: 'rjziaq0tono242cg91cvx',
          name: 'Zendesk',
          description: null,
          config: {
            mcp: {
              server: { url: 'https://test.com' },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
        c7kdb6dt92nyb80ub2rng: {
          id: 'c7kdb6dt92nyb80ub2rng',
          name: 'Inkeep Enterprise Search MCP',
          description: null,
          config: {
            mcp: {
              server: { url: 'https://test.com' },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
      },
      functionTools: {},
    },
    'data-analyst': {
      id: 'data-analyst',
      name: 'Data analyst',
      description: null,
      defaultSubAgentId: 'data-analyst',
      subAgents: {
        'data-analyst': {
          id: 'data-analyst',
          name: 'Data analyst',
          description: '',
          prompt: 'test',
          models: { base: { model: 'openai/gpt-5' } },
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: ['scatterplot', 'bar-chart-of-happiness-scores'],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: 'gt4inccv91xepjlozg5qy',
              toolId: 'wtftp4mk9hk7c1zd5rdi3',
              toolSelection: ['execute_sql'],
              headers: null,
              toolPolicies: {},
            },
          ],
        },
      },
      stopWhen: { transferCountIs: 10 },
      tools: {
        wtftp4mk9hk7c1zd5rdi3: {
          id: 'wtftp4mk9hk7c1zd5rdi3',
          name: 'Supabase (Gaurav Varma)',
          description: null,
          config: {
            mcp: {
              server: { url: 'https://test.com' },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: 'l3e51vzt5atfwymmu4ur5',
          imageUrl: 'https://test.png',
        },
      },
      functionTools: {},
    },
    'knowledge-agent': {
      id: 'knowledge-agent',
      name: 'Knowledge agent',
      description: null,
      defaultSubAgentId: 'knowledge-search-agent',
      subAgents: {
        'knowledge-search-agent': {
          id: 'knowledge-search-agent',
          name: 'Knowledge Search Agent',
          description: 'Searches the knowledge base and provides answers to user questions',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: ['web-search-agent'],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: 'acwjzxg2iacobkwjnt6o7',
              toolId: 'c7kdb6dt92nyb80ub2rng',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
        'web-search-agent': {
          id: 'web-search-agent',
          name: 'Web search agent',
          description: 'Responsible for searching the web',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: 'ausq8a0nyyyg5r14b8hzg',
              toolId: 'tdrfknro54h4b0lwklhig',
              toolSelection: ['basic-search'],
              headers: null,
              toolPolicies: {},
            },
          ],
        },
      },
      stopWhen: { transferCountIs: 10 },
      tools: {
        c7kdb6dt92nyb80ub2rng: {
          id: 'c7kdb6dt92nyb80ub2rng',
          name: 'Inkeep Enterprise Search MCP',
          description: null,
          config: {
            mcp: {
              server: { url: 'https://test.com' },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
        tdrfknro54h4b0lwklhig: {
          id: 'tdrfknro54h4b0lwklhig',
          name: 'Web search tool',
          description: null,
          config: {
            mcp: {
              server: { url: 'https://test.com' },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
      },
      functionTools: {},
    },
    'matt-meeting-prep-agent': {
      id: 'matt-meeting-prep-agent',
      name: 'Matt - Meeting Prep Agent',
      description: null,
      defaultSubAgentId: 'meeting-prep-agent',
      subAgents: {
        'meeting-prep-agent': {
          id: 'meeting-prep-agent',
          name: 'Meeting Prep Coordinator',
          description:
            'Helps users prepare for meetings by finding them in Google Calendar and conducting relevant research',
          prompt: 'test',
          models: { base: { model: 'openai/gpt-4o' } },
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: '23k0iczq6eoxznb6yxm2p',
              toolId: '6bb1ve7v75qokhqcp7p1r',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
            {
              agentToolRelationId: 'xg116sakzz6joe6eo4ljy',
              toolId: 'tdrfknro54h4b0lwklhig',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
      },
      stopWhen: { transferCountIs: 10 },
      tools: {
        '6bb1ve7v75qokhqcp7p1r': {
          id: '6bb1ve7v75qokhqcp7p1r',
          name: 'Google Calendar MCP',
          description: null,
          config: {
            mcp: {
              server: {
                url: 'https://test.com',
              },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
        tdrfknro54h4b0lwklhig: {
          id: 'tdrfknro54h4b0lwklhig',
          name: 'Web search tool',
          description: null,
          config: {
            mcp: {
              server: { url: 'https://test.com' },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
      },
      functionTools: {},
    },
    'meeting-prep-agent': {
      id: 'meeting-prep-agent',
      name: 'Meeting prep agent',
      description: null,
      defaultSubAgentId: 'meeting-prep-coordinator',
      subAgents: {
        'company-research': {
          id: 'company-research',
          name: 'Company research',
          description: 'Research the company to understand what they do.\n',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: 'f26mbzettj2hpxr9177bi',
              toolId: 'tdrfknro54h4b0lwklhig',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
        'meeting-finder': {
          id: 'meeting-finder',
          name: 'Meeting finder',
          description: 'Find the external meeting to prep for using Google Calendar.\n',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [],
        },
        'meeting-prep-coordinator': {
          id: 'meeting-prep-coordinator',
          name: 'Meeting prep coordinator',
          description: 'Orchestrate specialized agents to prepare for a meeting.\n',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: ['company-research', 'meeting-finder'],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [],
        },
      },
      stopWhen: { transferCountIs: 10 },
      tools: {
        tdrfknro54h4b0lwklhig: {
          id: 'tdrfknro54h4b0lwklhig',
          name: 'Web search tool',
          description: null,
          config: {
            mcp: {
              server: { url: 'https://test.com' },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
      },
      functionTools: {},
    },
    'meeting-prep-agent-gaurav': {
      id: 'meeting-prep-agent-gaurav',
      name: 'meeting-prep-agent-gaurav',
      description: null,
      defaultSubAgentId: 'meeting-coordinator',
      subAgents: {
        'meeting-coordinator': {
          id: 'meeting-coordinator',
          name: 'Meeting Prep Coordinator',
          description:
            'Orchestrates meeting preparation by coordinating calendar search and research tasks',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: ['meeting-finder', 'research-agent'],
          skills: [],
          dataComponents: ['meeting-tips-card'],
          artifactComponents: [],
          canUse: [],
        },
        'meeting-finder': {
          id: 'meeting-finder',
          name: 'Meeting Finder',
          description: 'Searches Google Calendar to find meetings based on user queries',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: 'i7s3inpktrx4a6oowruky',
              toolId: '6bb1ve7v75qokhqcp7p1r',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
        'research-agent': {
          id: 'research-agent',
          name: 'Research Agent',
          description: 'Conducts web research to gather information for meeting preparation',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: 'txc3yxepqz7e67yjhbcrs',
              toolId: 'tdrfknro54h4b0lwklhig',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
      },
      stopWhen: { transferCountIs: 10 },
      tools: {
        '6bb1ve7v75qokhqcp7p1r': {
          id: '6bb1ve7v75qokhqcp7p1r',
          name: 'Google Calendar MCP',
          description: null,
          config: {
            mcp: {
              server: {
                url: 'https://test.com',
              },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
        tdrfknro54h4b0lwklhig: {
          id: 'tdrfknro54h4b0lwklhig',
          name: 'Web search tool',
          description: null,
          config: {
            mcp: {
              server: { url: 'https://test.com' },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
      },
      functionTools: {},
    },
    'meeting-prep-agent-heegun': {
      id: 'meeting-prep-agent-heegun',
      name: 'meeting-prep-agent-heegun',
      description: null,
      defaultSubAgentId: 'meeting-prep-coordinator',
      subAgents: {
        'meeting-finder': {
          id: 'meeting-finder',
          name: 'Meeting Finder',
          description: 'Finds upcoming meetings from Google Calendar',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: '7bssh9oqtuuxmn5t1fet6',
              toolId: '6bb1ve7v75qokhqcp7p1r',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
        'meeting-prep-coordinator': {
          id: 'meeting-prep-coordinator',
          name: 'Meeting Prep Coordinator',
          description:
            'Coordinates the meeting preparation workflow by delegating to meeting finder and web researcher',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: ['meeting-finder', 'web-researcher'],
          skills: [],
          dataComponents: ['meeting-tips-card'],
          artifactComponents: [],
          canUse: [],
        },
        'web-researcher': {
          id: 'web-researcher',
          name: 'Web Researcher',
          description: 'Conducts web research to gather information for meeting preparation',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: 'd9y1szl02jactyxrzmiaz',
              toolId: 'tdrfknro54h4b0lwklhig',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
      },
      stopWhen: { transferCountIs: 10 },
      tools: {
        '6bb1ve7v75qokhqcp7p1r': {
          id: '6bb1ve7v75qokhqcp7p1r',
          name: 'Google Calendar MCP',
          description: null,
          config: {
            mcp: {
              server: {
                url: 'https://test.com',
              },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
        tdrfknro54h4b0lwklhig: {
          id: 'tdrfknro54h4b0lwklhig',
          name: 'Web search tool',
          description: null,
          config: {
            mcp: {
              server: { url: 'https://test.com' },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
      },
      functionTools: {},
    },
    meetingprepagenkevinmira: {
      id: 'meetingprepagenkevinmira',
      name: 'MeetingPrepAgenKevinMira',
      description: null,
      defaultSubAgentId: 'meeting-prep-coordinator',
      subAgents: {
        'meeting-finder': {
          id: 'meeting-finder',
          name: 'Meeting Finder',
          description: 'Searches Google Calendar to find meetings based on user queries',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: 'nw1p2tjs0m9nt63xapndf',
              toolId: '6bb1ve7v75qokhqcp7p1r',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
        'meeting-prep-coordinator': {
          id: 'meeting-prep-coordinator',
          name: 'Meeting Prep Coordinator',
          description:
            'Orchestrates meeting preparation by coordinating calendar search and research',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: ['web-researcher', 'meeting-finder'],
          skills: [],
          dataComponents: ['meeting-tips-card'],
          artifactComponents: [],
          canUse: [],
        },
        'web-researcher': {
          id: 'web-researcher',
          name: 'Web Researcher',
          description: 'Conducts web research to gather information for meeting preparation',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: 'nghrxcf8nl6mybrhlptc6',
              toolId: 'tdrfknro54h4b0lwklhig',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
      },
      stopWhen: { transferCountIs: 10 },
      tools: {
        '6bb1ve7v75qokhqcp7p1r': {
          id: '6bb1ve7v75qokhqcp7p1r',
          name: 'Google Calendar MCP',
          description: null,
          config: {
            mcp: {
              server: {
                url: 'https://test.com',
              },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
        tdrfknro54h4b0lwklhig: {
          id: 'tdrfknro54h4b0lwklhig',
          name: 'Web search tool',
          description: null,
          config: {
            mcp: {
              server: { url: 'https://test.com' },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
      },
      functionTools: {},
    },
    'omar-nasser-agent': {
      id: 'omar-nasser-agent',
      name: 'Omar-Nasser-agent',
      description: null,
      defaultSubAgentId: 'meeting-prep-coordinator',
      subAgents: {
        'calendar-finder': {
          id: 'calendar-finder',
          name: 'Calendar Finder',
          description: 'Searches Google Calendar to find meetings',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: 'ya1tgflt65nf859wiglja',
              toolId: '6bb1ve7v75qokhqcp7p1r',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
        'meeting-prep-coordinator': {
          id: 'meeting-prep-coordinator',
          name: 'Meeting Prep Coordinator',
          description: 'Orchestrates the meeting preparation workflow',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: ['web-researcher', 'calendar-finder'],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [],
        },
        'web-researcher': {
          id: 'web-researcher',
          name: 'Web Researcher',
          description: 'Conducts web research to help prepare for meetings',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: '7fn697dfkqyz0rai8g3nh',
              toolId: 'tdrfknro54h4b0lwklhig',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
      },
      models: { base: { model: 'anthropic/claude-sonnet-4-5' } },
      stopWhen: { transferCountIs: 10 },
      tools: {
        '6bb1ve7v75qokhqcp7p1r': {
          id: '6bb1ve7v75qokhqcp7p1r',
          name: 'Google Calendar MCP',
          description: null,
          config: {
            mcp: {
              server: {
                url: 'https://test.com',
              },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
        tdrfknro54h4b0lwklhig: {
          id: 'tdrfknro54h4b0lwklhig',
          name: 'Web search tool',
          description: null,
          config: {
            mcp: {
              server: { url: 'https://test.com' },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
      },
      functionTools: {},
    },
    'qa-agent': {
      id: 'qa-agent',
      name: 'Q&A Agent',
      description: null,
      defaultSubAgentId: 'qa-sub-agent',
      subAgents: {
        'qa-sub-agent': {
          id: 'qa-sub-agent',
          name: 'Q&A sub agent',
          description: 'Responsible for search knowledge base and answering question',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: 'wlowjsep89o8muyg0k6i7',
              toolId: 'rjziaq0tono242cg91cvx',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
      },
      stopWhen: { transferCountIs: 10 },
      tools: {
        rjziaq0tono242cg91cvx: {
          id: 'rjziaq0tono242cg91cvx',
          name: 'Zendesk',
          description: null,
          config: {
            mcp: {
              server: { url: 'https://test.com' },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
      },
      functionTools: {},
    },
    'sales-agent': {
      id: 'sales-agent',
      name: 'Sales agent',
      description: null,
      defaultSubAgentId: 'sales-coordinator',
      subAgents: {
        'company-researcher': {
          id: 'company-researcher',
          name: 'Company Researcher',
          description: 'Researches company basics and relevant signals using web search',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: '1ipqdo8f8wxklhnqz91wr',
              toolId: 'tdrfknro54h4b0lwklhig',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
        'competitor-analyst': {
          id: 'competitor-analyst',
          name: 'Competitor Analyst',
          description: 'Identifies competitors and common gaps using web search',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: '8idbgpfskdfro53t73wsl',
              toolId: 'tdrfknro54h4b0lwklhig',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
        'inkeep-positioning': {
          id: 'inkeep-positioning',
          name: 'Inkeep Positioning Specialist',
          description: 'Retrieves Inkeep positioning and differentiators from documentation',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: 'faykfch5jdrvuc7cgz9y4',
              toolId: 'c7kdb6dt92nyb80ub2rng',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
        'sales-coordinator': {
          id: 'sales-coordinator',
          name: 'Sales Coordinator',
          description: 'Orchestrates the sales research workflow and synthesizes insights',
          prompt: 'test',
          models: { base: { model: 'openai/gpt-5.2' } },
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: ['company-researcher', 'inkeep-positioning', 'competitor-analyst'],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [],
        },
      },
      stopWhen: { transferCountIs: 10 },
      tools: {
        c7kdb6dt92nyb80ub2rng: {
          id: 'c7kdb6dt92nyb80ub2rng',
          name: 'Inkeep Enterprise Search MCP',
          description: null,
          config: {
            mcp: {
              server: { url: 'https://test.com' },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
        tdrfknro54h4b0lwklhig: {
          id: 'tdrfknro54h4b0lwklhig',
          name: 'Web search tool',
          description: null,
          config: {
            mcp: {
              server: { url: 'https://test.com' },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
      },
      functionTools: {},
    },
    'sales-intelligence-agent': {
      id: 'sales-intelligence-agent',
      name: 'Sales Intelligence Agent',
      description: null,
      defaultSubAgentId: 'sales-brief-coordinator',
      subAgents: {
        '4cp6qs8le8zq4ppiw40a8': {
          id: '4cp6qs8le8zq4ppiw40a8',
          name: 'Notion Writer SubAgent',
          description: '',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: 'owessnxnhq01389y2ipb2',
              toolId: 'svclt7yv8fg0dgtku6wm2',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
        'company-researcher': {
          id: 'company-researcher',
          name: 'Company Researcher',
          description:
            'Researches company basics and relevant signals using web search (max 2 searches)',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: 'y5jiotm88ijsa42fgl5ko',
              toolId: 'tdrfknro54h4b0lwklhig',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
        'competitor-analyst': {
          id: 'competitor-analyst',
          name: 'Competitor Analyst',
          description:
            'Identifies competitors/alternatives and common gaps using web search (max 2 searches)',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: '9829l3gbh956pjurpuqbr',
              toolId: 'tdrfknro54h4b0lwklhig',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
        'inkeep-positioning': {
          id: 'inkeep-positioning',
          name: 'Inkeep Positioning Specialist',
          description:
            'Retrieves Inkeep positioning and differentiators from documentation (max 2 searches)',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: '1zvzsgyz4d9r40wsytrz9',
              toolId: 'c7kdb6dt92nyb80ub2rng',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
            {
              agentToolRelationId: '2xtjjb9hronyjah7amhp3',
              toolId: 'svclt7yv8fg0dgtku6wm2',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
        'sales-brief-coordinator': {
          id: 'sales-brief-coordinator',
          name: 'Sales Brief Coordinator',
          description:
            'Orchestrates research workflow and synthesizes insights into a comprehensive sales brief',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [
            'company-researcher',
            'inkeep-positioning',
            'competitor-analyst',
            '4cp6qs8le8zq4ppiw40a8',
          ],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [],
        },
      },
      models: { base: { model: 'openai/gpt-5.2' } },
      stopWhen: { transferCountIs: 10 },
      tools: {
        svclt7yv8fg0dgtku6wm2: {
          id: 'svclt7yv8fg0dgtku6wm2',
          name: 'Notion',
          description: null,
          config: {
            mcp: {
              server: { url: 'https://test.com' },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
        c7kdb6dt92nyb80ub2rng: {
          id: 'c7kdb6dt92nyb80ub2rng',
          name: 'Inkeep Enterprise Search MCP',
          description: null,
          config: {
            mcp: {
              server: { url: 'https://test.com' },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
        tdrfknro54h4b0lwklhig: {
          id: 'tdrfknro54h4b0lwklhig',
          name: 'Web search tool',
          description: null,
          config: {
            mcp: {
              server: { url: 'https://test.com' },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
      },
      functionTools: {},
    },
    'sales-meeting-prep-agent': {
      id: 'sales-meeting-prep-agent',
      name: 'Sales Meeting Prep Agent',
      description: null,
      defaultSubAgentId: 'prep-coordinator',
      subAgents: {
        'calendar-finder': {
          id: 'calendar-finder',
          name: 'Calendar Finder',
          description: 'Finds upcoming sales meetings from Google Calendar',
          prompt: 'test',
          models: { base: { model: 'anthropic/claude-opus-4-5' } },
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: '70mqw509rummhjm20d4j7',
              toolId: '6bb1ve7v75qokhqcp7p1r',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
        'prep-coordinator': {
          id: 'prep-coordinator',
          name: 'Sales Prep Coordinator',
          description: 'Orchestrates the meeting prep workflow',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: ['sales-researcher', 'calendar-finder'],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [],
        },
        'sales-researcher': {
          id: 'sales-researcher',
          name: 'Sales Researcher',
          description: 'Conducts comprehensive web research for sales meeting preparation',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: 'l3b60nyixu8dhh5p0rnph',
              toolId: 'tdrfknro54h4b0lwklhig',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
      },
      models: { base: { model: 'openai/gpt-5.2' } },
      stopWhen: { transferCountIs: 10 },
      tools: {
        '6bb1ve7v75qokhqcp7p1r': {
          id: '6bb1ve7v75qokhqcp7p1r',
          name: 'Google Calendar MCP',
          description: null,
          config: {
            mcp: {
              server: {
                url: 'https://test.com',
              },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
        tdrfknro54h4b0lwklhig: {
          id: 'tdrfknro54h4b0lwklhig',
          name: 'Web search tool',
          description: null,
          config: {
            mcp: {
              server: { url: 'https://test.com' },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
      },
      functionTools: {},
    },
    'web-search-agent': {
      id: 'web-search-agent',
      name: 'Web search agent',
      description: null,
      defaultSubAgentId: 'web-search-subagent',
      subAgents: {
        'web-search-subagent': {
          id: 'web-search-subagent',
          name: 'Web Search Sub Agent',
          description: 'Performs web searches and returns relevant results',
          prompt: 'test',
          models: null,
          stopWhen: null,
          canTransferTo: [],
          canDelegateTo: [],
          skills: [],
          dataComponents: [],
          artifactComponents: [],
          canUse: [
            {
              agentToolRelationId: 'edx1gs30zh50pk4wjozd5',
              toolId: 'tdrfknro54h4b0lwklhig',
              toolSelection: null,
              headers: null,
              toolPolicies: null,
            },
          ],
        },
      },
      tools: {
        tdrfknro54h4b0lwklhig: {
          id: 'tdrfknro54h4b0lwklhig',
          name: 'Web search tool',
          description: null,
          config: {
            mcp: {
              server: { url: 'https://test.com' },
              transport: { type: 'streamable_http' },
            },
            type: 'mcp',
          },
          credentialReferenceId: null,
          imageUrl: 'https://test.png',
        },
      },
      functionTools: {},
    },
  },
  tools: {
    mkb40x7c6vz5720dp6bgx: {
      tenantId: 'default',
      id: 'mkb40x7c6vz5720dp6bgx',
      projectId: 'demo-project',
      name: 'Exa Web Search',
      description: null,
      config: {
        mcp: {
          prompt: '',
          server: {
            url: 'https://test.com',
          },
          transport: { type: 'streamable_http' },
          toolOverrides: {},
        },
        type: 'mcp',
      },
      credentialReferenceId: null,
      credentialScope: 'project',
      headers: null,
      imageUrl: 'https://test.png',
      capabilities: null,
      isWorkApp: false,
    },
    '6bb1ve7v75qokhqcp7p1r': {
      tenantId: 'default',
      id: '6bb1ve7v75qokhqcp7p1r',
      projectId: 'demo-project',
      name: 'Google Calendar MCP',
      description: null,
      config: {
        mcp: {
          server: {
            url: 'https://test.com',
          },
          transport: { type: 'streamable_http' },
        },
        type: 'mcp',
      },
      credentialReferenceId: null,
      credentialScope: 'user',
      headers: null,
      imageUrl: 'https://test.png',
      capabilities: null,
      isWorkApp: false,
    },
    svclt7yv8fg0dgtku6wm2: {
      tenantId: 'default',
      id: 'svclt7yv8fg0dgtku6wm2',
      projectId: 'demo-project',
      name: 'Notion',
      description: null,
      config: {
        mcp: {
          server: { url: 'https://test.com' },
          transport: { type: 'streamable_http' },
        },
        type: 'mcp',
      },
      credentialReferenceId: null,
      credentialScope: 'user',
      headers: null,
      imageUrl: 'https://test.png',
      capabilities: null,
      isWorkApp: false,
    },
    xsg3x642jcx5jmwmaenar: {
      tenantId: 'default',
      id: 'xsg3x642jcx5jmwmaenar',
      projectId: 'demo-project',
      name: 'Ashby MCP',
      description: null,
      config: {
        mcp: {
          server: {
            url: 'https://test.com',
          },
          transport: { type: 'streamable_http' },
        },
        type: 'mcp',
      },
      credentialReferenceId: null,
      credentialScope: 'project',
      headers: null,
      imageUrl: 'https://test.png',
      capabilities: null,
      isWorkApp: false,
    },
    wtftp4mk9hk7c1zd5rdi3: {
      tenantId: 'default',
      id: 'wtftp4mk9hk7c1zd5rdi3',
      projectId: 'demo-project',
      name: 'Supabase (Gaurav Varma)',
      description: null,
      config: {
        mcp: {
          server: { url: 'https://test.com' },
          transport: { type: 'streamable_http' },
        },
        type: 'mcp',
      },
      credentialReferenceId: 'l3e51vzt5atfwymmu4ur5',
      credentialScope: 'project',
      headers: null,
      imageUrl: 'https://test.png',
      capabilities: null,
      isWorkApp: false,
    },
    i6xrgvko43d61kwg1j0di: {
      tenantId: 'default',
      id: 'i6xrgvko43d61kwg1j0di',
      projectId: 'demo-project',
      name: 'Globalping (Justin Chavez)',
      description: null,
      config: {
        mcp: {
          server: { url: 'https://test.com' },
          transport: { type: 'streamable_http' },
        },
        type: 'mcp',
      },
      credentialReferenceId: null,
      credentialScope: 'project',
      headers: null,
      imageUrl: 'https://test.png',
      capabilities: null,
      isWorkApp: false,
    },
    rjziaq0tono242cg91cvx: {
      tenantId: 'default',
      id: 'rjziaq0tono242cg91cvx',
      projectId: 'demo-project',
      name: 'Zendesk',
      description: null,
      config: {
        mcp: {
          server: { url: 'https://test.com' },
          transport: { type: 'streamable_http' },
        },
        type: 'mcp',
      },
      credentialReferenceId: null,
      credentialScope: 'project',
      headers: null,
      imageUrl: 'https://test.png',
      capabilities: null,
      isWorkApp: false,
    },
    c7kdb6dt92nyb80ub2rng: {
      tenantId: 'default',
      id: 'c7kdb6dt92nyb80ub2rng',
      projectId: 'demo-project',
      name: 'Inkeep Enterprise Search MCP',
      description: null,
      config: {
        mcp: {
          server: { url: 'https://test.com' },
          transport: { type: 'streamable_http' },
        },
        type: 'mcp',
      },
      credentialReferenceId: null,
      credentialScope: 'project',
      headers: null,
      imageUrl: 'https://test.png',
      capabilities: null,
      isWorkApp: false,
    },
    '4cpdsk4n40c2423jmiocs': {
      tenantId: 'default',
      id: '4cpdsk4n40c2423jmiocs',
      projectId: 'demo-project',
      name: 'Gmail MCP',
      description: null,
      config: {
        mcp: {
          server: {
            url: 'https://test.com',
          },
          transport: { type: 'streamable_http' },
        },
        type: 'mcp',
      },
      credentialReferenceId: null,
      credentialScope: 'project',
      headers: null,
      imageUrl: 'https://test.png',
      capabilities: null,
      isWorkApp: false,
    },
    tdrfknro54h4b0lwklhig: {
      tenantId: 'default',
      id: 'tdrfknro54h4b0lwklhig',
      projectId: 'demo-project',
      name: 'Web search tool',
      description: null,
      config: {
        mcp: {
          server: { url: 'https://test.com' },
          transport: { type: 'streamable_http' },
        },
        type: 'mcp',
      },
      credentialReferenceId: null,
      credentialScope: 'project',
      headers: null,
      imageUrl: 'https://test.png',
      capabilities: null,
      isWorkApp: false,
    },
  },
  functions: null,
  externalAgents: null,
  dataComponents: null,
  artifactComponents: null,
  credentialReferences: {
    p2w6mieaqrfinek5imqx4: {
      tenantId: 'default',
      id: 'p2w6mieaqrfinek5imqx4',
      projectId: 'demo-project',
      name: 'Notion',
      type: 'nango',
      credentialStoreId: 'nango-default',
      retrievalParams: {
        authMode: 'OAUTH2',
        provider: 'mcp-generic',
        connectionId: 'ea2431ac-1520-454e-9f05-6286b2b85f44',
        providerConfigKey: 'notion_svcl',
      },
      toolId: 'svclt7yv8fg0dgtku6wm2',
      userId: 'Nwbx5F0GxmCD1nHtRcBRKpeW2w0dywbf',
    },
    '8samfrliooeknlbf7gn9z': {
      tenantId: 'default',
      id: '8samfrliooeknlbf7gn9z',
      projectId: 'demo-project',
      name: 'Notion',
      type: 'nango',
      credentialStoreId: 'nango-default',
      retrievalParams: {
        authMode: 'OAUTH2',
        provider: 'mcp-generic',
        connectionId: '82f3e9a3-8b5a-4cfe-978e-14252f633723',
        providerConfigKey: 'notion_svcl',
      },
      toolId: 'svclt7yv8fg0dgtku6wm2',
      userId: '64SzZGDIo8poIeI0BJOPFAdNfG9OFRn7',
    },
    wve281sig4881brnyn63c: {
      tenantId: 'default',
      id: 'wve281sig4881brnyn63c',
      projectId: 'demo-project',
      name: 'Notion',
      type: 'nango',
      credentialStoreId: 'nango-default',
      retrievalParams: {
        authMode: 'OAUTH2',
        provider: 'mcp-generic',
        connectionId: '858da7fa-52ea-4ab3-8046-80de655789f0',
        providerConfigKey: 'notion_svcl',
      },
      toolId: 'svclt7yv8fg0dgtku6wm2',
      userId: 'jdDroHFmaXZtD5kz8pGpGiRKYR5TsSFF',
    },
    rq6z45owo49eux0v8ms63: {
      tenantId: 'default',
      id: 'rq6z45owo49eux0v8ms63',
      projectId: 'demo-project',
      name: 'Notion',
      type: 'nango',
      credentialStoreId: 'nango-default',
      retrievalParams: {
        authMode: 'OAUTH2',
        provider: 'mcp-generic',
        connectionId: '31d32d69-cbb1-48ac-8796-00eb02e850d1',
        providerConfigKey: 'notion_noti',
      },
      toolId: null,
      userId: null,
    },
    l3e51vzt5atfwymmu4ur5: {
      tenantId: 'default',
      id: 'l3e51vzt5atfwymmu4ur5',
      projectId: 'demo-project',
      name: 'Supabase (Gaurav Varma)',
      type: 'nango',
      credentialStoreId: 'nango-default',
      retrievalParams: {
        authMode: 'OAUTH2',
        provider: 'mcp-generic',
        connectionId: 'e82678af-c1e3-4415-b0a7-96db77816450',
        providerConfigKey: 'supabase-gaurav-varma_wtft',
      },
      toolId: null,
      userId: null,
    },
    wof2nm307suqtj909z36n: {
      tenantId: 'default',
      id: 'wof2nm307suqtj909z36n',
      projectId: 'demo-project',
      name: 'Neon',
      type: 'nango',
      credentialStoreId: 'nango-default',
      retrievalParams: {
        authMode: 'OAUTH2',
        provider: 'mcp-generic',
        connectionId: 'b65b99f7-5ccc-429f-be4d-b1137438bed6',
        providerConfigKey: 'neon_tpr0',
      },
      toolId: null,
      userId: null,
    },
    ajkw9zmio8zj7jl423hv2: {
      tenantId: 'default',
      id: 'ajkw9zmio8zj7jl423hv2',
      projectId: 'demo-project',
      name: 'Notion OAuth Credential',
      type: 'nango',
      credentialStoreId: 'nango-default',
      retrievalParams: {
        authMode: 'OAUTH2',
        provider: 'mcp-generic',
        connectionId: '78bb863e-9f29-4778-98e7-23060a2cd5f8',
        providerConfigKey: 'notion_34nuouvv6heqtzhagmnns',
      },
      toolId: null,
      userId: null,
    },
  },
  statusUpdates: null,
  functionTools: null,
};
