workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Inkeep Agents API:
        inputs:
            - location: https://api.pilot.inkeep.com/openapi.json
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/inkeep/inkeep/inkeep-agents-api
targets:
    inkeep-agents:
        target: mcp-typescript
        source: Inkeep Agents API
