/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4009c91be960
 */

import * as z from "zod";

export type AgentEvaluatorRelation = {
  id: string;
  agentId: string;
  evaluatorId: string;
  createdAt: string;
  updatedAt: string;
};

export const AgentEvaluatorRelation$zodSchema: z.ZodType<
  AgentEvaluatorRelation
> = z.object({
  agentId: z.string(),
  createdAt: z.string(),
  evaluatorId: z.string(),
  id: z.string(),
  updatedAt: z.string(),
});
