/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c60555de6d8e
 */

import * as z from "zod";

export type CanRelateToInternalSubAgent = {
  subAgentId: string;
  subAgentSubAgentRelationId: string;
};

export const CanRelateToInternalSubAgent$zodSchema: z.ZodType<
  CanRelateToInternalSubAgent
> = z.object({
  subAgentId: z.string(),
  subAgentSubAgentRelationId: z.string(),
});
