/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e4e293666ca0
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { TriggerCreate, TriggerCreate$zodSchema } from "./triggercreate.js";
import {
  TriggerWithWebhookUrlWithWarningResponse,
  TriggerWithWebhookUrlWithWarningResponse$zodSchema,
} from "./triggerwithwebhookurlwithwarningresponse.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type CreateTriggerRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
  body?: TriggerCreate | undefined;
};

export const CreateTriggerRequest$zodSchema: z.ZodType<CreateTriggerRequest> = z
  .object({
    agentId: z.string().describe("Agent identifier"),
    body: TriggerCreate$zodSchema.optional(),
    projectId: z.string().describe("Project identifier"),
    tenantId: z.string().describe("Tenant identifier"),
  });

export type CreateTriggerResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  TriggerWithWebhookUrlWithWarningResponse?:
    | TriggerWithWebhookUrlWithWarningResponse
    | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const CreateTriggerResponse$zodSchema: z.ZodType<CreateTriggerResponse> =
  z.object({
    BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
    ContentType: z.string().describe(
      "HTTP response content type for this operation",
    ),
    Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
    InternalServerError: InternalServerError$zodSchema.optional().describe(
      "Internal Server Error",
    ),
    NotFound: NotFound$zodSchema.optional().describe("Not Found"),
    RawResponse: z.custom<Response>(x => x instanceof Response).describe(
      "Raw HTTP response; suitable for custom response parsing",
    ),
    StatusCode: z.int().describe(
      "HTTP response status code for this operation",
    ),
    TriggerWithWebhookUrlWithWarningResponse:
      TriggerWithWebhookUrlWithWarningResponse$zodSchema.optional().describe(
        "Trigger created successfully",
      ),
    Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
    UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
      "Unprocessable Entity",
    ),
  });
