/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5216d66d98be
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import {
  McpToolResponse,
  McpToolResponse$zodSchema,
} from "./mcptoolresponse.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { ToolCreate, ToolCreate$zodSchema } from "./toolcreate.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type CreateToolRequest = {
  tenantId: string;
  projectId: string;
  body?: ToolCreate | undefined;
};

export const CreateToolRequest$zodSchema: z.ZodType<CreateToolRequest> = z
  .object({
    body: ToolCreate$zodSchema.optional(),
    projectId: z.string().describe("Project identifier"),
    tenantId: z.string().describe("Tenant identifier"),
  });

export type CreateToolResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  McpToolResponse?: McpToolResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const CreateToolResponse$zodSchema: z.ZodType<CreateToolResponse> = z
  .object({
    BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
    ContentType: z.string().describe(
      "HTTP response content type for this operation",
    ),
    Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
    InternalServerError: InternalServerError$zodSchema.optional().describe(
      "Internal Server Error",
    ),
    McpToolResponse: McpToolResponse$zodSchema.optional().describe(
      "Tool created successfully",
    ),
    NotFound: NotFound$zodSchema.optional().describe("Not Found"),
    RawResponse: z.custom<Response>(x => x instanceof Response).describe(
      "Raw HTTP response; suitable for custom response parsing",
    ),
    StatusCode: z.int().describe(
      "HTTP response status code for this operation",
    ),
    Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
    UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
      "Unprocessable Entity",
    ),
  });
