/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 96ca7dd7d6c1
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import {
  EvaluationRunConfigWithSuiteConfigs,
  EvaluationRunConfigWithSuiteConfigs$zodSchema,
} from "./evaluationrunconfigwithsuiteconfigs.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type GetEvaluationRunConfigRequest = {
  tenantId: string;
  projectId: string;
  configId: string;
};

export const GetEvaluationRunConfigRequest$zodSchema: z.ZodType<
  GetEvaluationRunConfigRequest
> = z.object({
  configId: z.string(),
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

/**
 * Evaluation run config details
 */
export type GetEvaluationRunConfigResponseBody = {
  data: EvaluationRunConfigWithSuiteConfigs;
};

export const GetEvaluationRunConfigResponseBody$zodSchema: z.ZodType<
  GetEvaluationRunConfigResponseBody
> = z.object({
  data: EvaluationRunConfigWithSuiteConfigs$zodSchema,
}).describe("Evaluation run config details");

export type GetEvaluationRunConfigResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: GetEvaluationRunConfigResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const GetEvaluationRunConfigResponse$zodSchema: z.ZodType<
  GetEvaluationRunConfigResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
  object: z.lazy(() => GetEvaluationRunConfigResponseBody$zodSchema).optional(),
});
