/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e587eb8f2cb8
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type GetMcpToolGithubAccessRequest = {
  tenantId: string;
  projectId: string;
  toolId: string;
};

export const GetMcpToolGithubAccessRequest$zodSchema: z.ZodType<
  GetMcpToolGithubAccessRequest
> = z.object({
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
  toolId: z.string().describe("The tool ID"),
});

/**
 * Access mode: "all" means the MCP tool has access to all project repositories, "selected" means the tool is scoped to specific repositories
 */
export const GetMcpToolGithubAccessMode = {
  All: "all",
  Selected: "selected",
} as const;
/**
 * Access mode: "all" means the MCP tool has access to all project repositories, "selected" means the tool is scoped to specific repositories
 */
export type GetMcpToolGithubAccessMode = ClosedEnum<
  typeof GetMcpToolGithubAccessMode
>;

export const GetMcpToolGithubAccessMode$zodSchema = z.enum([
  "all",
  "selected",
]).describe(
  "Access mode: \"all\" means the MCP tool has access to all project repositories, \"selected\" means the tool is scoped to specific repositories",
);

export type GetMcpToolGithubAccessRepository = {
  id: string;
  installationDbId: string;
  repositoryId: string;
  repositoryName: string;
  repositoryFullName: string;
  private: boolean;
  createdAt: string;
  updatedAt: string;
  installationAccountLogin: string;
};

export const GetMcpToolGithubAccessRepository$zodSchema: z.ZodType<
  GetMcpToolGithubAccessRepository
> = z.object({
  createdAt: z.string(),
  id: z.string(),
  installationAccountLogin: z.string(),
  installationDbId: z.string(),
  private: z.boolean(),
  repositoryFullName: z.string(),
  repositoryId: z.string(),
  repositoryName: z.string(),
  updatedAt: z.string(),
});

/**
 * GitHub access configuration retrieved successfully
 */
export type GetMcpToolGithubAccessResponseBody = {
  mode: GetMcpToolGithubAccessMode;
  repositories: Array<GetMcpToolGithubAccessRepository>;
};

export const GetMcpToolGithubAccessResponseBody$zodSchema: z.ZodType<
  GetMcpToolGithubAccessResponseBody
> = z.object({
  mode: GetMcpToolGithubAccessMode$zodSchema,
  repositories: z.array(
    z.lazy(() => GetMcpToolGithubAccessRepository$zodSchema),
  ),
}).describe("GitHub access configuration retrieved successfully");

export type GetMcpToolGithubAccessResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: GetMcpToolGithubAccessResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const GetMcpToolGithubAccessResponse$zodSchema: z.ZodType<
  GetMcpToolGithubAccessResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
  object: z.lazy(() => GetMcpToolGithubAccessResponseBody$zodSchema).optional(),
});
