/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 05f54aac3a05
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import {
  TriggerInvocationListResponse,
  TriggerInvocationListResponse$zodSchema,
} from "./triggerinvocationlistresponse.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

/**
 * Filter by invocation status
 */
export const ListTriggerInvocationsStatus = {
  Pending: "pending",
  Success: "success",
  Failed: "failed",
} as const;
/**
 * Filter by invocation status
 */
export type ListTriggerInvocationsStatus = ClosedEnum<
  typeof ListTriggerInvocationsStatus
>;

export const ListTriggerInvocationsStatus$zodSchema = z.enum([
  "pending",
  "success",
  "failed",
]).describe("Filter by invocation status");

export type ListTriggerInvocationsRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
  id: string;
  page?: number | undefined;
  limit?: number | undefined;
  from?: string | undefined;
  to?: string | undefined;
  status?: ListTriggerInvocationsStatus | undefined;
};

export const ListTriggerInvocationsRequest$zodSchema: z.ZodType<
  ListTriggerInvocationsRequest
> = z.object({
  agentId: z.string().describe("Agent identifier"),
  from: z.iso.datetime({ offset: true }).describe(
    "Start date for filtering (ISO8601)",
  ).optional(),
  id: z.string().describe("Resource identifier"),
  limit: z.number().default(10),
  page: z.number().default(1),
  projectId: z.string().describe("Project identifier"),
  status: ListTriggerInvocationsStatus$zodSchema.optional(),
  tenantId: z.string().describe("Tenant identifier"),
  to: z.iso.datetime({ offset: true }).describe(
    "End date for filtering (ISO8601)",
  ).optional(),
});

export type ListTriggerInvocationsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  TriggerInvocationListResponse?: TriggerInvocationListResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const ListTriggerInvocationsResponse$zodSchema: z.ZodType<
  ListTriggerInvocationsResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  TriggerInvocationListResponse: TriggerInvocationListResponse$zodSchema
    .optional(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
