/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4e3cd1a6cf77
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export type PostRunV1ChatCompletionsSecurity = { bearerAuth: string };

export const PostRunV1ChatCompletionsSecurity$zodSchema: z.ZodType<
  PostRunV1ChatCompletionsSecurity
> = z.object({
  bearerAuth: z.string().describe(
    "Bearer token authentication. Use this for API clients and service-to-service communication. Set the Authorization header to \"Bearer <token>\".",
  ),
});

/**
 * The role of the message
 */
export const PostRunV1ChatCompletionsRole = {
  System: "system",
  User: "user",
  Assistant: "assistant",
  Function: "function",
  Tool: "tool",
} as const;
/**
 * The role of the message
 */
export type PostRunV1ChatCompletionsRole = ClosedEnum<
  typeof PostRunV1ChatCompletionsRole
>;

export const PostRunV1ChatCompletionsRole$zodSchema = z.enum([
  "system",
  "user",
  "assistant",
  "function",
  "tool",
]).describe("The role of the message");

export const TypeImageURL = {
  ImageUrl: "image_url",
} as const;
export type TypeImageURL = ClosedEnum<typeof TypeImageURL>;

export const TypeImageURL$zodSchema = z.enum([
  "image_url",
]);

export const DetailRequest = {
  Auto: "auto",
  Low: "low",
  High: "high",
} as const;
export type DetailRequest = ClosedEnum<typeof DetailRequest>;

export const DetailRequest$zodSchema = z.enum([
  "auto",
  "low",
  "high",
]);

export type ImageUrl = { url: string; detail?: DetailRequest | undefined };

export const ImageUrl$zodSchema: z.ZodType<ImageUrl> = z.object({
  detail: DetailRequest$zodSchema.optional(),
  url: z.string(),
});

export type ContentImageURL = { type: TypeImageURL; image_url: ImageUrl };

export const ContentImageURL$zodSchema: z.ZodType<ContentImageURL> = z.object({
  image_url: z.lazy(() => ImageUrl$zodSchema),
  type: TypeImageURL$zodSchema,
});

export const PostRunV1ChatCompletionsTypeText = {
  Text: "text",
} as const;
export type PostRunV1ChatCompletionsTypeText = ClosedEnum<
  typeof PostRunV1ChatCompletionsTypeText
>;

export const PostRunV1ChatCompletionsTypeText$zodSchema = z.enum([
  "text",
]);

export type ContentText = {
  type: PostRunV1ChatCompletionsTypeText;
  text: string;
};

export const ContentText$zodSchema: z.ZodType<ContentText> = z.object({
  text: z.string(),
  type: PostRunV1ChatCompletionsTypeText$zodSchema,
});

export type ContentUnion2 =
  | (ContentText & { type: "text" })
  | (ContentImageURL & { type: "image_url" });

export const ContentUnion2$zodSchema: z.ZodType<ContentUnion2> = z.union([
  z.lazy(() => ContentText$zodSchema).and(
    z.object({
      type: z.literal("text"),
    }).transform((v) => ({ type: v.type })),
  ),
  z.lazy(() => ContentImageURL$zodSchema).and(
    z.object({
      type: z.literal("image_url"),
    }).transform((v) => ({ type: v.type })),
  ),
]);

/**
 * The message content
 */
export type ContentUnion1 =
  | string
  | Array<
    (ContentText & { type: "text" }) | (ContentImageURL & { type: "image_url" })
  >;

export const ContentUnion1$zodSchema: z.ZodType<ContentUnion1> = z.union([
  z.string(),
  z.array(z.union([
    z.lazy(() => ContentText$zodSchema).and(
      z.object({
        type: z.literal("text"),
      }).transform((v) => ({ type: v.type })),
    ),
    z.lazy(() => ContentImageURL$zodSchema).and(
      z.object({
        type: z.literal("image_url"),
      }).transform((v) => ({ type: v.type })),
    ),
  ])),
]).describe("The message content");

export type PostRunV1ChatCompletionsMessage = {
  role: PostRunV1ChatCompletionsRole;
  content:
    | string
    | Array<
      | (ContentText & { type: "text" })
      | (ContentImageURL & { type: "image_url" })
    >;
  name?: string | undefined;
};

export const PostRunV1ChatCompletionsMessage$zodSchema: z.ZodType<
  PostRunV1ChatCompletionsMessage
> = z.object({
  content: z.union([
    z.string(),
    z.array(z.union([
      z.lazy(() => ContentText$zodSchema).and(
        z.object({
          type: z.literal("text"),
        }).transform((v) => ({ type: v.type })),
      ),
      z.lazy(() => ContentImageURL$zodSchema).and(
        z.object({
          type: z.literal("image_url"),
        }).transform((v) => ({ type: v.type })),
      ),
    ])),
  ]),
  name: z.string().optional(),
  role: PostRunV1ChatCompletionsRole$zodSchema,
});

export type PostRunV1ChatCompletionsRequest = {
  model: string;
  messages: Array<PostRunV1ChatCompletionsMessage>;
  temperature?: number | undefined;
  top_p?: number | undefined;
  n?: number | undefined;
  stream?: boolean | undefined;
  max_tokens?: number | undefined;
  presence_penalty?: number | undefined;
  frequency_penalty?: number | undefined;
  logit_bias?: { [k: string]: number } | undefined;
  user?: string | undefined;
  conversationId?: string | undefined;
  tools?: Array<string> | undefined;
  runConfig?: { [k: string]: any | null } | undefined;
  headers?: { [k: string]: any | null } | undefined;
};

export const PostRunV1ChatCompletionsRequest$zodSchema: z.ZodType<
  PostRunV1ChatCompletionsRequest
> = z.object({
  conversationId: z.string().optional(),
  frequency_penalty: z.number().optional(),
  headers: z.record(z.string(), z.any().nullable()).optional(),
  logit_bias: z.record(z.string(), z.number()).optional(),
  max_tokens: z.number().optional(),
  messages: z.array(z.lazy(() => PostRunV1ChatCompletionsMessage$zodSchema)),
  model: z.string(),
  n: z.number().optional(),
  presence_penalty: z.number().optional(),
  runConfig: z.record(z.string(), z.any().nullable()).optional(),
  stream: z.boolean().optional(),
  temperature: z.number().optional(),
  tools: z.array(z.string()).optional(),
  top_p: z.number().optional(),
  user: z.string().optional(),
});

/**
 * Internal server error
 */
export type PostRunV1ChatCompletionsInternalServerErrorResponseBody = {
  error: string;
  message: string;
};

export const PostRunV1ChatCompletionsInternalServerErrorResponseBody$zodSchema:
  z.ZodType<PostRunV1ChatCompletionsInternalServerErrorResponseBody> = z.object(
    {
      error: z.string(),
      message: z.string(),
    },
  ).describe("Internal server error");

/**
 * Agent or agent not found
 */
export type PostRunV1ChatCompletionsNotFoundResponseBody = { error: string };

export const PostRunV1ChatCompletionsNotFoundResponseBody$zodSchema: z.ZodType<
  PostRunV1ChatCompletionsNotFoundResponseBody
> = z.object({
  error: z.string(),
}).describe("Agent or agent not found");

export type DetailResponse = {
  field: string;
  message: string;
  value?: any | null | undefined;
};

export const DetailResponse$zodSchema: z.ZodType<DetailResponse> = z.object({
  field: z.string(),
  message: z.string(),
  value: z.any().nullable().optional(),
});

/**
 * Invalid request context or parameters
 */
export type PostRunV1ChatCompletionsBadRequestResponseBody = {
  error: string;
  details?: Array<DetailResponse> | undefined;
};

export const PostRunV1ChatCompletionsBadRequestResponseBody$zodSchema:
  z.ZodType<PostRunV1ChatCompletionsBadRequestResponseBody> = z.object({
    details: z.array(z.lazy(() => DetailResponse$zodSchema)).optional(),
    error: z.string(),
  }).describe("Invalid request context or parameters");

export type PostRunV1ChatCompletionsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredTextEventStreamRes?: string | undefined;
  fourHundredApplicationJsonObject?:
    | PostRunV1ChatCompletionsBadRequestResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | PostRunV1ChatCompletionsNotFoundResponseBody
    | undefined;
  fiveHundredApplicationJsonObject?:
    | PostRunV1ChatCompletionsInternalServerErrorResponseBody
    | undefined;
  Headers: { [k: string]: Array<string> };
};

export const PostRunV1ChatCompletionsResponse$zodSchema: z.ZodType<
  PostRunV1ChatCompletionsResponse
> = z.object({
  ContentType: z.string(),
  Headers: z.record(z.string(), z.array(z.string())).default({}),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  fiveHundredApplicationJsonObject: z.lazy(() =>
    PostRunV1ChatCompletionsInternalServerErrorResponseBody$zodSchema
  ).optional(),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    PostRunV1ChatCompletionsNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredApplicationJsonObject: z.lazy(() =>
    PostRunV1ChatCompletionsBadRequestResponseBody$zodSchema
  ).optional(),
  twoHundredTextEventStreamRes: z.string().describe(
    "Streaming chat completion response in Server-Sent Events format",
  ).optional(),
});
