/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f239fa626565
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export const RemoveProjectMemberRole = {
  ProjectAdmin: "project_admin",
  ProjectMember: "project_member",
  ProjectViewer: "project_viewer",
} as const;
export type RemoveProjectMemberRole = ClosedEnum<
  typeof RemoveProjectMemberRole
>;

export const RemoveProjectMemberRole$zodSchema = z.enum([
  "project_admin",
  "project_member",
  "project_viewer",
]);

export type RemoveProjectMemberRequest = {
  tenantId: string;
  projectId: string;
  userId: string;
  role: RemoveProjectMemberRole;
};

export const RemoveProjectMemberRequest$zodSchema: z.ZodType<
  RemoveProjectMemberRequest
> = z.object({
  projectId: z.string(),
  role: RemoveProjectMemberRole$zodSchema,
  tenantId: z.string(),
  userId: z.string(),
});

export type RemoveProjectMemberResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const RemoveProjectMemberResponse$zodSchema: z.ZodType<
  RemoveProjectMemberResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
  InternalServerError: InternalServerError$zodSchema.optional().describe(
    "Internal Server Error",
  ),
  NotFound: NotFound$zodSchema.optional().describe("Not Found"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
    "Unprocessable Entity",
  ),
});
