/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8eb94a17514b
 */

import * as z from "zod";

export type SlackSetChannelSettingsAgentConfig = {
  projectId: string;
  agentId: string;
  grantAccessToMembers?: boolean | undefined;
};

export const SlackSetChannelSettingsAgentConfig$zodSchema: z.ZodType<
  SlackSetChannelSettingsAgentConfig
> = z.object({
  agentId: z.string(),
  grantAccessToMembers: z.boolean().optional(),
  projectId: z.string(),
});

export type SlackSetChannelSettingsRequestBody = {
  agentConfig: SlackSetChannelSettingsAgentConfig;
  channelName?: string | undefined;
  channelType?: string | undefined;
};

export const SlackSetChannelSettingsRequestBody$zodSchema: z.ZodType<
  SlackSetChannelSettingsRequestBody
> = z.object({
  agentConfig: z.lazy(() => SlackSetChannelSettingsAgentConfig$zodSchema),
  channelName: z.string().optional(),
  channelType: z.string().optional(),
});

export type SlackSetChannelSettingsRequest = {
  teamId: string;
  channelId: string;
  body?: SlackSetChannelSettingsRequestBody | undefined;
};

export const SlackSetChannelSettingsRequest$zodSchema: z.ZodType<
  SlackSetChannelSettingsRequest
> = z.object({
  body: z.lazy(() => SlackSetChannelSettingsRequestBody$zodSchema).optional(),
  channelId: z.string(),
  teamId: z.string(),
});

/**
 * Channel settings updated
 */
export type SlackSetChannelSettingsResponseBody = {
  success: boolean;
  configId: string;
};

export const SlackSetChannelSettingsResponseBody$zodSchema: z.ZodType<
  SlackSetChannelSettingsResponseBody
> = z.object({
  configId: z.string(),
  success: z.boolean(),
}).describe("Channel settings updated");

export type SlackSetChannelSettingsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: SlackSetChannelSettingsResponseBody | undefined;
};

export const SlackSetChannelSettingsResponse$zodSchema: z.ZodType<
  SlackSetChannelSettingsResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  object: z.lazy(() => SlackSetChannelSettingsResponseBody$zodSchema).optional()
    .describe("Channel settings updated"),
});
