/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 45db7adc74b1
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type StartConversationsEvaluationsRequestBody = {
  conversationIds: Array<string>;
  evaluatorIds: Array<string>;
};

export const StartConversationsEvaluationsRequestBody$zodSchema: z.ZodType<
  StartConversationsEvaluationsRequestBody
> = z.object({
  conversationIds: z.array(z.string()),
  evaluatorIds: z.array(z.string()),
});

export type StartConversationsEvaluationsRequest = {
  tenantId: string;
  projectId: string;
  body?: StartConversationsEvaluationsRequestBody | undefined;
};

export const StartConversationsEvaluationsRequest$zodSchema: z.ZodType<
  StartConversationsEvaluationsRequest
> = z.object({
  body: z.lazy(() => StartConversationsEvaluationsRequestBody$zodSchema)
    .optional(),
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

/**
 * Evaluations triggered
 */
export type StartConversationsEvaluationsResponseBody = {
  message: string;
  evaluationRunId: string;
  conversationIds: Array<string>;
  evaluatorIds: Array<string>;
};

export const StartConversationsEvaluationsResponseBody$zodSchema: z.ZodType<
  StartConversationsEvaluationsResponseBody
> = z.object({
  conversationIds: z.array(z.string()),
  evaluationRunId: z.string(),
  evaluatorIds: z.array(z.string()),
  message: z.string(),
}).describe("Evaluations triggered");

export type StartConversationsEvaluationsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: StartConversationsEvaluationsResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const StartConversationsEvaluationsResponse$zodSchema: z.ZodType<
  StartConversationsEvaluationsResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
  object: z.lazy(() => StartConversationsEvaluationsResponseBody$zodSchema)
    .optional(),
});
