/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c9bbe377017e
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import {
  EvaluationResult,
  EvaluationResult$zodSchema,
} from "./evaluationresult.js";
import {
  EvaluationResultUpdate,
  EvaluationResultUpdate$zodSchema,
} from "./evaluationresultupdate.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type UpdateEvaluationResultRequest = {
  tenantId: string;
  projectId: string;
  resultId: string;
  body?: EvaluationResultUpdate | undefined;
};

export const UpdateEvaluationResultRequest$zodSchema: z.ZodType<
  UpdateEvaluationResultRequest
> = z.object({
  body: EvaluationResultUpdate$zodSchema.optional(),
  projectId: z.string().describe("Project identifier"),
  resultId: z.string(),
  tenantId: z.string().describe("Tenant identifier"),
});

/**
 * Evaluation result updated
 */
export type UpdateEvaluationResultResponseBody = { data: EvaluationResult };

export const UpdateEvaluationResultResponseBody$zodSchema: z.ZodType<
  UpdateEvaluationResultResponseBody
> = z.object({
  data: EvaluationResult$zodSchema,
}).describe("Evaluation result updated");

export type UpdateEvaluationResultResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: UpdateEvaluationResultResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const UpdateEvaluationResultResponse$zodSchema: z.ZodType<
  UpdateEvaluationResultResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
  object: z.lazy(() => UpdateEvaluationResultResponseBody$zodSchema).optional(),
});
