/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 887211b5263b
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Signing algorithm
 */
export const AddPublicKeyRequestAlgorithm = {
  Rs256: "RS256",
  Rs384: "RS384",
  Rs512: "RS512",
  Es256: "ES256",
  Es384: "ES384",
  Es512: "ES512",
  EdDSA: "EdDSA",
} as const;
/**
 * Signing algorithm
 */
export type AddPublicKeyRequestAlgorithm = ClosedEnum<
  typeof AddPublicKeyRequestAlgorithm
>;

export const AddPublicKeyRequestAlgorithm$zodSchema = z.enum([
  "RS256",
  "RS384",
  "RS512",
  "ES256",
  "ES384",
  "ES512",
  "EdDSA",
]).describe("Signing algorithm");

export type AddPublicKeyRequest = {
  kid: string;
  publicKey: string;
  algorithm: AddPublicKeyRequestAlgorithm;
};

export const AddPublicKeyRequest$zodSchema: z.ZodType<AddPublicKeyRequest> = z
  .object({
    algorithm: AddPublicKeyRequestAlgorithm$zodSchema.describe(
      "Signing algorithm",
    ),
    kid: z.string().describe("Key identifier"),
    publicKey: z.string().describe("PEM-encoded public key"),
  });
