/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AgentStopWhen, AgentStopWhen$zodSchema } from "./agentstopwhen.js";
import {
  ContextConfigCreate,
  ContextConfigCreate$zodSchema,
} from "./contextconfigcreate.js";
import {
  ExternalAgentCreate,
  ExternalAgentCreate$zodSchema,
} from "./externalagentcreate.js";
import {
  FullAgentAgentInsert,
  FullAgentAgentInsert$zodSchema,
} from "./fullagentagentinsert.js";
import { FunctionCreate, FunctionCreate$zodSchema } from "./functioncreate.js";
import {
  FunctionToolCreate,
  FunctionToolCreate$zodSchema,
} from "./functiontoolcreate.js";
import { Model, Model$zodSchema } from "./model.js";
import { StatusUpdate, StatusUpdate$zodSchema } from "./statusupdate.js";
import { TeamAgent, TeamAgent$zodSchema } from "./teamagent.js";
import { ToolCreate, ToolCreate$zodSchema } from "./toolcreate.js";
import { TriggerCreate, TriggerCreate$zodSchema } from "./triggercreate.js";

export type AgentWithinContextOfProject = {
  id: string;
  name: string;
  description?: string | null | undefined;
  defaultSubAgentId?: string | null | undefined;
  contextConfigId?: string | null | undefined;
  models?: Model | undefined;
  statusUpdates?: StatusUpdate | undefined;
  prompt?: string | undefined;
  stopWhen?: AgentStopWhen | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  subAgents: { [k: string]: FullAgentAgentInsert };
  tools?: { [k: string]: ToolCreate } | undefined;
  externalAgents?: { [k: string]: ExternalAgentCreate } | undefined;
  teamAgents?: { [k: string]: TeamAgent } | undefined;
  functionTools?: { [k: string]: FunctionToolCreate } | undefined;
  functions?: { [k: string]: FunctionCreate } | undefined;
  triggers?: { [k: string]: TriggerCreate } | undefined;
  contextConfig?: ContextConfigCreate | undefined;
};

export const AgentWithinContextOfProject$zodSchema: z.ZodType<
  AgentWithinContextOfProject
> = z.object({
  contextConfig: ContextConfigCreate$zodSchema.optional(),
  contextConfigId: z.string().nullable().optional(),
  createdAt: z.string().optional(),
  defaultSubAgentId: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  externalAgents: z.record(z.string(), ExternalAgentCreate$zodSchema)
    .optional(),
  functionTools: z.record(z.string(), FunctionToolCreate$zodSchema).optional(),
  functions: z.record(z.string(), FunctionCreate$zodSchema).optional(),
  id: z.string(),
  models: Model$zodSchema.optional(),
  name: z.string(),
  prompt: z.string().optional(),
  statusUpdates: StatusUpdate$zodSchema.optional(),
  stopWhen: AgentStopWhen$zodSchema.optional(),
  subAgents: z.record(z.string(), FullAgentAgentInsert$zodSchema),
  teamAgents: z.record(z.string(), TeamAgent$zodSchema).optional(),
  tools: z.record(z.string(), ToolCreate$zodSchema).optional(),
  triggers: z.record(z.string(), TriggerCreate$zodSchema).optional(),
  updatedAt: z.string().optional(),
});
