/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import {
  type AgentWithinContextOfProject,
  AgentWithinContextOfProject$zodSchema,
} from './agentwithincontextofproject.js';

export type AgentWithinContextOfProjectResponse = {
  data: AgentWithinContextOfProject;
};

export const AgentWithinContextOfProjectResponse$zodSchema: z.ZodType<
  AgentWithinContextOfProjectResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: AgentWithinContextOfProject$zodSchema,
});
