/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8eece35e2f09
 */

import * as z from "zod";

export type AgentDatasetRelation = {
  id: string;
  agentId: string;
  datasetId: string;
  createdAt: string;
  updatedAt: string;
};

export const AgentDatasetRelation$zodSchema: z.ZodType<AgentDatasetRelation> = z
  .object({
    agentId: z.string(),
    createdAt: z.string(),
    datasetId: z.string(),
    id: z.string(),
    updatedAt: z.string(),
  });
