/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 46896d26b78c
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ApiConfigType = {
  Api: "api",
} as const;
export type ApiConfigType = ClosedEnum<typeof ApiConfigType>;

export const ApiConfigType$zodSchema = z.enum([
  "api",
]);

export type Api = {};

export const Api$zodSchema: z.ZodType<Api> = z.object({});

export type ApiConfig = { type: ApiConfigType; api?: Api | undefined };

export const ApiConfig$zodSchema: z.ZodType<ApiConfig> = z.object({
  api: z.lazy(() => Api$zodSchema).optional(),
  type: ApiConfigType$zodSchema,
});
