/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dd19459c89de
 */

import * as z from "zod";
import {
  AppResponseItem,
  AppResponseItem$zodSchema,
} from "./appresponseitem.js";
import { Pagination, Pagination$zodSchema } from "./pagination.js";

export type AppListResponse = {
  data: Array<AppResponseItem>;
  pagination: Pagination;
};

export const AppListResponse$zodSchema: z.ZodType<AppListResponse> = z.object({
  data: z.array(AppResponseItem$zodSchema),
  pagination: Pagination$zodSchema,
});
