/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 067b7ff7d51d
 */

import * as z from "zod";

export type ArtifactComponent = {
  id: string;
  name: string;
  description: string | null;
  props?: any | null | undefined;
  render?: any | null | undefined;
  createdAt: string;
  updatedAt: string;
};

export const ArtifactComponent$zodSchema: z.ZodType<ArtifactComponent> = z
  .object({
    createdAt: z.string(),
    description: z.string().nullable(),
    id: z.string(),
    name: z.string(),
    props: z.any().nullable().optional(),
    render: z.any().nullable().optional(),
    updatedAt: z.string(),
  });
