/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d49b9794a7c8
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import {
  SubAgentArtifactComponentResponse,
  SubAgentArtifactComponentResponse$zodSchema,
} from "./subagentartifactcomponentresponse.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type AssociateArtifactComponentWithAgentRequestBody = {
  agentId: string;
  subAgentId: string;
  artifactComponentId: string;
};

export const AssociateArtifactComponentWithAgentRequestBody$zodSchema:
  z.ZodType<AssociateArtifactComponentWithAgentRequestBody> = z.object({
    agentId: z.string(),
    artifactComponentId: z.string(),
    subAgentId: z.string(),
  });

export type AssociateArtifactComponentWithAgentRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
  body?: AssociateArtifactComponentWithAgentRequestBody | undefined;
};

export const AssociateArtifactComponentWithAgentRequest$zodSchema: z.ZodType<
  AssociateArtifactComponentWithAgentRequest
> = z.object({
  agentId: z.string().describe("Agent identifier"),
  body: z.lazy(() => AssociateArtifactComponentWithAgentRequestBody$zodSchema)
    .optional(),
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

export type AssociateArtifactComponentWithAgentResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  SubAgentArtifactComponentResponse?:
    | SubAgentArtifactComponentResponse
    | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  ErrorResponse?: ErrorResponse | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const AssociateArtifactComponentWithAgentResponse$zodSchema: z.ZodType<
  AssociateArtifactComponentWithAgentResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  SubAgentArtifactComponentResponse: SubAgentArtifactComponentResponse$zodSchema
    .optional(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
