/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 863356bde955
 */

import * as z from "zod";

export type BranchInfo = { baseName: string; fullName: string; hash: string };

export const BranchInfo$zodSchema: z.ZodType<BranchInfo> = z.object({
  baseName: z.string(),
  fullName: z.string(),
  hash: z.string(),
});
