/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 23d9790404a2
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type CancelScheduledTriggerInvocationRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
  id: string;
  invocationId: string;
};

export const CancelScheduledTriggerInvocationRequest$zodSchema: z.ZodType<
  CancelScheduledTriggerInvocationRequest
> = z.object({
  agentId: z.string().describe("Agent identifier"),
  id: z.string().describe("Scheduled Trigger ID"),
  invocationId: z.string().describe("Scheduled Trigger Invocation ID"),
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

/**
 * Scheduled trigger invocation cancelled successfully
 */
export type CancelScheduledTriggerInvocationResponseBody = {
  success: boolean;
  invocationId: string;
  previousStatus?: string | undefined;
};

export const CancelScheduledTriggerInvocationResponseBody$zodSchema: z.ZodType<
  CancelScheduledTriggerInvocationResponseBody
> = z.object({
  invocationId: z.string(),
  previousStatus: z.string().optional(),
  success: z.boolean(),
}).describe("Scheduled trigger invocation cancelled successfully");

export type CancelScheduledTriggerInvocationResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: CancelScheduledTriggerInvocationResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const CancelScheduledTriggerInvocationResponse$zodSchema: z.ZodType<
  CancelScheduledTriggerInvocationResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
  object: z.lazy(() => CancelScheduledTriggerInvocationResponseBody$zodSchema)
    .optional(),
});
