/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 98ad262df7eb
 */

import * as z from "zod";

export type ConversationBoundsResponseData = {
  createdAt: string;
  updatedAt: string;
};

export const ConversationBoundsResponseData$zodSchema: z.ZodType<
  ConversationBoundsResponseData
> = z.object({
  createdAt: z.string(),
  updatedAt: z.string(),
});

export type ConversationBoundsResponse = {
  data: ConversationBoundsResponseData;
};

export const ConversationBoundsResponse$zodSchema: z.ZodType<
  ConversationBoundsResponse
> = z.object({
  data: z.lazy(() => ConversationBoundsResponseData$zodSchema),
});
