/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type CreatePlaygroundTokenSecurity = { cookieAuth: string };

export const CreatePlaygroundTokenSecurity$zodSchema: z.ZodType<
  CreatePlaygroundTokenSecurity
> = z.object({
  cookieAuth: z.string().describe(
    "Session-based authentication using HTTP-only cookies. Cookies are automatically sent by browsers. For server-side requests, include cookies with names starting with \"better-auth.\" in the Cookie header.",
  ),
});

export type CreatePlaygroundTokenRequestBody = {
  projectId: string;
  agentId: string;
};

export const CreatePlaygroundTokenRequestBody$zodSchema: z.ZodType<
  CreatePlaygroundTokenRequestBody
> = z.object({
  agentId: z.string(),
  projectId: z.string(),
});

export type CreatePlaygroundTokenRequest = {
  tenantId: string;
  body?: CreatePlaygroundTokenRequestBody | undefined;
};

export const CreatePlaygroundTokenRequest$zodSchema: z.ZodType<
  CreatePlaygroundTokenRequest
> = z.object({
  body: z.lazy(() => CreatePlaygroundTokenRequestBody$zodSchema).optional(),
  tenantId: z.string().describe("Tenant identifier"),
});

/**
 * Temporary API key generated successfully
 */
export type CreatePlaygroundTokenResponseBody = {
  apiKey: string;
  expiresAt: string;
};

export const CreatePlaygroundTokenResponseBody$zodSchema: z.ZodType<
  CreatePlaygroundTokenResponseBody
> = z.object({
  apiKey: z.string(),
  expiresAt: z.string(),
}).describe("Temporary API key generated successfully");

export type CreatePlaygroundTokenResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: CreatePlaygroundTokenResponseBody | undefined;
  ErrorResponse?: ErrorResponse | undefined;
};

export const CreatePlaygroundTokenResponse$zodSchema: z.ZodType<
  CreatePlaygroundTokenResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  object: z.lazy(() => CreatePlaygroundTokenResponseBody$zodSchema).optional(),
});
