/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0b623b22ad50
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { FeedbackCreate, FeedbackCreate$zodSchema } from "./feedbackcreate.js";
import {
  FeedbackResponse,
  FeedbackResponse$zodSchema,
} from "./feedbackresponse.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type CreateFeedbackRequest = {
  tenantId: string;
  projectId: string;
  body?: FeedbackCreate | undefined;
};

export const CreateFeedbackRequest$zodSchema: z.ZodType<CreateFeedbackRequest> =
  z.object({
    body: FeedbackCreate$zodSchema.optional(),
    projectId: z.string().describe("Project identifier"),
    tenantId: z.string().describe("Tenant identifier"),
  });

export type CreateFeedbackResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  FeedbackResponse?: FeedbackResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const CreateFeedbackResponse$zodSchema: z.ZodType<
  CreateFeedbackResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  FeedbackResponse: FeedbackResponse$zodSchema.optional(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
