/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 80253ecac118
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import {
  SubAgentToolRelationCreate,
  SubAgentToolRelationCreate$zodSchema,
} from "./subagenttoolrelationcreate.js";
import {
  SubAgentToolRelationResponse,
  SubAgentToolRelationResponse$zodSchema,
} from "./subagenttoolrelationresponse.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type CreateSubagentToolRelationRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
  body?: SubAgentToolRelationCreate | undefined;
};

export const CreateSubagentToolRelationRequest$zodSchema: z.ZodType<
  CreateSubagentToolRelationRequest
> = z.object({
  agentId: z.string().describe("Agent identifier"),
  body: SubAgentToolRelationCreate$zodSchema.optional(),
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

export type CreateSubagentToolRelationResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  SubAgentToolRelationResponse?: SubAgentToolRelationResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const CreateSubagentToolRelationResponse$zodSchema: z.ZodType<
  CreateSubagentToolRelationResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
  InternalServerError: InternalServerError$zodSchema.optional().describe(
    "Internal Server Error",
  ),
  NotFound: NotFound$zodSchema.optional().describe("Not Found"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  SubAgentToolRelationResponse: SubAgentToolRelationResponse$zodSchema
    .optional().describe("SubAgent tool relation created successfully"),
  Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
    "Unprocessable Entity",
  ),
});
