/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e4e293666ca0
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { TriggerCreate, TriggerCreate$zodSchema } from "./triggercreate.js";
import {
  TriggerWithWebhookUrlResponse,
  TriggerWithWebhookUrlResponse$zodSchema,
} from "./triggerwithwebhookurlresponse.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type CreateTriggerRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
  body?: TriggerCreate | undefined;
};

export const CreateTriggerRequest$zodSchema: z.ZodType<CreateTriggerRequest> = z
  .object({
    agentId: z.string().describe("Agent identifier"),
    body: TriggerCreate$zodSchema.optional(),
    projectId: z.string().describe("Project identifier"),
    tenantId: z.string().describe("Tenant identifier"),
  });

export type CreateTriggerResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  TriggerWithWebhookUrlResponse?: TriggerWithWebhookUrlResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const CreateTriggerResponse$zodSchema: z.ZodType<CreateTriggerResponse> =
  z.object({
    BadRequest: BadRequest$zodSchema.optional(),
    ContentType: z.string(),
    Forbidden: Forbidden$zodSchema.optional(),
    InternalServerError: InternalServerError$zodSchema.optional(),
    NotFound: NotFound$zodSchema.optional(),
    RawResponse: z.custom<Response>(x => x instanceof Response),
    StatusCode: z.int(),
    TriggerWithWebhookUrlResponse: TriggerWithWebhookUrlResponse$zodSchema
      .optional(),
    Unauthorized: Unauthorized$zodSchema.optional(),
    UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
  });
