/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 56ab81b2f33d
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { BranchResponse, BranchResponse$zodSchema } from "./branchresponse.js";
import {
  CreateBranchRequest,
  CreateBranchRequest$zodSchema,
} from "./createbranchrequest.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type CreateBranchRequestRequest = {
  tenantId: string;
  projectId: string;
  body?: CreateBranchRequest | undefined;
};

export const CreateBranchRequestRequest$zodSchema: z.ZodType<
  CreateBranchRequestRequest
> = z.object({
  body: CreateBranchRequest$zodSchema.optional(),
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

export type CreateBranchResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  BranchResponse?: BranchResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  ErrorResponse?: ErrorResponse | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const CreateBranchResponse$zodSchema: z.ZodType<CreateBranchResponse> = z
  .object({
    BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
    BranchResponse: BranchResponse$zodSchema.optional().describe(
      "Branch created successfully",
    ),
    ContentType: z.string().describe(
      "HTTP response content type for this operation",
    ),
    ErrorResponse: ErrorResponse$zodSchema.optional().describe(
      "Branch already exists",
    ),
    Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
    InternalServerError: InternalServerError$zodSchema.optional().describe(
      "Internal Server Error",
    ),
    NotFound: NotFound$zodSchema.optional().describe("Not Found"),
    RawResponse: z.custom<Response>(x => x instanceof Response).describe(
      "Raw HTTP response; suitable for custom response parsing",
    ),
    StatusCode: z.int().describe(
      "HTTP response status code for this operation",
    ),
    Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
    UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
      "Unprocessable Entity",
    ),
  });
