/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import { type BadRequest, BadRequest$zodSchema } from './badrequest.js';
import { type Forbidden, Forbidden$zodSchema } from './forbidden.js';
import { type FunctionCreate, FunctionCreate$zodSchema } from './functioncreate.js';
import { type FunctionResponse, FunctionResponse$zodSchema } from './functionresponse.js';
import { type InternalServerError, InternalServerError$zodSchema } from './internalservererror.js';
import { type NotFound, NotFound$zodSchema } from './notfound.js';
import { type Unauthorized, Unauthorized$zodSchema } from './unauthorized.js';
import { type UnprocessableEntity, UnprocessableEntity$zodSchema } from './unprocessableentity.js';

export type CreateFunctionRequest = {
  tenantId: string;
  projectId: string;
  body?: FunctionCreate | undefined;
};

export const CreateFunctionRequest$zodSchema: z.ZodType<
  CreateFunctionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  body: FunctionCreate$zodSchema.optional(),
  projectId: z.string().describe('Project identifier'),
  tenantId: z.string().describe('Tenant identifier'),
});

export type CreateFunctionResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  FunctionResponse?: FunctionResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const CreateFunctionResponse$zodSchema: z.ZodType<
  CreateFunctionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  FunctionResponse: FunctionResponse$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
