/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: edfe7f27234c
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import {
  SubAgentRelationCreate,
  SubAgentRelationCreate$zodSchema,
} from "./subagentrelationcreate.js";
import {
  SubAgentRelationResponse,
  SubAgentRelationResponse$zodSchema,
} from "./subagentrelationresponse.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type CreateSubAgentRelationRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
  body?: SubAgentRelationCreate | undefined;
};

export const CreateSubAgentRelationRequest$zodSchema: z.ZodType<
  CreateSubAgentRelationRequest
> = z.object({
  agentId: z.string().describe("Agent identifier"),
  body: SubAgentRelationCreate$zodSchema.optional(),
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

export type CreateSubAgentRelationResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  SubAgentRelationResponse?: SubAgentRelationResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const CreateSubAgentRelationResponse$zodSchema: z.ZodType<
  CreateSubAgentRelationResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
  InternalServerError: InternalServerError$zodSchema.optional().describe(
    "Internal Server Error",
  ),
  NotFound: NotFound$zodSchema.optional().describe("Not Found"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  SubAgentRelationResponse: SubAgentRelationResponse$zodSchema.optional()
    .describe("Sub Agent Relation created successfully"),
  Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
    "Unprocessable Entity",
  ),
});
