/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import {
  type AgentWithinContextOfProject,
  AgentWithinContextOfProject$zodSchema,
} from './agentwithincontextofproject.js';
import {
  type AgentWithinContextOfProjectResponse,
  AgentWithinContextOfProjectResponse$zodSchema,
} from './agentwithincontextofprojectresponse.js';
import { type BadRequest, BadRequest$zodSchema } from './badrequest.js';
import { type ErrorResponse, ErrorResponse$zodSchema } from './errorresponse.js';
import { type Forbidden, Forbidden$zodSchema } from './forbidden.js';
import { type InternalServerError, InternalServerError$zodSchema } from './internalservererror.js';
import { type NotFound, NotFound$zodSchema } from './notfound.js';
import { type Unauthorized, Unauthorized$zodSchema } from './unauthorized.js';
import { type UnprocessableEntity, UnprocessableEntity$zodSchema } from './unprocessableentity.js';

export type CreateFullAgentRequest = {
  tenantId: string;
  projectId: string;
  body?: AgentWithinContextOfProject | undefined;
};

export const CreateFullAgentRequest$zodSchema: z.ZodType<
  CreateFullAgentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  body: AgentWithinContextOfProject$zodSchema.optional(),
  projectId: z.string().describe('Project identifier'),
  tenantId: z.string().describe('Tenant identifier'),
});

export type CreateFullAgentResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  AgentWithinContextOfProjectResponse?: AgentWithinContextOfProjectResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  ErrorResponse?: ErrorResponse | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const CreateFullAgentResponse$zodSchema: z.ZodType<
  CreateFullAgentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  AgentWithinContextOfProjectResponse: AgentWithinContextOfProjectResponse$zodSchema.optional(),
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
