/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 458b15bc2b03
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import {
  ScheduledTriggerCreate,
  ScheduledTriggerCreate$zodSchema,
} from "./scheduledtriggercreate.js";
import {
  ScheduledTriggerResponse,
  ScheduledTriggerResponse$zodSchema,
} from "./scheduledtriggerresponse.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type CreateScheduledTriggerRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
  body?: ScheduledTriggerCreate | undefined;
};

export const CreateScheduledTriggerRequest$zodSchema: z.ZodType<
  CreateScheduledTriggerRequest
> = z.object({
  agentId: z.string().describe("Agent identifier"),
  body: ScheduledTriggerCreate$zodSchema.optional(),
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

export type CreateScheduledTriggerResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ScheduledTriggerResponse?: ScheduledTriggerResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const CreateScheduledTriggerResponse$zodSchema: z.ZodType<
  CreateScheduledTriggerResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  ScheduledTriggerResponse: ScheduledTriggerResponse$zodSchema.optional(),
  StatusCode: z.int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
