/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6165c1ca3035
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const CredentialReferenceType = {
  Memory: "memory",
  Keychain: "keychain",
  Nango: "nango",
} as const;
export type CredentialReferenceType = ClosedEnum<
  typeof CredentialReferenceType
>;

export const CredentialReferenceType$zodSchema = z.enum([
  "memory",
  "keychain",
  "nango",
]);

export type CredentialReferenceTool = {
  tenantId: string;
  id: string;
  projectId: string;
  name: string;
  description: string | null;
  config?: any | null | undefined;
  credentialReferenceId: string | null;
  credentialScope: string;
  headers?: any | null | undefined;
  imageUrl: string | null;
  capabilities?: any | null | undefined;
  lastError: string | null;
  isWorkApp: boolean;
  createdAt: string;
  updatedAt: string;
};

export const CredentialReferenceTool$zodSchema: z.ZodType<
  CredentialReferenceTool
> = z.object({
  capabilities: z.any().nullable().optional(),
  config: z.any().nullable().optional(),
  createdAt: z.string(),
  credentialReferenceId: z.string().nullable(),
  credentialScope: z.string(),
  description: z.string().nullable(),
  headers: z.any().nullable().optional(),
  id: z.string(),
  imageUrl: z.string().nullable(),
  isWorkApp: z.boolean(),
  lastError: z.string().nullable(),
  name: z.string(),
  projectId: z.string(),
  tenantId: z.string(),
  updatedAt: z.string(),
});

export type CredentialReferenceExternalAgent = {
  tenantId: string;
  id: string;
  projectId: string;
  name: string;
  description: string | null;
  baseUrl: string;
  credentialReferenceId?: string | null | undefined;
  createdAt: string;
  updatedAt: string;
};

export const CredentialReferenceExternalAgent$zodSchema: z.ZodType<
  CredentialReferenceExternalAgent
> = z.object({
  baseUrl: z.string(),
  createdAt: z.string(),
  credentialReferenceId: z.string().nullable().optional(),
  description: z.string().nullable(),
  id: z.string(),
  name: z.string(),
  projectId: z.string(),
  tenantId: z.string(),
  updatedAt: z.string(),
});

export type CredentialReference = {
  id: string;
  name: string;
  type: CredentialReferenceType;
  credentialStoreId: string;
  retrievalParams?: any | null | undefined;
  toolId: string | null;
  userId: string | null;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
  tools?: Array<CredentialReferenceTool> | undefined;
  externalAgents?: Array<CredentialReferenceExternalAgent> | undefined;
};

export const CredentialReference$zodSchema: z.ZodType<CredentialReference> = z
  .object({
    createdAt: z.string(),
    createdBy: z.string().nullable(),
    credentialStoreId: z.string(),
    externalAgents: z.array(
      z.lazy(() => CredentialReferenceExternalAgent$zodSchema),
    ).optional(),
    id: z.string(),
    name: z.string(),
    retrievalParams: z.any().nullable().optional(),
    toolId: z.string().nullable(),
    tools: z.array(z.lazy(() => CredentialReferenceTool$zodSchema)).optional(),
    type: CredentialReferenceType$zodSchema,
    updatedAt: z.string(),
    userId: z.string().nullable(),
  });
