/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a5d4c11b478c
 */

import * as z from "zod";
import {
  CredentialReference,
  CredentialReference$zodSchema,
} from "./credentialreference.js";
import { Pagination, Pagination$zodSchema } from "./pagination.js";

export type CredentialReferenceListResponse = {
  data: Array<CredentialReference>;
  pagination: Pagination;
};

export const CredentialReferenceListResponse$zodSchema: z.ZodType<
  CredentialReferenceListResponse
> = z.object({
  data: z.array(CredentialReference$zodSchema),
  pagination: Pagination$zodSchema,
});
