/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DatasetUpdate = {
  name?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
};

export const DatasetUpdate$zodSchema: z.ZodType<DatasetUpdate> = z.object({
  createdAt: z.string().optional(),
  name: z.string().optional(),
  updatedAt: z.string().optional(),
});
