/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0332aba33537
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The type of ref
 */
export const DatasetRunType = {
  Commit: "commit",
  Tag: "tag",
  Branch: "branch",
} as const;
/**
 * The type of ref
 */
export type DatasetRunType = ClosedEnum<typeof DatasetRunType>;

export const DatasetRunType$zodSchema = z.enum([
  "commit",
  "tag",
  "branch",
]).describe("The type of ref");

export type DatasetRunRef = {
  type: DatasetRunType;
  name: string;
  hash: string;
};

export const DatasetRunRef$zodSchema: z.ZodType<DatasetRunRef> = z.object({
  hash: z.string().describe("The commit hash this ref resolves to"),
  name: z.string().describe(
    "The name of the ref (branch name, tag name, or commit hash)",
  ),
  type: DatasetRunType$zodSchema.describe("The type of ref"),
});

export type DatasetRun = {
  id: string;
  datasetId: string;
  datasetRunConfigId: string | null;
  evaluationJobConfigId: string | null;
  ref?: DatasetRunRef | null | undefined;
  createdAt: string;
  updatedAt: string;
};

export const DatasetRun$zodSchema: z.ZodType<DatasetRun> = z.object({
  createdAt: z.string(),
  datasetId: z.string(),
  datasetRunConfigId: z.string().nullable(),
  evaluationJobConfigId: z.string().nullable(),
  id: z.string(),
  ref: z.lazy(() => DatasetRunRef$zodSchema).nullable().optional(),
  updatedAt: z.string(),
});
