/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import { type ErrorResponse, ErrorResponse$zodSchema } from './errorresponse.js';

export type DeleteApiKeyRequest = {
  tenantId: string;
  projectId: string;
  id: string;
};

export const DeleteApiKeyRequest$zodSchema: z.ZodType<DeleteApiKeyRequest, z.ZodTypeDef, unknown> =
  z.object({
    id: z.string().describe('Resource identifier'),
    projectId: z.string().describe('Project identifier'),
    tenantId: z.string().describe('Tenant identifier'),
  });

export type DeleteApiKeyResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ErrorResponse?: ErrorResponse | undefined;
};

export const DeleteApiKeyResponse$zodSchema: z.ZodType<
  DeleteApiKeyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
