/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 331d7e4564c7
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type DeleteExternalAgentRequest = {
  tenantId: string;
  projectId: string;
  id: string;
};

export const DeleteExternalAgentRequest$zodSchema: z.ZodType<
  DeleteExternalAgentRequest
> = z.object({
  id: z.string().describe("Resource identifier"),
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

export type DeleteExternalAgentResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ErrorResponse?: ErrorResponse | undefined;
};

export const DeleteExternalAgentResponse$zodSchema: z.ZodType<
  DeleteExternalAgentResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
});
