/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cbd94b498e09
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type DisconnectGithubInstallationRequest = {
  tenantId: string;
  installationId: string;
};

export const DisconnectGithubInstallationRequest$zodSchema: z.ZodType<
  DisconnectGithubInstallationRequest
> = z.object({
  installationId: z.string().describe("The internal installation ID"),
  tenantId: z.string().describe("Tenant identifier"),
});

/**
 * Installation disconnected successfully
 */
export type DisconnectGithubInstallationResponseBody = {
  success?: true | undefined;
};

export const DisconnectGithubInstallationResponseBody$zodSchema: z.ZodType<
  DisconnectGithubInstallationResponseBody
> = z.object({
  success: z.literal(true).default(true).optional().describe(
    "Whether the disconnection was successful",
  ),
}).describe("Installation disconnected successfully");

export type DisconnectGithubInstallationResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: DisconnectGithubInstallationResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const DisconnectGithubInstallationResponse$zodSchema: z.ZodType<
  DisconnectGithubInstallationResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
  InternalServerError: InternalServerError$zodSchema.optional().describe(
    "Internal Server Error",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
    "Unprocessable Entity",
  ),
  object: z.lazy(() => DisconnectGithubInstallationResponseBody$zodSchema)
    .optional().describe("Installation disconnected successfully"),
});
