/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type EvaluationResultUpdate = {
  conversationId?: string | undefined;
  evaluatorId?: string | undefined;
  evaluationRunId?: string | null | undefined;
  output?: any | null | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
};

export const EvaluationResultUpdate$zodSchema: z.ZodType<
  EvaluationResultUpdate
> = z.object({
  conversationId: z.string().optional(),
  createdAt: z.string().optional(),
  evaluationRunId: z.string().nullable().optional(),
  evaluatorId: z.string().optional(),
  output: z.any().nullable().optional(),
  updatedAt: z.string().optional(),
});
