/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 060ac7e2bfc6
 */

import * as z from "zod";

export type EvaluationSuiteConfig = {
  id: string;
  filters?: any | null | undefined;
  sampleRate: number | null;
  createdAt: string;
  updatedAt: string;
};

export const EvaluationSuiteConfig$zodSchema: z.ZodType<EvaluationSuiteConfig> =
  z.object({
    createdAt: z.string(),
    filters: z.any().nullable().optional(),
    id: z.string(),
    sampleRate: z.number().nullable(),
    updatedAt: z.string(),
  });
