/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3cf652120af9
 */

import * as z from "zod";

export type ExternalAgent = {
  id: string;
  name: string;
  description: string | null;
  baseUrl: string;
  credentialReferenceId?: string | null | undefined;
  createdAt: string;
  updatedAt: string;
};

export const ExternalAgent$zodSchema: z.ZodType<ExternalAgent> = z.object({
  baseUrl: z.string(),
  createdAt: z.string(),
  credentialReferenceId: z.string().nullable().optional(),
  description: z.string().nullable(),
  id: z.string(),
  name: z.string(),
  updatedAt: z.string(),
});
