/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  CanDelegateToExternalAgentInsert,
  CanDelegateToExternalAgentInsert$zodSchema,
} from "./candelegatetoexternalagentinsert.js";
import {
  CanDelegateToTeamAgentInsert,
  CanDelegateToTeamAgentInsert$zodSchema,
} from "./candelegatetoteamagentinsert.js";
import { CanUseItem, CanUseItem$zodSchema } from "./canuseitem.js";
import { Model, Model$zodSchema } from "./model.js";

export const FullAgentAgentInsertType = {
  Internal: "internal",
} as const;
export type FullAgentAgentInsertType = ClosedEnum<
  typeof FullAgentAgentInsertType
>;

export const FullAgentAgentInsertType$zodSchema = z.enum([
  "internal",
]);

export type FullAgentAgentInsertCanDelegateTo =
  | CanDelegateToExternalAgentInsert
  | CanDelegateToTeamAgentInsert
  | string;

export const FullAgentAgentInsertCanDelegateTo$zodSchema: z.ZodType<
  FullAgentAgentInsertCanDelegateTo
> = z.union([
  CanDelegateToExternalAgentInsert$zodSchema,
  CanDelegateToTeamAgentInsert$zodSchema,
  z.string(),
]);

export type FullAgentAgentInsert = {
  id: string;
  name: string;
  description?: string | null | undefined;
  prompt?: string | undefined;
  conversationHistoryConfig?: any | null | undefined;
  models?: Model | undefined;
  stopWhen?: any | null | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  type: FullAgentAgentInsertType;
  canUse: Array<CanUseItem>;
  dataComponents?: Array<string> | undefined;
  artifactComponents?: Array<string> | undefined;
  canTransferTo?: Array<string> | undefined;
  canDelegateTo?:
    | Array<
      CanDelegateToExternalAgentInsert | CanDelegateToTeamAgentInsert | string
    >
    | undefined;
};

export const FullAgentAgentInsert$zodSchema: z.ZodType<FullAgentAgentInsert> = z
  .object({
    artifactComponents: z.array(z.string()).optional(),
    canDelegateTo: z.array(z.union([
      CanDelegateToExternalAgentInsert$zodSchema,
      CanDelegateToTeamAgentInsert$zodSchema,
      z.string(),
    ])).optional(),
    canTransferTo: z.array(z.string()).optional(),
    canUse: z.array(CanUseItem$zodSchema),
    conversationHistoryConfig: z.any().nullable().optional(),
    createdAt: z.string().optional(),
    dataComponents: z.array(z.string()).optional(),
    description: z.string().nullable().optional(),
    id: z.string(),
    models: Model$zodSchema.optional(),
    name: z.string(),
    prompt: z.string().optional(),
    stopWhen: z.any().nullable().optional(),
    type: FullAgentAgentInsertType$zodSchema,
    updatedAt: z.string().optional(),
  });
