/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 020b0e50a246
 */

import * as z from "zod";
import {
  FullProjectSelectWithRelationIds,
  FullProjectSelectWithRelationIds$zodSchema,
} from "./fullprojectselectwithrelationids.js";

export type FullProjectSelectWithRelationIdsResponse = {
  data: FullProjectSelectWithRelationIds;
};

export const FullProjectSelectWithRelationIdsResponse$zodSchema: z.ZodType<
  FullProjectSelectWithRelationIdsResponse
> = z.object({
  data: FullProjectSelectWithRelationIds$zodSchema,
});
