/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 88f5a0333de4
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  CanDelegateToExternalAgent,
  CanDelegateToExternalAgent$zodSchema,
} from "./candelegatetoexternalagent.js";
import {
  CanDelegateToTeamAgent,
  CanDelegateToTeamAgent$zodSchema,
} from "./candelegatetoteamagent.js";
import { CanUseItem, CanUseItem$zodSchema } from "./canuseitem.js";

export const FullAgentSubAgentSelectType = {
  Internal: "internal",
} as const;
export type FullAgentSubAgentSelectType = ClosedEnum<
  typeof FullAgentSubAgentSelectType
>;

export const FullAgentSubAgentSelectType$zodSchema = z.enum([
  "internal",
]);

export type FullAgentSubAgentSelectCanDelegateTo =
  | CanDelegateToExternalAgent
  | CanDelegateToTeamAgent
  | string;

export const FullAgentSubAgentSelectCanDelegateTo$zodSchema: z.ZodType<
  FullAgentSubAgentSelectCanDelegateTo
> = z.union([
  CanDelegateToExternalAgent$zodSchema,
  CanDelegateToTeamAgent$zodSchema,
  z.string(),
]);

export type FullAgentSubAgentSelect = {
  id: string;
  name: string;
  description: string | null;
  prompt: string | null;
  conversationHistoryConfig?: any | null | undefined;
  models?: any | null | undefined;
  stopWhen?: any | null | undefined;
  createdAt: string;
  updatedAt: string;
  type: FullAgentSubAgentSelectType;
  canUse: Array<CanUseItem>;
  dataComponents: Array<string> | null;
  artifactComponents: Array<string> | null;
  canTransferTo: Array<string> | null;
  canDelegateTo:
    | Array<CanDelegateToExternalAgent | CanDelegateToTeamAgent | string>
    | null;
};

export const FullAgentSubAgentSelect$zodSchema: z.ZodType<
  FullAgentSubAgentSelect
> = z.object({
  artifactComponents: z.array(z.string()).nullable(),
  canDelegateTo: z.array(z.union([
    CanDelegateToExternalAgent$zodSchema,
    CanDelegateToTeamAgent$zodSchema,
    z.string(),
  ])).nullable(),
  canTransferTo: z.array(z.string()).nullable(),
  canUse: z.array(CanUseItem$zodSchema),
  conversationHistoryConfig: z.any().nullable().optional(),
  createdAt: z.string(),
  dataComponents: z.array(z.string()).nullable(),
  description: z.string().nullable(),
  id: z.string(),
  models: z.any().nullable().optional(),
  name: z.string(),
  prompt: z.string().nullable(),
  stopWhen: z.any().nullable().optional(),
  type: FullAgentSubAgentSelectType$zodSchema,
  updatedAt: z.string(),
});
