/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { FunctionTool, FunctionTool$zodSchema } from "./functiontool.js";

export type FunctionToolResponse = { data: FunctionTool };

export const FunctionToolResponse$zodSchema: z.ZodType<
  FunctionToolResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: FunctionTool$zodSchema,
});
