/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 97fd05628bcf
 */

import * as z from "zod";

export type FunctionCreate = {
  id: string;
  inputSchema?: { [k: string]: any | null } | null | undefined;
  executeCode: string;
  dependencies?: { [k: string]: string } | null | undefined;
};

export const FunctionCreate$zodSchema: z.ZodType<FunctionCreate> = z.object({
  dependencies: z.record(z.string(), z.string()).nullable().optional(),
  executeCode: z.string(),
  id: z.string().describe("Resource identifier"),
  inputSchema: z.record(z.string(), z.any().nullable()).nullable().optional(),
});
