/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 44dd2f63e495
 */

import * as z from "zod";
import {
  ArtifactComponentArrayResponse,
  ArtifactComponentArrayResponse$zodSchema,
} from "./artifactcomponentarrayresponse.js";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type GetArtifactComponentsForAgentRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
  subAgentId: string;
};

export const GetArtifactComponentsForAgentRequest$zodSchema: z.ZodType<
  GetArtifactComponentsForAgentRequest
> = z.object({
  agentId: z.string().describe("Agent identifier"),
  projectId: z.string().describe("Project identifier"),
  subAgentId: z.string().describe("Sub-agent identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

export type GetArtifactComponentsForAgentResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ArtifactComponentArrayResponse?: ArtifactComponentArrayResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const GetArtifactComponentsForAgentResponse$zodSchema: z.ZodType<
  GetArtifactComponentsForAgentResponse
> = z.object({
  ArtifactComponentArrayResponse: ArtifactComponentArrayResponse$zodSchema
    .optional().describe("Artifact components retrieved successfully"),
  BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
  InternalServerError: InternalServerError$zodSchema.optional().describe(
    "Internal Server Error",
  ),
  NotFound: NotFound$zodSchema.optional().describe("Not Found"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
    "Unprocessable Entity",
  ),
});
