/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetApiWorkflowProcessResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
};

export const GetApiWorkflowProcessResponse$zodSchema: z.ZodType<
  GetApiWorkflowProcessResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
});
