/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0dc7c3ca4eac
 */

import * as z from "zod";
import {
  ArtifactComponentResponse,
  ArtifactComponentResponse$zodSchema,
} from "./artifactcomponentresponse.js";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type GetArtifactComponentByIdRequest = {
  tenantId: string;
  projectId: string;
  id: string;
};

export const GetArtifactComponentByIdRequest$zodSchema: z.ZodType<
  GetArtifactComponentByIdRequest
> = z.object({
  id: z.string().describe("Resource identifier"),
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

export type GetArtifactComponentByIdResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ArtifactComponentResponse?: ArtifactComponentResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const GetArtifactComponentByIdResponse$zodSchema: z.ZodType<
  GetArtifactComponentByIdResponse
> = z.object({
  ArtifactComponentResponse: ArtifactComponentResponse$zodSchema.optional()
    .describe("Artifact component found"),
  BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
  InternalServerError: InternalServerError$zodSchema.optional().describe(
    "Internal Server Error",
  ),
  NotFound: NotFound$zodSchema.optional().describe("Not Found"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
    "Unprocessable Entity",
  ),
});
