/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 282ea7416d3a
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import {
  ContextConfigResponse,
  ContextConfigResponse$zodSchema,
} from "./contextconfigresponse.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type GetContextConfigByIdRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
  id: string;
};

export const GetContextConfigByIdRequest$zodSchema: z.ZodType<
  GetContextConfigByIdRequest
> = z.object({
  agentId: z.string().describe("Agent identifier"),
  id: z.string().describe("Resource identifier"),
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

export type GetContextConfigByIdResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ContextConfigResponse?: ContextConfigResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const GetContextConfigByIdResponse$zodSchema: z.ZodType<
  GetContextConfigByIdResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  ContextConfigResponse: ContextConfigResponse$zodSchema.optional().describe(
    "Context configuration found",
  ),
  Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
  InternalServerError: InternalServerError$zodSchema.optional().describe(
    "Internal Server Error",
  ),
  NotFound: NotFound$zodSchema.optional().describe("Not Found"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
    "Unprocessable Entity",
  ),
});
