/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 369e727e1df1
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import {
  ConversationWithFormattedMessagesResponse,
  ConversationWithFormattedMessagesResponse$zodSchema,
} from "./conversationwithformattedmessagesresponse.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type GetConversationRequest = {
  tenantId: string;
  projectId: string;
  id: string;
  limit?: number | undefined;
  includeInternal?: boolean | null | undefined;
};

export const GetConversationRequest$zodSchema: z.ZodType<
  GetConversationRequest
> = z.object({
  id: z.string().describe("Resource identifier"),
  includeInternal: z.boolean().default(false).nullable(),
  limit: z.number().default(20),
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

export type GetConversationResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ConversationWithFormattedMessagesResponse?:
    | ConversationWithFormattedMessagesResponse
    | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const GetConversationResponse$zodSchema: z.ZodType<
  GetConversationResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  ConversationWithFormattedMessagesResponse:
    ConversationWithFormattedMessagesResponse$zodSchema.optional().describe(
      "Conversation found with formatted messages for LLM use",
    ),
  Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
  InternalServerError: InternalServerError$zodSchema.optional().describe(
    "Internal Server Error",
  ),
  NotFound: NotFound$zodSchema.optional().describe("Not Found"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
    "Unprocessable Entity",
  ),
});
