/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 25bbe310bade
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Dataset, Dataset$zodSchema } from "./dataset.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type GetDatasetRequest = {
  tenantId: string;
  projectId: string;
  datasetId: string;
};

export const GetDatasetRequest$zodSchema: z.ZodType<GetDatasetRequest> = z
  .object({
    datasetId: z.string(),
    projectId: z.string().describe("Project identifier"),
    tenantId: z.string().describe("Tenant identifier"),
  });

/**
 * Dataset details
 */
export type GetDatasetResponseBody = { data: Dataset };

export const GetDatasetResponseBody$zodSchema: z.ZodType<
  GetDatasetResponseBody
> = z.object({
  data: Dataset$zodSchema,
}).describe("Dataset details");

export type GetDatasetResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: GetDatasetResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const GetDatasetResponse$zodSchema: z.ZodType<GetDatasetResponse> = z
  .object({
    BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
    ContentType: z.string().describe(
      "HTTP response content type for this operation",
    ),
    Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
    InternalServerError: InternalServerError$zodSchema.optional().describe(
      "Internal Server Error",
    ),
    NotFound: NotFound$zodSchema.optional().describe("Not Found"),
    RawResponse: z.custom<Response>(x => x instanceof Response).describe(
      "Raw HTTP response; suitable for custom response parsing",
    ),
    StatusCode: z.int().describe(
      "HTTP response status code for this operation",
    ),
    Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
    UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
      "Unprocessable Entity",
    ),
    object: z.lazy(() => GetDatasetResponseBody$zodSchema).optional().describe(
      "Dataset details",
    ),
  });
