/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 20fac96cfdca
 */

import * as z from "zod";
import {
  AgentWithinContextOfProjectResponse,
  AgentWithinContextOfProjectResponse$zodSchema,
} from "./agentwithincontextofprojectresponse.js";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type GetFullAgentRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
};

export const GetFullAgentRequest$zodSchema: z.ZodType<GetFullAgentRequest> = z
  .object({
    agentId: z.string().describe("Agent identifier"),
    projectId: z.string().describe("Project identifier"),
    tenantId: z.string().describe("Tenant identifier"),
  });

export type GetFullAgentResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  AgentWithinContextOfProjectResponse?:
    | AgentWithinContextOfProjectResponse
    | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const GetFullAgentResponse$zodSchema: z.ZodType<GetFullAgentResponse> = z
  .object({
    AgentWithinContextOfProjectResponse:
      AgentWithinContextOfProjectResponse$zodSchema.optional().describe(
        "Full agent found",
      ),
    BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
    ContentType: z.string().describe(
      "HTTP response content type for this operation",
    ),
    Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
    InternalServerError: InternalServerError$zodSchema.optional().describe(
      "Internal Server Error",
    ),
    NotFound: NotFound$zodSchema.optional().describe("Not Found"),
    RawResponse: z.custom<Response>(x => x instanceof Response).describe(
      "Raw HTTP response; suitable for custom response parsing",
    ),
    StatusCode: z.int().describe(
      "HTTP response status code for this operation",
    ),
    Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
    UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
      "Unprocessable Entity",
    ),
  });
