/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 002430a2bd63
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type GetMcpToolSlackAccessRequest = {
  tenantId: string;
  projectId: string;
  toolId: string;
};

export const GetMcpToolSlackAccessRequest$zodSchema: z.ZodType<
  GetMcpToolSlackAccessRequest
> = z.object({
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
  toolId: z.string().describe("The tool ID"),
});

/**
 * Channel access mode: "all" means the MCP tool can post to any channel, "selected" means the tool is scoped to specific channels
 */
export const GetMcpToolSlackAccessChannelAccessMode = {
  All: "all",
  Selected: "selected",
} as const;
/**
 * Channel access mode: "all" means the MCP tool can post to any channel, "selected" means the tool is scoped to specific channels
 */
export type GetMcpToolSlackAccessChannelAccessMode = ClosedEnum<
  typeof GetMcpToolSlackAccessChannelAccessMode
>;

export const GetMcpToolSlackAccessChannelAccessMode$zodSchema = z.enum([
  "all",
  "selected",
]).describe(
  "Channel access mode: \"all\" means the MCP tool can post to any channel, \"selected\" means the tool is scoped to specific channels",
);

/**
 * Slack access configuration retrieved successfully
 */
export type GetMcpToolSlackAccessResponseBody = {
  channelAccessMode: GetMcpToolSlackAccessChannelAccessMode;
  dmEnabled: boolean;
  channelIds?: Array<string> | undefined;
};

export const GetMcpToolSlackAccessResponseBody$zodSchema: z.ZodType<
  GetMcpToolSlackAccessResponseBody
> = z.object({
  channelAccessMode: GetMcpToolSlackAccessChannelAccessMode$zodSchema.describe(
    "Channel access mode: \"all\" means the MCP tool can post to any channel, \"selected\" means the tool is scoped to specific channels",
  ),
  channelIds: z.array(z.string()).optional().describe(
    "List of allowed channel IDs (only used when channelAccessMode is \"selected\")",
  ),
  dmEnabled: z.boolean().describe("Whether DM access is enabled for this tool"),
}).describe("Slack access configuration retrieved successfully");

export type GetMcpToolSlackAccessResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: GetMcpToolSlackAccessResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const GetMcpToolSlackAccessResponse$zodSchema: z.ZodType<
  GetMcpToolSlackAccessResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
  InternalServerError: InternalServerError$zodSchema.optional().describe(
    "Internal Server Error",
  ),
  NotFound: NotFound$zodSchema.optional().describe("Not Found"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
    "Unprocessable Entity",
  ),
  object: z.lazy(() => GetMcpToolSlackAccessResponseBody$zodSchema).optional()
    .describe("Slack access configuration retrieved successfully"),
});
