/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

/**
 * The credential scope
 */
export const GetOauthRedirectUrlCredentialScope = {
  Project: "project",
  User: "user",
} as const;
/**
 * The credential scope
 */
export type GetOauthRedirectUrlCredentialScope = ClosedEnum<
  typeof GetOauthRedirectUrlCredentialScope
>;

export const GetOauthRedirectUrlCredentialScope$zodSchema = z.enum([
  "project",
  "user",
]).describe("The credential scope");

export type GetOauthRedirectUrlRequestBody = {
  url: string;
  credentialScope: GetOauthRedirectUrlCredentialScope;
};

export const GetOauthRedirectUrlRequestBody$zodSchema: z.ZodType<
  GetOauthRedirectUrlRequestBody
> = z.object({
  credentialScope: GetOauthRedirectUrlCredentialScope$zodSchema,
  url: z.string(),
});

export type GetOauthRedirectUrlRequest = {
  tenantId: string;
  projectId: string;
  body?: GetOauthRedirectUrlRequestBody | undefined;
};

export const GetOauthRedirectUrlRequest$zodSchema: z.ZodType<
  GetOauthRedirectUrlRequest
> = z.object({
  body: z.lazy(() => GetOauthRedirectUrlRequestBody$zodSchema).optional(),
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

export type GetOauthRedirectUrlData = { redirectUrl: string | null };

export const GetOauthRedirectUrlData$zodSchema: z.ZodType<
  GetOauthRedirectUrlData
> = z.object({
  redirectUrl: z.string().nullable(),
});

/**
 * OAuth redirect URL
 */
export type GetOauthRedirectUrlResponseBody = { data: GetOauthRedirectUrlData };

export const GetOauthRedirectUrlResponseBody$zodSchema: z.ZodType<
  GetOauthRedirectUrlResponseBody
> = z.object({
  data: z.lazy(() => GetOauthRedirectUrlData$zodSchema),
}).describe("OAuth redirect URL");

export type GetOauthRedirectUrlResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: GetOauthRedirectUrlResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const GetOauthRedirectUrlResponse$zodSchema: z.ZodType<
  GetOauthRedirectUrlResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
  object: z.lazy(() => GetOauthRedirectUrlResponseBody$zodSchema).optional(),
});
