/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6bfebc8dd541
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type GetProjectGithubAccessRequest = {
  tenantId: string;
  projectId: string;
};

export const GetProjectGithubAccessRequest$zodSchema: z.ZodType<
  GetProjectGithubAccessRequest
> = z.object({
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

/**
 * Access mode: "all" means project has access to all tenant repositories, "selected" means project is scoped to specific repositories
 */
export const GetProjectGithubAccessMode = {
  All: "all",
  Selected: "selected",
} as const;
/**
 * Access mode: "all" means project has access to all tenant repositories, "selected" means project is scoped to specific repositories
 */
export type GetProjectGithubAccessMode = ClosedEnum<
  typeof GetProjectGithubAccessMode
>;

export const GetProjectGithubAccessMode$zodSchema = z.enum([
  "all",
  "selected",
]).describe(
  "Access mode: \"all\" means project has access to all tenant repositories, \"selected\" means project is scoped to specific repositories",
);

export type GetProjectGithubAccessRepository = {
  id: string;
  installationDbId: string;
  repositoryId: string;
  repositoryName: string;
  repositoryFullName: string;
  private: boolean;
  createdAt: string;
  updatedAt: string;
};

export const GetProjectGithubAccessRepository$zodSchema: z.ZodType<
  GetProjectGithubAccessRepository
> = z.object({
  createdAt: z.string(),
  id: z.string(),
  installationDbId: z.string(),
  private: z.boolean(),
  repositoryFullName: z.string(),
  repositoryId: z.string(),
  repositoryName: z.string(),
  updatedAt: z.string(),
});

/**
 * GitHub access configuration for a project
 */
export type GetProjectGithubAccessResponseBody = {
  mode: GetProjectGithubAccessMode;
  repositories: Array<GetProjectGithubAccessRepository>;
};

export const GetProjectGithubAccessResponseBody$zodSchema: z.ZodType<
  GetProjectGithubAccessResponseBody
> = z.object({
  mode: GetProjectGithubAccessMode$zodSchema,
  repositories: z.array(
    z.lazy(() => GetProjectGithubAccessRepository$zodSchema),
  ),
}).describe("GitHub access configuration for a project");

export type GetProjectGithubAccessResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: GetProjectGithubAccessResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const GetProjectGithubAccessResponse$zodSchema: z.ZodType<
  GetProjectGithubAccessResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
  object: z.lazy(() => GetProjectGithubAccessResponseBody$zodSchema).optional(),
});
