/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5e1556f58da0
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export type GetRunApiExecutionsExecutionIdSecurity = { bearerAuth: string };

export const GetRunApiExecutionsExecutionIdSecurity$zodSchema: z.ZodType<
  GetRunApiExecutionsExecutionIdSecurity
> = z.object({
  bearerAuth: z.string().describe(
    "Bearer token authentication. Use this for API clients and service-to-service communication. Set the Authorization header to \"Bearer <token>\".",
  ),
});

export type GetRunApiExecutionsExecutionIdRequest = { executionId: string };

export const GetRunApiExecutionsExecutionIdRequest$zodSchema: z.ZodType<
  GetRunApiExecutionsExecutionIdRequest
> = z.object({
  executionId: z.string(),
});

/**
 * Execution not found
 */
export type GetRunApiExecutionsExecutionIdNotFoundResponseBody = {
  error: string;
};

export const GetRunApiExecutionsExecutionIdNotFoundResponseBody$zodSchema:
  z.ZodType<GetRunApiExecutionsExecutionIdNotFoundResponseBody> = z.object({
    error: z.string(),
  }).describe("Execution not found");

export const GetRunApiExecutionsExecutionIdStatus = {
  Running: "running",
  Suspended: "suspended",
  Completed: "completed",
  Failed: "failed",
} as const;
export type GetRunApiExecutionsExecutionIdStatus = ClosedEnum<
  typeof GetRunApiExecutionsExecutionIdStatus
>;

export const GetRunApiExecutionsExecutionIdStatus$zodSchema = z.enum([
  "running",
  "suspended",
  "completed",
  "failed",
]);

/**
 * Execution status
 */
export type GetRunApiExecutionsExecutionIdResponseBody = {
  id: string;
  status: GetRunApiExecutionsExecutionIdStatus;
  conversationId: string;
  agentId: string;
  createdAt: string;
  updatedAt: string;
};

export const GetRunApiExecutionsExecutionIdResponseBody$zodSchema: z.ZodType<
  GetRunApiExecutionsExecutionIdResponseBody
> = z.object({
  agentId: z.string(),
  conversationId: z.string(),
  createdAt: z.string(),
  id: z.string(),
  status: GetRunApiExecutionsExecutionIdStatus$zodSchema,
  updatedAt: z.string(),
}).describe("Execution status");

export type GetRunApiExecutionsExecutionIdResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?:
    | GetRunApiExecutionsExecutionIdResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | GetRunApiExecutionsExecutionIdNotFoundResponseBody
    | undefined;
};

export const GetRunApiExecutionsExecutionIdResponse$zodSchema: z.ZodType<
  GetRunApiExecutionsExecutionIdResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    GetRunApiExecutionsExecutionIdNotFoundResponseBody$zodSchema
  ).optional().describe("Execution not found"),
  twoHundredApplicationJsonObject: z.lazy(() =>
    GetRunApiExecutionsExecutionIdResponseBody$zodSchema
  ).optional().describe("Execution status"),
});
