/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 58e8c365c9d9
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import {
  ScheduledTriggerInvocationResponse,
  ScheduledTriggerInvocationResponse$zodSchema,
} from "./scheduledtriggerinvocationresponse.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type GetScheduledTriggerInvocationByIdRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
  id: string;
  invocationId: string;
};

export const GetScheduledTriggerInvocationByIdRequest$zodSchema: z.ZodType<
  GetScheduledTriggerInvocationByIdRequest
> = z.object({
  agentId: z.string().describe("Agent identifier"),
  id: z.string().describe("Scheduled Trigger ID"),
  invocationId: z.string().describe("Scheduled Trigger Invocation ID"),
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

export type GetScheduledTriggerInvocationByIdResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ScheduledTriggerInvocationResponse?:
    | ScheduledTriggerInvocationResponse
    | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const GetScheduledTriggerInvocationByIdResponse$zodSchema: z.ZodType<
  GetScheduledTriggerInvocationByIdResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
  InternalServerError: InternalServerError$zodSchema.optional().describe(
    "Internal Server Error",
  ),
  NotFound: NotFound$zodSchema.optional().describe("Not Found"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  ScheduledTriggerInvocationResponse:
    ScheduledTriggerInvocationResponse$zodSchema.optional().describe(
      "Scheduled trigger invocation found",
    ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
    "Unprocessable Entity",
  ),
});
