/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';

export type HealthResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
};

export const HealthResponse$zodSchema: z.ZodType<HealthResponse, z.ZodTypeDef, unknown> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
