/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b7edd34c3de2
 */

import * as z from "zod";

export type InitiateToolOauthLoginRequest = {
  tenantId: string;
  projectId: string;
  id: string;
};

export const InitiateToolOauthLoginRequest$zodSchema: z.ZodType<
  InitiateToolOauthLoginRequest
> = z.object({
  id: z.string().describe("Resource identifier"),
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

export type InitiateToolOauthLoginResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  fourHundredTextHtmlRes?: string | undefined;
  fourHundredAndFourTextHtmlRes?: string | undefined;
  fiveHundredTextHtmlRes?: string | undefined;
};

export const InitiateToolOauthLoginResponse$zodSchema: z.ZodType<
  InitiateToolOauthLoginResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fiveHundredTextHtmlRes: z.string().describe("Internal server error")
    .optional(),
  fourHundredAndFourTextHtmlRes: z.string().describe("Tool not found")
    .optional(),
  fourHundredTextHtmlRes: z.string().describe(
    "OAuth not supported or configuration error",
  ).optional(),
});
