/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0991ecf8f453
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import {
  SubAgentTeamAgentRelationListResponse,
  SubAgentTeamAgentRelationListResponse$zodSchema,
} from "./subagentteamagentrelationlistresponse.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type ListSubAgentTeamAgentRelationsRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
  subAgentId: string;
  page?: number | undefined;
  limit?: number | undefined;
};

export const ListSubAgentTeamAgentRelationsRequest$zodSchema: z.ZodType<
  ListSubAgentTeamAgentRelationsRequest
> = z.object({
  agentId: z.string().describe("Agent identifier"),
  limit: z.number().default(10),
  page: z.number().default(1),
  projectId: z.string().describe("Project identifier"),
  subAgentId: z.string().describe("Sub-agent identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

export type ListSubAgentTeamAgentRelationsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  SubAgentTeamAgentRelationListResponse?:
    | SubAgentTeamAgentRelationListResponse
    | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const ListSubAgentTeamAgentRelationsResponse$zodSchema: z.ZodType<
  ListSubAgentTeamAgentRelationsResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
  InternalServerError: InternalServerError$zodSchema.optional().describe(
    "Internal Server Error",
  ),
  NotFound: NotFound$zodSchema.optional().describe("Not Found"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  SubAgentTeamAgentRelationListResponse:
    SubAgentTeamAgentRelationListResponse$zodSchema.optional().describe(
      "List of sub agent team agent relations retrieved successfully",
    ),
  Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
    "Unprocessable Entity",
  ),
});
