/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9767e6d3137e
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import {
  EvaluationJobConfig,
  EvaluationJobConfig$zodSchema,
} from "./evaluationjobconfig.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Pagination, Pagination$zodSchema } from "./pagination.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type ListEvaluationJobConfigsRequest = {
  tenantId: string;
  projectId: string;
};

export const ListEvaluationJobConfigsRequest$zodSchema: z.ZodType<
  ListEvaluationJobConfigsRequest
> = z.object({
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

/**
 * List of evaluation job configs
 */
export type ListEvaluationJobConfigsResponseBody = {
  data: Array<EvaluationJobConfig>;
  pagination: Pagination;
};

export const ListEvaluationJobConfigsResponseBody$zodSchema: z.ZodType<
  ListEvaluationJobConfigsResponseBody
> = z.object({
  data: z.array(EvaluationJobConfig$zodSchema),
  pagination: Pagination$zodSchema,
}).describe("List of evaluation job configs");

export type ListEvaluationJobConfigsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: ListEvaluationJobConfigsResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const ListEvaluationJobConfigsResponse$zodSchema: z.ZodType<
  ListEvaluationJobConfigsResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
  InternalServerError: InternalServerError$zodSchema.optional().describe(
    "Internal Server Error",
  ),
  NotFound: NotFound$zodSchema.optional().describe("Not Found"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
    "Unprocessable Entity",
  ),
  object: z.lazy(() => ListEvaluationJobConfigsResponseBody$zodSchema)
    .optional().describe("List of evaluation job configs"),
});
