/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 551f913fb456
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type ListGithubInstallationsRequest = {
  tenantId: string;
  includeDisconnected?: string | undefined;
};

export const ListGithubInstallationsRequest$zodSchema: z.ZodType<
  ListGithubInstallationsRequest
> = z.object({
  includeDisconnected: z.string().describe(
    "Include disconnected installations in the response",
  ).optional(),
  tenantId: z.string().describe("Tenant identifier"),
});

export type ListGithubInstallationsInstallation = {
  id: string;
  installationId: string;
  accountLogin: string;
  accountId: string;
  accountType: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  repositoryCount: number;
};

export const ListGithubInstallationsInstallation$zodSchema: z.ZodType<
  ListGithubInstallationsInstallation
> = z.object({
  accountId: z.string(),
  accountLogin: z.string(),
  accountType: z.string(),
  createdAt: z.string(),
  id: z.string(),
  installationId: z.string(),
  repositoryCount: z.number(),
  status: z.string(),
  updatedAt: z.string(),
});

/**
 * List of GitHub App installations
 */
export type ListGithubInstallationsResponseBody = {
  installations: Array<ListGithubInstallationsInstallation>;
};

export const ListGithubInstallationsResponseBody$zodSchema: z.ZodType<
  ListGithubInstallationsResponseBody
> = z.object({
  installations: z.array(
    z.lazy(() => ListGithubInstallationsInstallation$zodSchema),
  ),
}).describe("List of GitHub App installations");

export type ListGithubInstallationsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: ListGithubInstallationsResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const ListGithubInstallationsResponse$zodSchema: z.ZodType<
  ListGithubInstallationsResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
  object: z.lazy(() => ListGithubInstallationsResponseBody$zodSchema)
    .optional(),
});
