/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1e5ed9dab5ec
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import {
  ScheduledTriggerWithRunInfoListResponse,
  ScheduledTriggerWithRunInfoListResponse$zodSchema,
} from "./scheduledtriggerwithruninfolistresponse.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type ListScheduledTriggersRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
  page?: number | undefined;
  limit?: number | undefined;
};

export const ListScheduledTriggersRequest$zodSchema: z.ZodType<
  ListScheduledTriggersRequest
> = z.object({
  agentId: z.string().describe("Agent identifier"),
  limit: z.number().default(10),
  page: z.number().default(1),
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

export type ListScheduledTriggersResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ScheduledTriggerWithRunInfoListResponse?:
    | ScheduledTriggerWithRunInfoListResponse
    | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const ListScheduledTriggersResponse$zodSchema: z.ZodType<
  ListScheduledTriggersResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  ScheduledTriggerWithRunInfoListResponse:
    ScheduledTriggerWithRunInfoListResponse$zodSchema.optional(),
  StatusCode: z.int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
