/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6d4ead8d7be5
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import {
  EvaluationRunConfigWithSuiteConfigs,
  EvaluationRunConfigWithSuiteConfigs$zodSchema,
} from "./evaluationrunconfigwithsuiteconfigs.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Pagination, Pagination$zodSchema } from "./pagination.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type ListEvaluationRunConfigsRequest = {
  tenantId: string;
  projectId: string;
};

export const ListEvaluationRunConfigsRequest$zodSchema: z.ZodType<
  ListEvaluationRunConfigsRequest
> = z.object({
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

/**
 * List of evaluation run configs
 */
export type ListEvaluationRunConfigsResponseBody = {
  data: Array<EvaluationRunConfigWithSuiteConfigs>;
  pagination: Pagination;
};

export const ListEvaluationRunConfigsResponseBody$zodSchema: z.ZodType<
  ListEvaluationRunConfigsResponseBody
> = z.object({
  data: z.array(EvaluationRunConfigWithSuiteConfigs$zodSchema),
  pagination: Pagination$zodSchema,
}).describe("List of evaluation run configs");

export type ListEvaluationRunConfigsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: ListEvaluationRunConfigsResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const ListEvaluationRunConfigsResponse$zodSchema: z.ZodType<
  ListEvaluationRunConfigsResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
  object: z.lazy(() => ListEvaluationRunConfigsResponseBody$zodSchema)
    .optional(),
});
