/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cc17a87ece75
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Evaluator, Evaluator$zodSchema } from "./evaluator.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Pagination, Pagination$zodSchema } from "./pagination.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type ListEvaluatorsRequest = {
  tenantId: string;
  projectId: string;
  agentId?: string | undefined;
};

export const ListEvaluatorsRequest$zodSchema: z.ZodType<ListEvaluatorsRequest> =
  z.object({
    agentId: z.string().optional(),
    projectId: z.string().describe("Project identifier"),
    tenantId: z.string().describe("Tenant identifier"),
  });

/**
 * List of evaluators
 */
export type ListEvaluatorsResponseBody = {
  data: Array<Evaluator>;
  pagination: Pagination;
};

export const ListEvaluatorsResponseBody$zodSchema: z.ZodType<
  ListEvaluatorsResponseBody
> = z.object({
  data: z.array(Evaluator$zodSchema),
  pagination: Pagination$zodSchema,
}).describe("List of evaluators");

export type ListEvaluatorsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: ListEvaluatorsResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const ListEvaluatorsResponse$zodSchema: z.ZodType<
  ListEvaluatorsResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
  InternalServerError: InternalServerError$zodSchema.optional().describe(
    "Internal Server Error",
  ),
  NotFound: NotFound$zodSchema.optional().describe("Not Found"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
    "Unprocessable Entity",
  ),
  object: z.lazy(() => ListEvaluatorsResponseBody$zodSchema).optional()
    .describe("List of evaluators"),
});
