/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4a4f65fcda35
 */

import * as z from "zod";
import { DataPart, DataPart$zodSchema } from "./datapart.js";
import { FilePart, FilePart$zodSchema } from "./filepart.js";
import { TextPart, TextPart$zodSchema } from "./textpart.js";

export type Part =
  | (TextPart & { kind: "text" })
  | (FilePart & { kind: "file" })
  | (DataPart & { kind: "data" });

export const Part$zodSchema: z.ZodType<Part> = z.union([
  TextPart$zodSchema.and(
    z.object({
      kind: z.literal("text"),
    }).transform((v) => ({ kind: v.kind })),
  ),
  FilePart$zodSchema.and(
    z.object({
      kind: z.literal("file"),
    }).transform((v) => ({ kind: v.kind })),
  ),
  DataPart$zodSchema.and(
    z.object({
      kind: z.literal("data"),
    }).transform((v) => ({ kind: v.kind })),
  ),
]);
