/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4e3cd1a6cf77
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export type PostRunV1ChatCompletionsSecurity = { bearerAuth: string };

export const PostRunV1ChatCompletionsSecurity$zodSchema: z.ZodType<
  PostRunV1ChatCompletionsSecurity
> = z.object({
  bearerAuth: z.string().describe(
    "Bearer token authentication. Use this for API clients and service-to-service communication. Set the Authorization header to \"Bearer <token>\".",
  ),
});

/**
 * The role of the message
 */
export const PostRunV1ChatCompletionsRole = {
  System: "system",
  User: "user",
  Assistant: "assistant",
  Function: "function",
  Tool: "tool",
} as const;
/**
 * The role of the message
 */
export type PostRunV1ChatCompletionsRole = ClosedEnum<
  typeof PostRunV1ChatCompletionsRole
>;

export const PostRunV1ChatCompletionsRole$zodSchema = z.enum([
  "system",
  "user",
  "assistant",
  "function",
  "tool",
]).describe("The role of the message");

export const PostRunV1ChatCompletionsTypeFile = {
  File: "file",
} as const;
export type PostRunV1ChatCompletionsTypeFile = ClosedEnum<
  typeof PostRunV1ChatCompletionsTypeFile
>;

export const PostRunV1ChatCompletionsTypeFile$zodSchema = z.enum([
  "file",
]);

export type PostRunV1ChatCompletionsFile = {
  file_data: string;
  filename?: string | undefined;
};

export const PostRunV1ChatCompletionsFile$zodSchema: z.ZodType<
  PostRunV1ChatCompletionsFile
> = z.object({
  file_data: z.string(),
  filename: z.string().optional(),
});

export type ContentFile = {
  type: PostRunV1ChatCompletionsTypeFile;
  file: PostRunV1ChatCompletionsFile;
};

export const ContentFile$zodSchema: z.ZodType<ContentFile> = z.object({
  file: z.lazy(() => PostRunV1ChatCompletionsFile$zodSchema),
  type: PostRunV1ChatCompletionsTypeFile$zodSchema,
});

export const PostRunV1ChatCompletionsTypeImageURL = {
  ImageUrl: "image_url",
} as const;
export type PostRunV1ChatCompletionsTypeImageURL = ClosedEnum<
  typeof PostRunV1ChatCompletionsTypeImageURL
>;

export const PostRunV1ChatCompletionsTypeImageURL$zodSchema = z.enum([
  "image_url",
]);

export const PostRunV1ChatCompletionsDetailRequest = {
  Auto: "auto",
  Low: "low",
  High: "high",
} as const;
export type PostRunV1ChatCompletionsDetailRequest = ClosedEnum<
  typeof PostRunV1ChatCompletionsDetailRequest
>;

export const PostRunV1ChatCompletionsDetailRequest$zodSchema = z.enum([
  "auto",
  "low",
  "high",
]);

export type PostRunV1ChatCompletionsImageUrl = {
  url: string;
  detail?: PostRunV1ChatCompletionsDetailRequest | undefined;
};

export const PostRunV1ChatCompletionsImageUrl$zodSchema: z.ZodType<
  PostRunV1ChatCompletionsImageUrl
> = z.object({
  detail: PostRunV1ChatCompletionsDetailRequest$zodSchema.optional(),
  url: z.string(),
});

export type PostRunV1ChatCompletionsContentImageURL = {
  type: PostRunV1ChatCompletionsTypeImageURL;
  image_url: PostRunV1ChatCompletionsImageUrl;
};

export const PostRunV1ChatCompletionsContentImageURL$zodSchema: z.ZodType<
  PostRunV1ChatCompletionsContentImageURL
> = z.object({
  image_url: z.lazy(() => PostRunV1ChatCompletionsImageUrl$zodSchema),
  type: PostRunV1ChatCompletionsTypeImageURL$zodSchema,
});

export const PostRunV1ChatCompletionsTypeText = {
  Text: "text",
} as const;
export type PostRunV1ChatCompletionsTypeText = ClosedEnum<
  typeof PostRunV1ChatCompletionsTypeText
>;

export const PostRunV1ChatCompletionsTypeText$zodSchema = z.enum([
  "text",
]);

export type PostRunV1ChatCompletionsContentText = {
  type: PostRunV1ChatCompletionsTypeText;
  text: string;
};

export const PostRunV1ChatCompletionsContentText$zodSchema: z.ZodType<
  PostRunV1ChatCompletionsContentText
> = z.object({
  text: z.string(),
  type: PostRunV1ChatCompletionsTypeText$zodSchema,
});

export type PostRunV1ChatCompletionsContentUnion2 =
  | (PostRunV1ChatCompletionsContentText & { type: "text" })
  | (PostRunV1ChatCompletionsContentImageURL & { type: "image_url" })
  | (ContentFile & { type: "file" });

export const PostRunV1ChatCompletionsContentUnion2$zodSchema: z.ZodType<
  PostRunV1ChatCompletionsContentUnion2
> = z.union([
  z.lazy(() => PostRunV1ChatCompletionsContentText$zodSchema).and(
    z.object({
      type: z.literal("text"),
    }).transform((v) => ({ type: v.type })),
  ),
  z.lazy(() => PostRunV1ChatCompletionsContentImageURL$zodSchema).and(
    z.object({
      type: z.literal("image_url"),
    }).transform((v) => ({ type: v.type })),
  ),
  z.lazy(() => ContentFile$zodSchema).and(
    z.object({
      type: z.literal("file"),
    }).transform((v) => ({ type: v.type })),
  ),
]);

/**
 * The message content
 */
export type PostRunV1ChatCompletionsContentUnion1 =
  | string
  | Array<
    | (PostRunV1ChatCompletionsContentText & { type: "text" })
    | (PostRunV1ChatCompletionsContentImageURL & { type: "image_url" })
    | (ContentFile & { type: "file" })
  >;

export const PostRunV1ChatCompletionsContentUnion1$zodSchema: z.ZodType<
  PostRunV1ChatCompletionsContentUnion1
> = z.union([
  z.string(),
  z.array(z.union([
    z.lazy(() => PostRunV1ChatCompletionsContentText$zodSchema).and(
      z.object({
        type: z.literal("text"),
      }).transform((v) => ({ type: v.type })),
    ),
    z.lazy(() => PostRunV1ChatCompletionsContentImageURL$zodSchema).and(
      z.object({
        type: z.literal("image_url"),
      }).transform((v) => ({ type: v.type })),
    ),
    z.lazy(() => ContentFile$zodSchema).and(
      z.object({
        type: z.literal("file"),
      }).transform((v) => ({ type: v.type })),
    ),
  ])),
]).describe("The message content");

export type PostRunV1ChatCompletionsMessage = {
  role: PostRunV1ChatCompletionsRole;
  content:
    | string
    | Array<
      | (PostRunV1ChatCompletionsContentText & { type: "text" })
      | (PostRunV1ChatCompletionsContentImageURL & { type: "image_url" })
      | (ContentFile & { type: "file" })
    >;
  name?: string | undefined;
};

export const PostRunV1ChatCompletionsMessage$zodSchema: z.ZodType<
  PostRunV1ChatCompletionsMessage
> = z.object({
  content: z.union([
    z.string(),
    z.array(z.union([
      z.lazy(() => PostRunV1ChatCompletionsContentText$zodSchema).and(
        z.object({
          type: z.literal("text"),
        }).transform((v) => ({ type: v.type })),
      ),
      z.lazy(() => PostRunV1ChatCompletionsContentImageURL$zodSchema).and(
        z.object({
          type: z.literal("image_url"),
        }).transform((v) => ({ type: v.type })),
      ),
      z.lazy(() => ContentFile$zodSchema).and(
        z.object({
          type: z.literal("file"),
        }).transform((v) => ({ type: v.type })),
      ),
    ])),
  ]).describe("The message content"),
  name: z.string().optional().describe("The name of the message sender"),
  role: PostRunV1ChatCompletionsRole$zodSchema.describe(
    "The role of the message",
  ),
});

/**
 * Override the agent execution mode for this request. Takes precedence over the agent config default. Falls back to classic if unset.
 */
export const PostRunV1ChatCompletionsExecutionMode = {
  Classic: "classic",
  Durable: "durable",
} as const;
/**
 * Override the agent execution mode for this request. Takes precedence over the agent config default. Falls back to classic if unset.
 */
export type PostRunV1ChatCompletionsExecutionMode = ClosedEnum<
  typeof PostRunV1ChatCompletionsExecutionMode
>;

export const PostRunV1ChatCompletionsExecutionMode$zodSchema = z.enum([
  "classic",
  "durable",
]).describe(
  "Override the agent execution mode for this request. Takes precedence over the agent config default. Falls back to classic if unset.",
);

export type PostRunV1ChatCompletionsRequest = {
  model: string;
  messages: Array<PostRunV1ChatCompletionsMessage>;
  temperature?: number | undefined;
  top_p?: number | undefined;
  n?: number | undefined;
  stream?: boolean | undefined;
  max_tokens?: number | undefined;
  presence_penalty?: number | undefined;
  frequency_penalty?: number | undefined;
  logit_bias?: { [k: string]: number } | undefined;
  user?: string | undefined;
  conversationId?: string | undefined;
  tools?: Array<string> | undefined;
  runConfig?: { [k: string]: any | null } | undefined;
  executionMode?: PostRunV1ChatCompletionsExecutionMode | undefined;
  headers?: { [k: string]: any | null } | undefined;
  userProperties?: { [k: string]: any | null } | undefined;
};

export const PostRunV1ChatCompletionsRequest$zodSchema: z.ZodType<
  PostRunV1ChatCompletionsRequest
> = z.object({
  conversationId: z.string().optional().describe(
    "Conversation ID for multi-turn chat",
  ),
  executionMode: PostRunV1ChatCompletionsExecutionMode$zodSchema.optional()
    .describe(
      "Override the agent execution mode for this request. Takes precedence over the agent config default. Falls back to classic if unset.",
    ),
  frequency_penalty: z.number().optional().describe(
    "Frequency penalty (-2 to 2)",
  ),
  headers: z.record(z.string(), z.any().nullable()).optional().describe(
    "Headers data for template processing (validated against context config schema)",
  ),
  logit_bias: z.record(z.string(), z.number()).optional().describe(
    "Token logit bias",
  ),
  max_tokens: z.number().optional().describe("Maximum tokens to generate"),
  messages: z.array(z.lazy(() => PostRunV1ChatCompletionsMessage$zodSchema))
    .describe("The conversation messages"),
  model: z.string().describe("The model to use for the completion"),
  n: z.number().optional().describe("Number of completions to generate"),
  presence_penalty: z.number().optional().describe(
    "Presence penalty (-2 to 2)",
  ),
  runConfig: z.record(z.string(), z.any().nullable()).optional().describe(
    "Run configuration",
  ),
  stream: z.boolean().optional().describe("Whether to stream the response"),
  temperature: z.number().optional().describe("Controls randomness (0-1)"),
  tools: z.array(z.string()).optional().describe("Available tools"),
  top_p: z.number().optional().describe("Controls nucleus sampling"),
  user: z.string().optional().describe("User identifier"),
  userProperties: z.record(z.string(), z.any().nullable()).optional().describe(
    "User properties to associate with the conversation",
  ),
});

/**
 * Internal server error
 */
export type PostRunV1ChatCompletionsInternalServerErrorResponseBody = {
  error: string;
  message: string;
};

export const PostRunV1ChatCompletionsInternalServerErrorResponseBody$zodSchema:
  z.ZodType<PostRunV1ChatCompletionsInternalServerErrorResponseBody> = z.object(
    {
      error: z.string(),
      message: z.string(),
    },
  ).describe("Internal server error");

/**
 * Agent or agent not found
 */
export type PostRunV1ChatCompletionsNotFoundResponseBody = { error: string };

export const PostRunV1ChatCompletionsNotFoundResponseBody$zodSchema: z.ZodType<
  PostRunV1ChatCompletionsNotFoundResponseBody
> = z.object({
  error: z.string(),
}).describe("Agent or agent not found");

export type DetailResponse = {
  field: string;
  message: string;
  value?: any | null | undefined;
};

export const DetailResponse$zodSchema: z.ZodType<DetailResponse> = z.object({
  field: z.string(),
  message: z.string(),
  value: z.any().nullable().optional(),
});

/**
 * Invalid request context or parameters
 */
export type PostRunV1ChatCompletionsBadRequestResponseBody = {
  error: string;
  details?: Array<DetailResponse> | undefined;
};

export const PostRunV1ChatCompletionsBadRequestResponseBody$zodSchema:
  z.ZodType<PostRunV1ChatCompletionsBadRequestResponseBody> = z.object({
    details: z.array(z.lazy(() => DetailResponse$zodSchema)).optional(),
    error: z.string(),
  }).describe("Invalid request context or parameters");

export type PostRunV1ChatCompletionsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredTextEventStreamRes?: string | undefined;
  fourHundredApplicationJsonObject?:
    | PostRunV1ChatCompletionsBadRequestResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | PostRunV1ChatCompletionsNotFoundResponseBody
    | undefined;
  fiveHundredApplicationJsonObject?:
    | PostRunV1ChatCompletionsInternalServerErrorResponseBody
    | undefined;
  Headers: { [k: string]: Array<string> };
};

export const PostRunV1ChatCompletionsResponse$zodSchema: z.ZodType<
  PostRunV1ChatCompletionsResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  Headers: z.record(z.string(), z.array(z.string())).default({}),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fiveHundredApplicationJsonObject: z.lazy(() =>
    PostRunV1ChatCompletionsInternalServerErrorResponseBody$zodSchema
  ).optional().describe("Internal server error"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    PostRunV1ChatCompletionsNotFoundResponseBody$zodSchema
  ).optional().describe("Agent or agent not found"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    PostRunV1ChatCompletionsBadRequestResponseBody$zodSchema
  ).optional().describe("Invalid request context or parameters"),
  twoHundredTextEventStreamRes: z.string().describe(
    "Streaming chat completion response in Server-Sent Events format",
  ).optional(),
});
