/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1047252f9f7c
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export type PostRunApiExecutionsSecurity = { bearerAuth: string };

export const PostRunApiExecutionsSecurity$zodSchema: z.ZodType<
  PostRunApiExecutionsSecurity
> = z.object({
  bearerAuth: z.string().describe(
    "Bearer token authentication. Use this for API clients and service-to-service communication. Set the Authorization header to \"Bearer <token>\".",
  ),
});

export const PostRunApiExecutionsRole = {
  System: "system",
  User: "user",
  Assistant: "assistant",
  Function: "function",
  Tool: "tool",
} as const;
export type PostRunApiExecutionsRole = ClosedEnum<
  typeof PostRunApiExecutionsRole
>;

export const PostRunApiExecutionsRole$zodSchema = z.enum([
  "system",
  "user",
  "assistant",
  "function",
  "tool",
]);

export const PostRunApiExecutionsTypeImageURL = {
  ImageUrl: "image_url",
} as const;
export type PostRunApiExecutionsTypeImageURL = ClosedEnum<
  typeof PostRunApiExecutionsTypeImageURL
>;

export const PostRunApiExecutionsTypeImageURL$zodSchema = z.enum([
  "image_url",
]);

export const PostRunApiExecutionsDetail = {
  Auto: "auto",
  Low: "low",
  High: "high",
} as const;
export type PostRunApiExecutionsDetail = ClosedEnum<
  typeof PostRunApiExecutionsDetail
>;

export const PostRunApiExecutionsDetail$zodSchema = z.enum([
  "auto",
  "low",
  "high",
]);

export type PostRunApiExecutionsImageUrl = {
  url: string;
  detail?: PostRunApiExecutionsDetail | undefined;
};

export const PostRunApiExecutionsImageUrl$zodSchema: z.ZodType<
  PostRunApiExecutionsImageUrl
> = z.object({
  detail: PostRunApiExecutionsDetail$zodSchema.optional(),
  url: z.string(),
});

export type PostRunApiExecutionsContentImageURL = {
  type: PostRunApiExecutionsTypeImageURL;
  image_url: PostRunApiExecutionsImageUrl;
};

export const PostRunApiExecutionsContentImageURL$zodSchema: z.ZodType<
  PostRunApiExecutionsContentImageURL
> = z.object({
  image_url: z.lazy(() => PostRunApiExecutionsImageUrl$zodSchema),
  type: PostRunApiExecutionsTypeImageURL$zodSchema,
});

export const PostRunApiExecutionsTypeText = {
  Text: "text",
} as const;
export type PostRunApiExecutionsTypeText = ClosedEnum<
  typeof PostRunApiExecutionsTypeText
>;

export const PostRunApiExecutionsTypeText$zodSchema = z.enum([
  "text",
]);

export type PostRunApiExecutionsContentText = {
  type: PostRunApiExecutionsTypeText;
  text: string;
};

export const PostRunApiExecutionsContentText$zodSchema: z.ZodType<
  PostRunApiExecutionsContentText
> = z.object({
  text: z.string(),
  type: PostRunApiExecutionsTypeText$zodSchema,
});

export type PostRunApiExecutionsContentUnion2 =
  | (PostRunApiExecutionsContentText & { type: "text" })
  | (PostRunApiExecutionsContentImageURL & { type: "image_url" });

export const PostRunApiExecutionsContentUnion2$zodSchema: z.ZodType<
  PostRunApiExecutionsContentUnion2
> = z.union([
  z.lazy(() => PostRunApiExecutionsContentText$zodSchema).and(
    z.object({
      type: z.literal("text"),
    }).transform((v) => ({ type: v.type })),
  ),
  z.lazy(() => PostRunApiExecutionsContentImageURL$zodSchema).and(
    z.object({
      type: z.literal("image_url"),
    }).transform((v) => ({ type: v.type })),
  ),
]);

/**
 * The message content
 */
export type PostRunApiExecutionsContentUnion1 =
  | string
  | Array<
    | (PostRunApiExecutionsContentText & { type: "text" })
    | (PostRunApiExecutionsContentImageURL & { type: "image_url" })
  >;

export const PostRunApiExecutionsContentUnion1$zodSchema: z.ZodType<
  PostRunApiExecutionsContentUnion1
> = z.union([
  z.string(),
  z.array(z.union([
    z.lazy(() => PostRunApiExecutionsContentText$zodSchema).and(
      z.object({
        type: z.literal("text"),
      }).transform((v) => ({ type: v.type })),
    ),
    z.lazy(() => PostRunApiExecutionsContentImageURL$zodSchema).and(
      z.object({
        type: z.literal("image_url"),
      }).transform((v) => ({ type: v.type })),
    ),
  ])),
]).describe("The message content");

export type PostRunApiExecutionsMessage = {
  role: PostRunApiExecutionsRole;
  content:
    | string
    | Array<
      | (PostRunApiExecutionsContentText & { type: "text" })
      | (PostRunApiExecutionsContentImageURL & { type: "image_url" })
    >;
};

export const PostRunApiExecutionsMessage$zodSchema: z.ZodType<
  PostRunApiExecutionsMessage
> = z.object({
  content: z.union([
    z.string(),
    z.array(z.union([
      z.lazy(() => PostRunApiExecutionsContentText$zodSchema).and(
        z.object({
          type: z.literal("text"),
        }).transform((v) => ({ type: v.type })),
      ),
      z.lazy(() => PostRunApiExecutionsContentImageURL$zodSchema).and(
        z.object({
          type: z.literal("image_url"),
        }).transform((v) => ({ type: v.type })),
      ),
    ])),
  ]).describe("The message content"),
  role: PostRunApiExecutionsRole$zodSchema,
});

export type PostRunApiExecutionsRequest = {
  messages: Array<PostRunApiExecutionsMessage>;
  conversationId?: string | undefined;
  forwardedHeaders?: { [k: string]: string } | undefined;
};

export const PostRunApiExecutionsRequest$zodSchema: z.ZodType<
  PostRunApiExecutionsRequest
> = z.object({
  conversationId: z.string().optional(),
  forwardedHeaders: z.record(z.string(), z.string()).optional(),
  messages: z.array(z.lazy(() => PostRunApiExecutionsMessage$zodSchema))
    .describe("The conversation messages"),
});

/**
 * Agent not found
 */
export type PostRunApiExecutionsNotFoundResponseBody = { error: string };

export const PostRunApiExecutionsNotFoundResponseBody$zodSchema: z.ZodType<
  PostRunApiExecutionsNotFoundResponseBody
> = z.object({
  error: z.string(),
}).describe("Agent not found");

/**
 * Invalid request
 */
export type PostRunApiExecutionsBadRequestResponseBody = { error: string };

export const PostRunApiExecutionsBadRequestResponseBody$zodSchema: z.ZodType<
  PostRunApiExecutionsBadRequestResponseBody
> = z.object({
  error: z.string(),
}).describe("Invalid request");

export type PostRunApiExecutionsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredTextEventStreamRes?: string | undefined;
  fourHundredApplicationJsonObject?:
    | PostRunApiExecutionsBadRequestResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | PostRunApiExecutionsNotFoundResponseBody
    | undefined;
  Headers: { [k: string]: Array<string> };
};

export const PostRunApiExecutionsResponse$zodSchema: z.ZodType<
  PostRunApiExecutionsResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  Headers: z.record(z.string(), z.array(z.string())).default({}),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    PostRunApiExecutionsNotFoundResponseBody$zodSchema
  ).optional().describe("Agent not found"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    PostRunApiExecutionsBadRequestResponseBody$zodSchema
  ).optional().describe("Invalid request"),
  twoHundredTextEventStreamRes: z.string().describe(
    "Streaming SSE response. The x-workflow-run-id header contains the run ID for reconnection.",
  ).optional(),
});
