/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: aebb452d158e
 */

import * as z from "zod";
import {
  ReadyErrorChecks,
  ReadyErrorChecks$zodSchema,
} from "./readyerrorchecks.js";

export type ReadyErrorResponse = {
  type: string;
  title: string;
  status: number;
  detail: string;
  checks: ReadyErrorChecks;
};

export const ReadyErrorResponse$zodSchema: z.ZodType<ReadyErrorResponse> = z
  .object({
    checks: ReadyErrorChecks$zodSchema,
    detail: z.string().describe(
      "A human-readable explanation specific to this occurrence",
    ),
    status: z.number().describe("The HTTP status code"),
    title: z.string().describe(
      "A short, human-readable summary of the problem type",
    ),
    type: z.string().describe(
      "A URI reference that identifies the problem type",
    ),
  });
