/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b6fa280bff45
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Part, Part$zodSchema } from "./part.js";
import {
  TriggerIsDisabled,
  TriggerIsDisabled$zodSchema,
} from "./triggerisdisabled.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type RerunTriggerRequestBody = {
  userMessage: string;
  messageParts?: Array<Part> | undefined;
};

export const RerunTriggerRequestBody$zodSchema: z.ZodType<
  RerunTriggerRequestBody
> = z.object({
  messageParts: z.array(Part$zodSchema).optional().describe(
    "Optional structured message parts (from original trace)",
  ),
  userMessage: z.string().describe("The user message to send to the agent"),
});

export type RerunTriggerRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
  id: string;
  body?: RerunTriggerRequestBody | undefined;
};

export const RerunTriggerRequest$zodSchema: z.ZodType<RerunTriggerRequest> = z
  .object({
    agentId: z.string().describe("Agent identifier"),
    body: z.lazy(() => RerunTriggerRequestBody$zodSchema).optional(),
    id: z.string().describe("Resource identifier"),
    projectId: z.string().describe("Project identifier"),
    tenantId: z.string().describe("Tenant identifier"),
  });

/**
 * Trigger rerun accepted and dispatched
 */
export type RerunTriggerResponseBody = {
  success: boolean;
  invocationId: string;
  conversationId: string;
};

export const RerunTriggerResponseBody$zodSchema: z.ZodType<
  RerunTriggerResponseBody
> = z.object({
  conversationId: z.string(),
  invocationId: z.string(),
  success: z.boolean(),
}).describe("Trigger rerun accepted and dispatched");

export type RerunTriggerResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: RerunTriggerResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  TriggerIsDisabled?: TriggerIsDisabled | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const RerunTriggerResponse$zodSchema: z.ZodType<RerunTriggerResponse> = z
  .object({
    BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
    ContentType: z.string().describe(
      "HTTP response content type for this operation",
    ),
    Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
    InternalServerError: InternalServerError$zodSchema.optional().describe(
      "Internal Server Error",
    ),
    NotFound: NotFound$zodSchema.optional().describe("Not Found"),
    RawResponse: z.custom<Response>(x => x instanceof Response).describe(
      "Raw HTTP response; suitable for custom response parsing",
    ),
    StatusCode: z.int().describe(
      "HTTP response status code for this operation",
    ),
    TriggerIsDisabled: TriggerIsDisabled$zodSchema.optional().describe(
      "Trigger is disabled",
    ),
    Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
    UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
      "Unprocessable Entity",
    ),
    object: z.lazy(() => RerunTriggerResponseBody$zodSchema).optional()
      .describe("Trigger rerun accepted and dispatched"),
  });
