/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1477f9609de4
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { LastRunSummary, LastRunSummary$zodSchema } from "./lastrunsummary.js";

/**
 * Status of the last run
 */
export const LastRunStatus = {
  Completed: "completed",
  Failed: "failed",
} as const;
/**
 * Status of the last run
 */
export type LastRunStatus = ClosedEnum<typeof LastRunStatus>;

export const LastRunStatus$zodSchema = z.enum([
  "completed",
  "failed",
]).describe("Status of the last run");

export type ScheduledTriggerWithRunInfo = {
  id: string;
  name: string;
  description: string | null;
  enabled: boolean;
  cronExpression: string | null;
  cronTimezone: string | null;
  runAt: string | null;
  payload?: { [k: string]: any | null } | null | undefined;
  messageTemplate: string | null;
  maxRetries: number;
  retryDelaySeconds: number;
  timeoutSeconds: number;
  runAsUserId: string | null;
  createdBy: string | null;
  nextRunAt: string | null;
  ref: string;
  dispatchDelayMs: number | null;
  createdAt: string;
  updatedAt: string;
  lastRunAt: string | null;
  lastRunStatus: LastRunStatus | null;
  lastRunConversationIds: Array<string>;
  runAsUserIds: Array<string>;
  userCount: number;
  lastRunSummary: LastRunSummary | null;
};

export const ScheduledTriggerWithRunInfo$zodSchema: z.ZodType<
  ScheduledTriggerWithRunInfo
> = z.object({
  createdAt: z.string(),
  createdBy: z.string().nullable(),
  cronExpression: z.string().nullable(),
  cronTimezone: z.string().nullable(),
  description: z.string().nullable(),
  dispatchDelayMs: z.int().nullable(),
  enabled: z.boolean(),
  id: z.string(),
  lastRunAt: z.iso.datetime({ offset: true }).nullable().describe(
    "Timestamp of the last completed or failed run",
  ),
  lastRunConversationIds: z.array(z.string()).describe(
    "Conversation IDs from the last run",
  ),
  lastRunStatus: LastRunStatus$zodSchema.nullable().describe(
    "Status of the last run",
  ),
  lastRunSummary: LastRunSummary$zodSchema.nullable().describe(
    "Per-status counts for the most recent scheduled tick",
  ),
  maxRetries: z.int(),
  messageTemplate: z.string().nullable(),
  name: z.string(),
  nextRunAt: z.iso.datetime({ offset: true }).nullable().describe(
    "Timestamp of the next pending run",
  ),
  payload: z.record(z.string(), z.any().nullable()).nullable().optional(),
  ref: z.string(),
  retryDelaySeconds: z.int(),
  runAsUserId: z.string().nullable(),
  runAsUserIds: z.array(z.string()).describe(
    "User IDs associated with this trigger",
  ),
  runAt: z.string().nullable(),
  timeoutSeconds: z.int(),
  updatedAt: z.string(),
  userCount: z.int().describe("Number of associated users"),
});
