/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 93c7ec7c5e40
 */

import * as z from "zod";
import { Pagination, Pagination$zodSchema } from "./pagination.js";
import {
  ScheduledTriggerInvocation,
  ScheduledTriggerInvocation$zodSchema,
} from "./scheduledtriggerinvocation.js";

export type ScheduledTriggerInvocationListResponse = {
  data: Array<ScheduledTriggerInvocation>;
  pagination: Pagination;
};

export const ScheduledTriggerInvocationListResponse$zodSchema: z.ZodType<
  ScheduledTriggerInvocationListResponse
> = z.object({
  data: z.array(ScheduledTriggerInvocation$zodSchema),
  pagination: Pagination$zodSchema,
});
