/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1477f9609de4
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Status of the last run
 */
export const LastRunStatus = {
  Completed: "completed",
  Failed: "failed",
} as const;
/**
 * Status of the last run
 */
export type LastRunStatus = ClosedEnum<typeof LastRunStatus>;

export const LastRunStatus$zodSchema = z.enum([
  "completed",
  "failed",
]).describe("Status of the last run");

export type ScheduledTriggerWithRunInfo = {
  id: string;
  name: string;
  description: string | null;
  enabled: boolean;
  cronExpression: string | null;
  cronTimezone: string | null;
  runAt: string | null;
  payload?: { [k: string]: any | null } | null | undefined;
  messageTemplate: string | null;
  maxRetries: number;
  retryDelaySeconds: number;
  timeoutSeconds: number;
  createdAt: string;
  updatedAt: string;
  lastRunAt: string | null;
  lastRunStatus: LastRunStatus | null;
  lastRunConversationIds: Array<string>;
  nextRunAt: string | null;
};

export const ScheduledTriggerWithRunInfo$zodSchema: z.ZodType<
  ScheduledTriggerWithRunInfo
> = z.object({
  createdAt: z.string(),
  cronExpression: z.string().nullable(),
  cronTimezone: z.string().nullable(),
  description: z.string().nullable(),
  enabled: z.boolean(),
  id: z.string(),
  lastRunAt: z.iso.datetime({ offset: true }).nullable(),
  lastRunConversationIds: z.array(z.string()),
  lastRunStatus: LastRunStatus$zodSchema.nullable(),
  maxRetries: z.number(),
  messageTemplate: z.string().nullable(),
  name: z.string(),
  nextRunAt: z.iso.datetime({ offset: true }).nullable(),
  payload: z.record(z.string(), z.any().nullable()).nullable().optional(),
  retryDelaySeconds: z.number(),
  runAt: z.string().nullable(),
  timeoutSeconds: z.number(),
  updatedAt: z.string(),
});
