/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 59ebdf3eb5ac
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

/**
 * Channel access mode: "all" means the MCP tool can post to any channel, "selected" means the tool is scoped to specific channels
 */
export const ChannelAccessModeRequest = {
  All: "all",
  Selected: "selected",
} as const;
/**
 * Channel access mode: "all" means the MCP tool can post to any channel, "selected" means the tool is scoped to specific channels
 */
export type ChannelAccessModeRequest = ClosedEnum<
  typeof ChannelAccessModeRequest
>;

export const ChannelAccessModeRequest$zodSchema = z.enum([
  "all",
  "selected",
]).describe(
  "Channel access mode: \"all\" means the MCP tool can post to any channel, \"selected\" means the tool is scoped to specific channels",
);

export type SetMcpToolSlackAccessRequestBody = {
  channelAccessMode: ChannelAccessModeRequest;
  dmEnabled: boolean;
  channelIds?: Array<string> | undefined;
};

export const SetMcpToolSlackAccessRequestBody$zodSchema: z.ZodType<
  SetMcpToolSlackAccessRequestBody
> = z.object({
  channelAccessMode: ChannelAccessModeRequest$zodSchema.describe(
    "Channel access mode: \"all\" means the MCP tool can post to any channel, \"selected\" means the tool is scoped to specific channels",
  ),
  channelIds: z.array(z.string()).optional().describe(
    "List of allowed channel IDs (only used when channelAccessMode is \"selected\")",
  ),
  dmEnabled: z.boolean().describe("Whether DM access is enabled for this tool"),
});

export type SetMcpToolSlackAccessRequest = {
  tenantId: string;
  projectId: string;
  toolId: string;
  body?: SetMcpToolSlackAccessRequestBody | undefined;
};

export const SetMcpToolSlackAccessRequest$zodSchema: z.ZodType<
  SetMcpToolSlackAccessRequest
> = z.object({
  body: z.lazy(() => SetMcpToolSlackAccessRequestBody$zodSchema).optional(),
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
  toolId: z.string().describe("The tool ID"),
});

/**
 * Channel access mode: "all" means the MCP tool can post to any channel, "selected" means the tool is scoped to specific channels
 */
export const SetMcpToolSlackAccessChannelAccessModeResponse = {
  All: "all",
  Selected: "selected",
} as const;
/**
 * Channel access mode: "all" means the MCP tool can post to any channel, "selected" means the tool is scoped to specific channels
 */
export type SetMcpToolSlackAccessChannelAccessModeResponse = ClosedEnum<
  typeof SetMcpToolSlackAccessChannelAccessModeResponse
>;

export const SetMcpToolSlackAccessChannelAccessModeResponse$zodSchema = z.enum([
  "all",
  "selected",
]).describe(
  "Channel access mode: \"all\" means the MCP tool can post to any channel, \"selected\" means the tool is scoped to specific channels",
);

/**
 * Slack access configuration updated successfully
 */
export type SetMcpToolSlackAccessResponseBody = {
  channelAccessMode: SetMcpToolSlackAccessChannelAccessModeResponse;
  dmEnabled: boolean;
  channelIds?: Array<string> | undefined;
};

export const SetMcpToolSlackAccessResponseBody$zodSchema: z.ZodType<
  SetMcpToolSlackAccessResponseBody
> = z.object({
  channelAccessMode: SetMcpToolSlackAccessChannelAccessModeResponse$zodSchema
    .describe(
      "Channel access mode: \"all\" means the MCP tool can post to any channel, \"selected\" means the tool is scoped to specific channels",
    ),
  channelIds: z.array(z.string()).optional().describe(
    "List of allowed channel IDs (only used when channelAccessMode is \"selected\")",
  ),
  dmEnabled: z.boolean().describe("Whether DM access is enabled for this tool"),
}).describe("Slack access configuration updated successfully");

export type SetMcpToolSlackAccessResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: SetMcpToolSlackAccessResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const SetMcpToolSlackAccessResponse$zodSchema: z.ZodType<
  SetMcpToolSlackAccessResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
  InternalServerError: InternalServerError$zodSchema.optional().describe(
    "Internal Server Error",
  ),
  NotFound: NotFound$zodSchema.optional().describe("Not Found"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
    "Unprocessable Entity",
  ),
  object: z.lazy(() => SetMcpToolSlackAccessResponseBody$zodSchema).optional()
    .describe("Slack access configuration updated successfully"),
});
