/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d9a0287530ed
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

/**
 * Access mode: "all" means project has access to all tenant repositories, "selected" means project is scoped to specific repositories
 */
export const SetProjectGithubAccessModeRequest = {
  All: "all",
  Selected: "selected",
} as const;
/**
 * Access mode: "all" means project has access to all tenant repositories, "selected" means project is scoped to specific repositories
 */
export type SetProjectGithubAccessModeRequest = ClosedEnum<
  typeof SetProjectGithubAccessModeRequest
>;

export const SetProjectGithubAccessModeRequest$zodSchema = z.enum([
  "all",
  "selected",
]).describe(
  "Access mode: \"all\" means project has access to all tenant repositories, \"selected\" means project is scoped to specific repositories",
);

export type SetProjectGithubAccessRequestBody = {
  mode: SetProjectGithubAccessModeRequest;
  repositoryIds?: Array<string> | undefined;
};

export const SetProjectGithubAccessRequestBody$zodSchema: z.ZodType<
  SetProjectGithubAccessRequestBody
> = z.object({
  mode: SetProjectGithubAccessModeRequest$zodSchema,
  repositoryIds: z.array(z.string()).optional(),
});

export type SetProjectGithubAccessRequest = {
  tenantId: string;
  projectId: string;
  body?: SetProjectGithubAccessRequestBody | undefined;
};

export const SetProjectGithubAccessRequest$zodSchema: z.ZodType<
  SetProjectGithubAccessRequest
> = z.object({
  body: z.lazy(() => SetProjectGithubAccessRequestBody$zodSchema).optional(),
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

/**
 * Access mode: "all" means project has access to all tenant repositories, "selected" means project is scoped to specific repositories
 */
export const SetProjectGithubAccessModeResponse = {
  All: "all",
  Selected: "selected",
} as const;
/**
 * Access mode: "all" means project has access to all tenant repositories, "selected" means project is scoped to specific repositories
 */
export type SetProjectGithubAccessModeResponse = ClosedEnum<
  typeof SetProjectGithubAccessModeResponse
>;

export const SetProjectGithubAccessModeResponse$zodSchema = z.enum([
  "all",
  "selected",
]).describe(
  "Access mode: \"all\" means project has access to all tenant repositories, \"selected\" means project is scoped to specific repositories",
);

/**
 * GitHub access configuration updated successfully
 */
export type SetProjectGithubAccessResponseBody = {
  mode: SetProjectGithubAccessModeResponse;
  repositoryCount: number;
};

export const SetProjectGithubAccessResponseBody$zodSchema: z.ZodType<
  SetProjectGithubAccessResponseBody
> = z.object({
  mode: SetProjectGithubAccessModeResponse$zodSchema,
  repositoryCount: z.number(),
}).describe("GitHub access configuration updated successfully");

export type SetProjectGithubAccessResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: SetProjectGithubAccessResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const SetProjectGithubAccessResponse$zodSchema: z.ZodType<
  SetProjectGithubAccessResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
  object: z.lazy(() => SetProjectGithubAccessResponseBody$zodSchema).optional(),
});
