/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d83ff0039102
 */

import * as z from "zod";

export type SkillCreate = {
  name: string;
  description: string;
  content: string;
  metadata?: { [k: string]: string } | null | undefined;
};

export const SkillCreate$zodSchema: z.ZodType<SkillCreate> = z.object({
  content: z.string(),
  description: z.string(),
  metadata: z.record(z.string(), z.string()).nullable().optional(),
  name: z.string(),
});
