/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1d816d8db881
 */

import * as z from "zod";
import { SkillFile, SkillFile$zodSchema } from "./skillfile.js";

export type SkillWithFiles = {
  id: string;
  name: string;
  description: string;
  content: string;
  metadata: { [k: string]: string } | null;
  createdAt: string;
  updatedAt: string;
  files: Array<SkillFile>;
};

export const SkillWithFiles$zodSchema: z.ZodType<SkillWithFiles> = z.object({
  content: z.string(),
  createdAt: z.string(),
  description: z.string(),
  files: z.array(SkillFile$zodSchema),
  id: z.string(),
  metadata: z.record(z.string(), z.string()).nullable(),
  name: z.string(),
  updatedAt: z.string(),
});
