/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8daede63c493
 */

import * as z from "zod";

export type SlackUpdateJoinFromWorkspaceRequestBody = {
  shouldAllowJoinFromWorkspace: boolean;
};

export const SlackUpdateJoinFromWorkspaceRequestBody$zodSchema: z.ZodType<
  SlackUpdateJoinFromWorkspaceRequestBody
> = z.object({
  shouldAllowJoinFromWorkspace: z.boolean(),
});

export type SlackUpdateJoinFromWorkspaceRequest = {
  teamId: string;
  body?: SlackUpdateJoinFromWorkspaceRequestBody | undefined;
};

export const SlackUpdateJoinFromWorkspaceRequest$zodSchema: z.ZodType<
  SlackUpdateJoinFromWorkspaceRequest
> = z.object({
  body: z.lazy(() => SlackUpdateJoinFromWorkspaceRequestBody$zodSchema)
    .optional(),
  teamId: z.string(),
});

/**
 * Join from workspace setting updated
 */
export type SlackUpdateJoinFromWorkspaceResponseBody = { success: boolean };

export const SlackUpdateJoinFromWorkspaceResponseBody$zodSchema: z.ZodType<
  SlackUpdateJoinFromWorkspaceResponseBody
> = z.object({
  success: z.boolean(),
}).describe("Join from workspace setting updated");

export type SlackUpdateJoinFromWorkspaceResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: SlackUpdateJoinFromWorkspaceResponseBody | undefined;
};

export const SlackUpdateJoinFromWorkspaceResponse$zodSchema: z.ZodType<
  SlackUpdateJoinFromWorkspaceResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  object: z.lazy(() => SlackUpdateJoinFromWorkspaceResponseBody$zodSchema)
    .optional(),
});
