/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4daa60a40833
 */

import * as z from "zod";

export type SlackOauthRedirectRequest = {
  code?: string | undefined;
  error?: string | undefined;
  state?: string | undefined;
};

export const SlackOauthRedirectRequest$zodSchema: z.ZodType<
  SlackOauthRedirectRequest
> = z.object({
  code: z.string().optional(),
  error: z.string().optional(),
  state: z.string().optional(),
});

export type SlackOauthRedirectResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
};

export const SlackOauthRedirectResponse$zodSchema: z.ZodType<
  SlackOauthRedirectResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
});
