/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: aa91d2373f2e
 */

import * as z from "zod";

export type SlackGetJoinFromWorkspaceRequest = { teamId: string };

export const SlackGetJoinFromWorkspaceRequest$zodSchema: z.ZodType<
  SlackGetJoinFromWorkspaceRequest
> = z.object({
  teamId: z.string(),
});

/**
 * Join from workspace setting
 */
export type SlackGetJoinFromWorkspaceResponseBody = {
  shouldAllowJoinFromWorkspace: boolean;
};

export const SlackGetJoinFromWorkspaceResponseBody$zodSchema: z.ZodType<
  SlackGetJoinFromWorkspaceResponseBody
> = z.object({
  shouldAllowJoinFromWorkspace: z.boolean(),
}).describe("Join from workspace setting");

export type SlackGetJoinFromWorkspaceResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: SlackGetJoinFromWorkspaceResponseBody | undefined;
};

export const SlackGetJoinFromWorkspaceResponse$zodSchema: z.ZodType<
  SlackGetJoinFromWorkspaceResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  object: z.lazy(() => SlackGetJoinFromWorkspaceResponseBody$zodSchema)
    .optional().describe("Join from workspace setting"),
});
