/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bfd61830dd70
 */

import * as z from "zod";

export type SlackUserConnectRequest = {
  userId: string;
  userEmail?: string | undefined;
  userName?: string | undefined;
  tenantId?: string | undefined;
};

export const SlackUserConnectRequest$zodSchema: z.ZodType<
  SlackUserConnectRequest
> = z.object({
  tenantId: z.string().optional().describe("Tenant ID"),
  userEmail: z.string().optional().describe("User email"),
  userId: z.string().describe("Inkeep user ID"),
  userName: z.string().optional().describe("User display name"),
});

/**
 * Connect session created
 */
export type SlackUserConnectResponseBody = {
  sessionToken?: string | undefined;
  connectUrl?: string | undefined;
};

export const SlackUserConnectResponseBody$zodSchema: z.ZodType<
  SlackUserConnectResponseBody
> = z.object({
  connectUrl: z.string().optional(),
  sessionToken: z.string().optional(),
}).describe("Connect session created");

export type SlackUserConnectResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: SlackUserConnectResponseBody | undefined;
};

export const SlackUserConnectResponse$zodSchema: z.ZodType<
  SlackUserConnectResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  object: z.lazy(() => SlackUserConnectResponseBody$zodSchema).optional()
    .describe("Connect session created"),
});
