/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 13a6909d20ab
 */

import * as z from "zod";

export type SlackVerifyLinkTokenRequest = {
  token: string;
  userId: string;
  userEmail?: string | undefined;
};

export const SlackVerifyLinkTokenRequest$zodSchema: z.ZodType<
  SlackVerifyLinkTokenRequest
> = z.object({
  token: z.string(),
  userEmail: z.string().optional(),
  userId: z.string(),
});

/**
 * Link successful
 */
export type SlackVerifyLinkTokenResponseBody = {
  success: boolean;
  linkId?: string | undefined;
  slackUsername?: string | undefined;
  slackTeamId?: string | undefined;
  tenantId?: string | undefined;
};

export const SlackVerifyLinkTokenResponseBody$zodSchema: z.ZodType<
  SlackVerifyLinkTokenResponseBody
> = z.object({
  linkId: z.string().optional(),
  slackTeamId: z.string().optional(),
  slackUsername: z.string().optional(),
  success: z.boolean(),
  tenantId: z.string().optional(),
}).describe("Link successful");

export type SlackVerifyLinkTokenResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: SlackVerifyLinkTokenResponseBody | undefined;
};

export const SlackVerifyLinkTokenResponse$zodSchema: z.ZodType<
  SlackVerifyLinkTokenResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  object: z.lazy(() => SlackVerifyLinkTokenResponseBody$zodSchema).optional()
    .describe("Link successful"),
});
