/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2e8b8be275cf
 */

import * as z from "zod";

export type SlackListChannelsRequest = {
  teamId: string;
  limit?: number | null | undefined;
  cursor?: string | undefined;
  types?: string | undefined;
};

export const SlackListChannelsRequest$zodSchema: z.ZodType<
  SlackListChannelsRequest
> = z.object({
  cursor: z.string().optional(),
  limit: z.number().default(100).nullable(),
  teamId: z.string(),
  types: z.string().optional(),
});

export type SlackListChannelsAgentConfig = {
  projectId: string;
  agentId: string;
  grantAccessToMembers?: boolean | undefined;
};

export const SlackListChannelsAgentConfig$zodSchema: z.ZodType<
  SlackListChannelsAgentConfig
> = z.object({
  agentId: z.string(),
  grantAccessToMembers: z.boolean().optional(),
  projectId: z.string(),
});

export type Channel = {
  id: string;
  name: string;
  isPrivate: boolean;
  isShared: boolean;
  memberCount?: number | undefined;
  hasAgentConfig: boolean;
  agentConfig?: SlackListChannelsAgentConfig | undefined;
};

export const Channel$zodSchema: z.ZodType<Channel> = z.object({
  agentConfig: z.lazy(() => SlackListChannelsAgentConfig$zodSchema).optional(),
  hasAgentConfig: z.boolean(),
  id: z.string(),
  isPrivate: z.boolean(),
  isShared: z.boolean(),
  memberCount: z.number().optional(),
  name: z.string(),
});

/**
 * List of channels
 */
export type SlackListChannelsResponseBody = {
  channels: Array<Channel>;
  nextCursor?: string | undefined;
};

export const SlackListChannelsResponseBody$zodSchema: z.ZodType<
  SlackListChannelsResponseBody
> = z.object({
  channels: z.array(z.lazy(() => Channel$zodSchema)),
  nextCursor: z.string().optional(),
}).describe("List of channels");

export type SlackListChannelsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: SlackListChannelsResponseBody | undefined;
};

export const SlackListChannelsResponse$zodSchema: z.ZodType<
  SlackListChannelsResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  object: z.lazy(() => SlackListChannelsResponseBody$zodSchema).optional()
    .describe("List of channels"),
});
