/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4ed971751dd0
 */

import * as z from "zod";

export type StopWhen = {
  transferCountIs?: number | undefined;
  stepCountIs?: number | undefined;
};

export const StopWhen$zodSchema: z.ZodType<StopWhen> = z.object({
  stepCountIs: z.number().optional(),
  transferCountIs: z.number().optional(),
});
