/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7770741c4eda
 */

import * as z from "zod";
import {
  SubAgentTeamAgentRelation,
  SubAgentTeamAgentRelation$zodSchema,
} from "./subagentteamagentrelation.js";

export type SubAgentTeamAgentRelationResponse = {
  data: SubAgentTeamAgentRelation;
};

export const SubAgentTeamAgentRelationResponse$zodSchema: z.ZodType<
  SubAgentTeamAgentRelationResponse
> = z.object({
  data: SubAgentTeamAgentRelation$zodSchema,
});
