/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f6a2e79f3ad9
 */

import * as z from "zod";

export type SubAgentTeamAgentRelationUpdate = {
  id?: string | undefined;
  subAgentId?: string | undefined;
  targetAgentId?: string | undefined;
  headers?: { [k: string]: string } | null | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
};

export const SubAgentTeamAgentRelationUpdate$zodSchema: z.ZodType<
  SubAgentTeamAgentRelationUpdate
> = z.object({
  createdAt: z.string().optional(),
  headers: z.record(z.string(), z.string()).nullable().optional(),
  id: z.string().optional(),
  subAgentId: z.string().optional(),
  targetAgentId: z.string().optional(),
  updatedAt: z.string().optional(),
});
