/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 94b8cfc18d1b
 */

import * as z from "zod";
import {
  SubAgentSkillWithIndex,
  SubAgentSkillWithIndex$zodSchema,
} from "./subagentskillwithindex.js";

export type SubAgentSkillWithIndexArrayResponse = {
  data: Array<SubAgentSkillWithIndex>;
};

export const SubAgentSkillWithIndexArrayResponse$zodSchema: z.ZodType<
  SubAgentSkillWithIndexArrayResponse
> = z.object({
  data: z.array(SubAgentSkillWithIndex$zodSchema),
});
