/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 593ccefd13af
 */

import * as z from "zod";
import {
  SubAgentFunctionToolRelation,
  SubAgentFunctionToolRelation$zodSchema,
} from "./subagentfunctiontoolrelation.js";

export type SubAgentFunctionToolRelationResponse = {
  data: SubAgentFunctionToolRelation;
};

export const SubAgentFunctionToolRelationResponse$zodSchema: z.ZodType<
  SubAgentFunctionToolRelationResponse
> = z.object({
  data: SubAgentFunctionToolRelation$zodSchema,
});
