/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 41dd3e237e0d
 */

import * as z from "zod";

export type SubAgentSkillWithIndex = {
  id: string;
  name: string;
  description: string;
  content: string;
  metadata: { [k: string]: string } | null;
  createdAt: string;
  updatedAt: string;
  subAgentSkillId: string;
  subAgentId: string;
  index: number;
  alwaysLoaded: boolean;
};

export const SubAgentSkillWithIndex$zodSchema: z.ZodType<
  SubAgentSkillWithIndex
> = z.object({
  alwaysLoaded: z.boolean(),
  content: z.string(),
  createdAt: z.string(),
  description: z.string(),
  id: z.string(),
  index: z.int(),
  metadata: z.record(z.string(), z.string()).nullable(),
  name: z.string(),
  subAgentId: z.string(),
  subAgentSkillId: z.string(),
  updatedAt: z.string(),
});
