/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SubAgentExternalAgentRelation = {
  id: string;
  subAgentId: string;
  externalAgentId: string;
  headers?: any | null | undefined;
  createdAt: string;
  updatedAt: string;
};

export const SubAgentExternalAgentRelation$zodSchema: z.ZodType<
  SubAgentExternalAgentRelation,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  externalAgentId: z.string(),
  headers: z.any().nullable().optional(),
  id: z.string(),
  subAgentId: z.string(),
  updatedAt: z.string(),
});
