/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 65aec1eddd00
 */

import * as z from "zod";

export type Tool = {
  id: string;
  name: string;
  description: string | null;
  config?: any | null | undefined;
  credentialReferenceId: string | null;
  credentialScope: string;
  headers?: any | null | undefined;
  imageUrl: string | null;
  capabilities?: any | null | undefined;
  lastError: string | null;
  isWorkApp: boolean;
  createdAt: string;
  updatedAt: string;
};

export const Tool$zodSchema: z.ZodType<Tool> = z.object({
  capabilities: z.any().nullable().optional(),
  config: z.any().nullable().optional(),
  createdAt: z.string(),
  credentialReferenceId: z.string().nullable(),
  credentialScope: z.string(),
  description: z.string().nullable(),
  headers: z.any().nullable().optional(),
  id: z.string(),
  imageUrl: z.string().nullable(),
  isWorkApp: z.boolean(),
  lastError: z.string().nullable(),
  name: z.string(),
  updatedAt: z.string(),
});
