/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ToolCreateTypeMcp = {
  Mcp: "mcp",
} as const;
export type ToolCreateTypeMcp = ClosedEnum<typeof ToolCreateTypeMcp>;

export const ToolCreateTypeMcp$zodSchema = z.enum([
  "mcp",
]);

export type ToolCreateServer = { url: string };

export const ToolCreateServer$zodSchema: z.ZodType<ToolCreateServer> = z.object(
  {
    url: z.string(),
  },
);

export const ToolCreateTransportType = {
  StreamableHttp: "streamable_http",
  Sse: "sse",
} as const;
export type ToolCreateTransportType = ClosedEnum<
  typeof ToolCreateTransportType
>;

export const ToolCreateTransportType$zodSchema = z.enum([
  "streamable_http",
  "sse",
]);

/**
 * Reconnection options for streamable HTTP transport
 */
export type ToolCreateReconnectionOptions = {};

export const ToolCreateReconnectionOptions$zodSchema: z.ZodType<
  ToolCreateReconnectionOptions
> = z.object({}).describe("Reconnection options for streamable HTTP transport");

export type ToolCreateTransport = {
  type: ToolCreateTransportType;
  requestInit?: { [k: string]: any | null } | undefined;
  eventSourceInit?: { [k: string]: any | null } | undefined;
  reconnectionOptions?: ToolCreateReconnectionOptions | undefined;
  sessionId?: string | undefined;
};

export const ToolCreateTransport$zodSchema: z.ZodType<ToolCreateTransport> = z
  .object({
    eventSourceInit: z.record(z.string(), z.any().nullable()).optional(),
    reconnectionOptions: z.lazy(() => ToolCreateReconnectionOptions$zodSchema)
      .optional(),
    requestInit: z.record(z.string(), z.any().nullable()).optional(),
    sessionId: z.string().optional(),
    type: ToolCreateTransportType$zodSchema,
  });

export type ToolCreateTransformation = string | { [k: string]: string };

export const ToolCreateTransformation$zodSchema: z.ZodType<
  ToolCreateTransformation
> = z.union([
  z.string(),
  z.record(z.string(), z.string()),
]);

export type ToolCreateToolOverrides = {
  displayName?: string | undefined;
  description?: string | undefined;
  schema?: any | null | undefined;
  transformation?: string | { [k: string]: string } | undefined;
};

export const ToolCreateToolOverrides$zodSchema: z.ZodType<
  ToolCreateToolOverrides
> = z.object({
  description: z.string().optional(),
  displayName: z.string().optional(),
  schema: z.any().nullable().optional(),
  transformation: z.union([
    z.string(),
    z.record(z.string(), z.string()),
  ]).optional(),
});

export type ToolCreateMcp = {
  server: ToolCreateServer;
  transport?: ToolCreateTransport | undefined;
  activeTools?: Array<string> | undefined;
  toolOverrides?: { [k: string]: ToolCreateToolOverrides } | undefined;
  prompt?: string | undefined;
};

export const ToolCreateMcp$zodSchema: z.ZodType<ToolCreateMcp> = z.object({
  activeTools: z.array(z.string()).optional(),
  prompt: z.string().optional(),
  server: z.lazy(() => ToolCreateServer$zodSchema),
  toolOverrides: z.record(
    z.string(),
    z.lazy(() => ToolCreateToolOverrides$zodSchema),
  ).optional(),
  transport: z.lazy(() => ToolCreateTransport$zodSchema).optional(),
});

export type ToolCreateConfig = { type: ToolCreateTypeMcp; mcp: ToolCreateMcp };

export const ToolCreateConfig$zodSchema: z.ZodType<ToolCreateConfig> = z.object(
  {
    mcp: z.lazy(() => ToolCreateMcp$zodSchema),
    type: ToolCreateTypeMcp$zodSchema,
  },
);

export type ToolCreate = {
  id: string;
  name: string;
  description?: string | null | undefined;
  config: ToolCreateConfig;
  credentialReferenceId?: string | null | undefined;
  credentialScope?: string | undefined;
  headers?: any | null | undefined;
  imageUrl?: string | undefined;
  capabilities?: any | null | undefined;
  lastError?: string | null | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
};

export const ToolCreate$zodSchema: z.ZodType<ToolCreate> = z.object({
  capabilities: z.any().nullable().optional(),
  config: z.lazy(() => ToolCreateConfig$zodSchema),
  createdAt: z.string().optional(),
  credentialReferenceId: z.string().nullable().optional(),
  credentialScope: z.string().optional(),
  description: z.string().nullable().optional(),
  headers: z.any().nullable().optional(),
  id: z.string(),
  imageUrl: z.string().optional(),
  lastError: z.string().nullable().optional(),
  name: z.string(),
  updatedAt: z.string().optional(),
});
