/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ToolUpdateTypeMcp = {
  Mcp: "mcp",
} as const;
export type ToolUpdateTypeMcp = ClosedEnum<typeof ToolUpdateTypeMcp>;

export const ToolUpdateTypeMcp$zodSchema = z.enum([
  "mcp",
]);

export type ToolUpdateServer = { url: string };

export const ToolUpdateServer$zodSchema: z.ZodType<ToolUpdateServer> = z.object(
  {
    url: z.string(),
  },
);

export const ToolUpdateTransportType = {
  StreamableHttp: "streamable_http",
  Sse: "sse",
} as const;
export type ToolUpdateTransportType = ClosedEnum<
  typeof ToolUpdateTransportType
>;

export const ToolUpdateTransportType$zodSchema = z.enum([
  "streamable_http",
  "sse",
]);

/**
 * Reconnection options for streamable HTTP transport
 */
export type ToolUpdateReconnectionOptions = {};

export const ToolUpdateReconnectionOptions$zodSchema: z.ZodType<
  ToolUpdateReconnectionOptions
> = z.object({}).describe("Reconnection options for streamable HTTP transport");

export type ToolUpdateTransport = {
  type: ToolUpdateTransportType;
  requestInit?: { [k: string]: any | null } | undefined;
  eventSourceInit?: { [k: string]: any | null } | undefined;
  reconnectionOptions?: ToolUpdateReconnectionOptions | undefined;
  sessionId?: string | undefined;
};

export const ToolUpdateTransport$zodSchema: z.ZodType<ToolUpdateTransport> = z
  .object({
    eventSourceInit: z.record(z.string(), z.any().nullable()).optional(),
    reconnectionOptions: z.lazy(() => ToolUpdateReconnectionOptions$zodSchema)
      .optional(),
    requestInit: z.record(z.string(), z.any().nullable()).optional(),
    sessionId: z.string().optional(),
    type: ToolUpdateTransportType$zodSchema,
  });

export type ToolUpdateTransformation = string | { [k: string]: string };

export const ToolUpdateTransformation$zodSchema: z.ZodType<
  ToolUpdateTransformation
> = z.union([
  z.string(),
  z.record(z.string(), z.string()),
]);

export type ToolUpdateToolOverrides = {
  displayName?: string | undefined;
  description?: string | undefined;
  schema?: any | null | undefined;
  transformation?: string | { [k: string]: string } | undefined;
};

export const ToolUpdateToolOverrides$zodSchema: z.ZodType<
  ToolUpdateToolOverrides
> = z.object({
  description: z.string().optional(),
  displayName: z.string().optional(),
  schema: z.any().nullable().optional(),
  transformation: z.union([
    z.string(),
    z.record(z.string(), z.string()),
  ]).optional(),
});

export type ToolUpdateMcp = {
  server: ToolUpdateServer;
  transport?: ToolUpdateTransport | undefined;
  activeTools?: Array<string> | undefined;
  toolOverrides?: { [k: string]: ToolUpdateToolOverrides } | undefined;
  prompt?: string | undefined;
};

export const ToolUpdateMcp$zodSchema: z.ZodType<ToolUpdateMcp> = z.object({
  activeTools: z.array(z.string()).optional(),
  prompt: z.string().optional(),
  server: z.lazy(() => ToolUpdateServer$zodSchema),
  toolOverrides: z.record(
    z.string(),
    z.lazy(() => ToolUpdateToolOverrides$zodSchema),
  ).optional(),
  transport: z.lazy(() => ToolUpdateTransport$zodSchema).optional(),
});

export type ToolUpdateConfig = { type: ToolUpdateTypeMcp; mcp: ToolUpdateMcp };

export const ToolUpdateConfig$zodSchema: z.ZodType<ToolUpdateConfig> = z.object(
  {
    mcp: z.lazy(() => ToolUpdateMcp$zodSchema),
    type: ToolUpdateTypeMcp$zodSchema,
  },
);

export type ToolUpdate = {
  id?: string | undefined;
  name?: string | undefined;
  description?: string | null | undefined;
  config?: ToolUpdateConfig | undefined;
  credentialReferenceId?: string | null | undefined;
  credentialScope?: string | undefined;
  headers?: any | null | undefined;
  imageUrl?: string | undefined;
  capabilities?: any | null | undefined;
  lastError?: string | null | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
};

export const ToolUpdate$zodSchema: z.ZodType<ToolUpdate> = z.object({
  capabilities: z.any().nullable().optional(),
  config: z.lazy(() => ToolUpdateConfig$zodSchema).optional(),
  createdAt: z.string().optional(),
  credentialReferenceId: z.string().nullable().optional(),
  credentialScope: z.string().optional(),
  description: z.string().nullable().optional(),
  headers: z.any().nullable().optional(),
  id: z.string().optional(),
  imageUrl: z.string().optional(),
  lastError: z.string().nullable().optional(),
  name: z.string().optional(),
  updatedAt: z.string().optional(),
});
