/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 69c021b9184a
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type TriggerDatasetRunRequestBody = {
  branchName?: string | undefined;
  evaluatorIds?: Array<string> | undefined;
};

export const TriggerDatasetRunRequestBody$zodSchema: z.ZodType<
  TriggerDatasetRunRequestBody
> = z.object({
  branchName: z.string().optional(),
  evaluatorIds: z.array(z.string()).optional(),
});

export type TriggerDatasetRunRequest = {
  tenantId: string;
  projectId: string;
  runConfigId: string;
  body?: TriggerDatasetRunRequestBody | undefined;
};

export const TriggerDatasetRunRequest$zodSchema: z.ZodType<
  TriggerDatasetRunRequest
> = z.object({
  body: z.lazy(() => TriggerDatasetRunRequestBody$zodSchema).optional(),
  projectId: z.string().describe("Project identifier"),
  runConfigId: z.string(),
  tenantId: z.string().describe("Tenant identifier"),
});

export const TriggerDatasetRunStatus = {
  Pending: "pending",
} as const;
export type TriggerDatasetRunStatus = ClosedEnum<
  typeof TriggerDatasetRunStatus
>;

export const TriggerDatasetRunStatus$zodSchema = z.enum([
  "pending",
]);

/**
 * Dataset run triggered
 */
export type TriggerDatasetRunResponseBody = {
  datasetRunId: string;
  status: TriggerDatasetRunStatus;
  totalItems: number;
};

export const TriggerDatasetRunResponseBody$zodSchema: z.ZodType<
  TriggerDatasetRunResponseBody
> = z.object({
  datasetRunId: z.string(),
  status: TriggerDatasetRunStatus$zodSchema,
  totalItems: z.number(),
}).describe("Dataset run triggered");

export type TriggerDatasetRunResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: TriggerDatasetRunResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const TriggerDatasetRunResponse$zodSchema: z.ZodType<
  TriggerDatasetRunResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
  InternalServerError: InternalServerError$zodSchema.optional().describe(
    "Internal Server Error",
  ),
  NotFound: NotFound$zodSchema.optional().describe("Not Found"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
    "Unprocessable Entity",
  ),
  object: z.lazy(() => TriggerDatasetRunResponseBody$zodSchema).optional()
    .describe("Dataset run triggered"),
});
