/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ComponentJoin, ComponentJoin$zodSchema } from "./componentjoin.js";
import {
  SignatureSource,
  SignatureSource$zodSchema,
} from "./signaturesource.js";
import {
  SignatureValidationOptions,
  SignatureValidationOptions$zodSchema,
} from "./signaturevalidationoptions.js";
import {
  SignedComponent,
  SignedComponent$zodSchema,
} from "./signedcomponent.js";
import {
  TriggerAuthenticationInput,
  TriggerAuthenticationInput$zodSchema,
} from "./triggerauthenticationinput.js";
import {
  TriggerOutputTransform,
  TriggerOutputTransform$zodSchema,
} from "./triggeroutputtransform.js";

/**
 * HMAC algorithm to use for signature verification
 */
export const TriggerUpdateAlgorithm = {
  Sha256: "sha256",
  Sha512: "sha512",
  Sha384: "sha384",
  Sha1: "sha1",
  Md5: "md5",
} as const;
/**
 * HMAC algorithm to use for signature verification
 */
export type TriggerUpdateAlgorithm = ClosedEnum<typeof TriggerUpdateAlgorithm>;

export const TriggerUpdateAlgorithm$zodSchema = z.enum([
  "sha256",
  "sha512",
  "sha384",
  "sha1",
  "md5",
]).describe("HMAC algorithm to use for signature verification");

/**
 * Encoding format of the signature (hex or base64)
 */
export const TriggerUpdateEncoding = {
  Hex: "hex",
  Base64: "base64",
} as const;
/**
 * Encoding format of the signature (hex or base64)
 */
export type TriggerUpdateEncoding = ClosedEnum<typeof TriggerUpdateEncoding>;

export const TriggerUpdateEncoding$zodSchema = z.enum([
  "hex",
  "base64",
]).describe("Encoding format of the signature (hex or base64)");

/**
 * Configuration for webhook signature verification
 */
export type TriggerUpdateSignatureVerification = {
  algorithm: TriggerUpdateAlgorithm;
  encoding: TriggerUpdateEncoding;
  signature: SignatureSource;
  signedComponents: Array<SignedComponent>;
  componentJoin: ComponentJoin;
  validation?: SignatureValidationOptions | undefined;
};

export const TriggerUpdateSignatureVerification$zodSchema: z.ZodType<
  TriggerUpdateSignatureVerification
> = z.object({
  algorithm: TriggerUpdateAlgorithm$zodSchema,
  componentJoin: ComponentJoin$zodSchema,
  encoding: TriggerUpdateEncoding$zodSchema,
  signature: SignatureSource$zodSchema,
  signedComponents: z.array(SignedComponent$zodSchema),
  validation: SignatureValidationOptions$zodSchema.optional(),
}).describe("Configuration for webhook signature verification");

export type TriggerUpdate = {
  tenantId?: string | undefined;
  id?: string | undefined;
  projectId?: string | undefined;
  agentId?: string | undefined;
  name?: string | undefined;
  description?: string | null | undefined;
  enabled?: boolean | undefined;
  inputSchema?: { [k: string]: any | null } | null | undefined;
  outputTransform?: TriggerOutputTransform | null | undefined;
  messageTemplate?: string | null | undefined;
  authentication?: TriggerAuthenticationInput | null | undefined;
  signingSecretCredentialReferenceId?: string | null | undefined;
  signatureVerification?: TriggerUpdateSignatureVerification | null | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
};

export const TriggerUpdate$zodSchema: z.ZodType<TriggerUpdate> = z.object({
  agentId: z.string().optional(),
  authentication: TriggerAuthenticationInput$zodSchema.nullable().optional(),
  createdAt: z.string().optional(),
  description: z.string().nullable().optional(),
  enabled: z.boolean().optional(),
  id: z.string().optional(),
  inputSchema: z.record(z.string(), z.any().nullable()).nullable().optional(),
  messageTemplate: z.string().nullable().optional(),
  name: z.string().optional(),
  outputTransform: TriggerOutputTransform$zodSchema.nullable().optional(),
  projectId: z.string().optional(),
  signatureVerification: z.lazy(() =>
    TriggerUpdateSignatureVerification$zodSchema
  ).nullable().optional(),
  signingSecretCredentialReferenceId: z.string().nullable().optional(),
  tenantId: z.string().optional(),
  updatedAt: z.string().optional(),
});
