/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 884c4c047e28
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ComponentJoin, ComponentJoin$zodSchema } from "./componentjoin.js";
import {
  SignatureSource,
  SignatureSource$zodSchema,
} from "./signaturesource.js";
import {
  SignatureValidationOptions,
  SignatureValidationOptions$zodSchema,
} from "./signaturevalidationoptions.js";
import {
  SignedComponent,
  SignedComponent$zodSchema,
} from "./signedcomponent.js";
import {
  TriggerAuthenticationInput,
  TriggerAuthenticationInput$zodSchema,
} from "./triggerauthenticationinput.js";
import {
  TriggerOutputTransform,
  TriggerOutputTransform$zodSchema,
} from "./triggeroutputtransform.js";

/**
 * HMAC algorithm to use for signature verification
 */
export const TriggerUpdateAlgorithm = {
  Sha256: "sha256",
  Sha512: "sha512",
  Sha384: "sha384",
  Sha1: "sha1",
  Md5: "md5",
} as const;
/**
 * HMAC algorithm to use for signature verification
 */
export type TriggerUpdateAlgorithm = ClosedEnum<typeof TriggerUpdateAlgorithm>;

export const TriggerUpdateAlgorithm$zodSchema = z.enum([
  "sha256",
  "sha512",
  "sha384",
  "sha1",
  "md5",
]).describe("HMAC algorithm to use for signature verification");

/**
 * Encoding format of the signature (hex or base64)
 */
export const TriggerUpdateEncoding = {
  Hex: "hex",
  Base64: "base64",
} as const;
/**
 * Encoding format of the signature (hex or base64)
 */
export type TriggerUpdateEncoding = ClosedEnum<typeof TriggerUpdateEncoding>;

export const TriggerUpdateEncoding$zodSchema = z.enum([
  "hex",
  "base64",
]).describe("Encoding format of the signature (hex or base64)");

/**
 * Configuration for webhook signature verification
 */
export type TriggerUpdateSignatureVerification = {
  algorithm: TriggerUpdateAlgorithm;
  encoding: TriggerUpdateEncoding;
  signature: SignatureSource;
  signedComponents: Array<SignedComponent>;
  componentJoin: ComponentJoin;
  validation?: SignatureValidationOptions | undefined;
};

export const TriggerUpdateSignatureVerification$zodSchema: z.ZodType<
  TriggerUpdateSignatureVerification
> = z.object({
  algorithm: TriggerUpdateAlgorithm$zodSchema.describe(
    "HMAC algorithm to use for signature verification",
  ),
  componentJoin: ComponentJoin$zodSchema.describe(
    "How to join signed components",
  ),
  encoding: TriggerUpdateEncoding$zodSchema.describe(
    "Encoding format of the signature (hex or base64)",
  ),
  signature: SignatureSource$zodSchema.describe(
    "Configuration for extracting the signature",
  ),
  signedComponents: z.array(SignedComponent$zodSchema).describe(
    "Array of components that are signed (order matters)",
  ),
  validation: SignatureValidationOptions$zodSchema.optional().describe(
    "Advanced validation options",
  ),
}).describe("Configuration for webhook signature verification");

export type TriggerUpdate = {
  id?: string | undefined;
  name?: string | undefined;
  description?: string | null | undefined;
  enabled?: boolean | undefined;
  inputSchema?: { [k: string]: any | null } | null | undefined;
  outputTransform?: TriggerOutputTransform | null | undefined;
  messageTemplate?: string | null | undefined;
  authentication?: TriggerAuthenticationInput | null | undefined;
  signingSecretCredentialReferenceId?: string | null | undefined;
  signatureVerification?: TriggerUpdateSignatureVerification | null | undefined;
  runAsUserId?: string | null | undefined;
  createdBy?: string | null | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
};

export const TriggerUpdate$zodSchema: z.ZodType<TriggerUpdate> = z.object({
  authentication: TriggerAuthenticationInput$zodSchema.nullable().optional(),
  createdAt: z.string().optional(),
  createdBy: z.string().nullable().optional().describe(
    "User ID of the user who created this trigger",
  ),
  description: z.string().nullable().optional().describe("Trigger description"),
  enabled: z.boolean().optional().describe("Whether the trigger is enabled"),
  id: z.string().optional().describe("Resource identifier"),
  inputSchema: z.record(z.string(), z.any().nullable()).nullable().optional()
    .describe("JSON Schema for input validation"),
  messageTemplate: z.string().nullable().optional().describe(
    "Message template with {{\"{{\"}}placeholder}} syntax",
  ),
  name: z.string().optional().describe("Trigger name"),
  outputTransform: TriggerOutputTransform$zodSchema.nullable().optional(),
  runAsUserId: z.string().nullable().optional().describe(
    "User ID to run the webhook as",
  ),
  signatureVerification: z.lazy(() =>
    TriggerUpdateSignatureVerification$zodSchema
  ).nullable().optional().describe(
    "Configuration for webhook signature verification",
  ),
  signingSecretCredentialReferenceId: z.string().nullable().optional().describe(
    "Reference to credential containing signing secret",
  ),
  updatedAt: z.string().optional(),
});
