/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f95ac2b5123b
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  FullProjectDefinition,
  FullProjectDefinition$zodSchema,
} from "./fullprojectdefinition.js";
import {
  FullProjectSelectResponse,
  FullProjectSelectResponse$zodSchema,
} from "./fullprojectselectresponse.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type UpdateFullProjectRequest = {
  tenantId: string;
  projectId: string;
  body?: FullProjectDefinition | undefined;
};

export const UpdateFullProjectRequest$zodSchema: z.ZodType<
  UpdateFullProjectRequest
> = z.object({
  body: FullProjectDefinition$zodSchema.optional(),
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

export type UpdateFullProjectResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  FullProjectSelectResponse?: FullProjectSelectResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const UpdateFullProjectResponse$zodSchema: z.ZodType<
  UpdateFullProjectResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  FullProjectSelectResponse: FullProjectSelectResponse$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
