/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 97db5c46f176
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Evaluator, Evaluator$zodSchema } from "./evaluator.js";
import {
  EvaluatorUpdate,
  EvaluatorUpdate$zodSchema,
} from "./evaluatorupdate.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type UpdateEvaluatorRequest = {
  tenantId: string;
  projectId: string;
  evaluatorId: string;
  body?: EvaluatorUpdate | undefined;
};

export const UpdateEvaluatorRequest$zodSchema: z.ZodType<
  UpdateEvaluatorRequest
> = z.object({
  body: EvaluatorUpdate$zodSchema.optional(),
  evaluatorId: z.string(),
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

/**
 * Evaluator updated
 */
export type UpdateEvaluatorResponseBody = { data: Evaluator };

export const UpdateEvaluatorResponseBody$zodSchema: z.ZodType<
  UpdateEvaluatorResponseBody
> = z.object({
  data: Evaluator$zodSchema,
}).describe("Evaluator updated");

export type UpdateEvaluatorResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: UpdateEvaluatorResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const UpdateEvaluatorResponse$zodSchema: z.ZodType<
  UpdateEvaluatorResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
  InternalServerError: InternalServerError$zodSchema.optional().describe(
    "Internal Server Error",
  ),
  NotFound: NotFound$zodSchema.optional().describe("Not Found"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
    "Unprocessable Entity",
  ),
  object: z.lazy(() => UpdateEvaluatorResponseBody$zodSchema).optional()
    .describe("Evaluator updated"),
});
