/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ba6af22632db
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import {
  SubAgentTeamAgentRelationResponse,
  SubAgentTeamAgentRelationResponse$zodSchema,
} from "./subagentteamagentrelationresponse.js";
import {
  SubAgentTeamAgentRelationUpdate,
  SubAgentTeamAgentRelationUpdate$zodSchema,
} from "./subagentteamagentrelationupdate.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type UpdateSubAgentTeamAgentRelationRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
  subAgentId: string;
  id: string;
  body?: SubAgentTeamAgentRelationUpdate | undefined;
};

export const UpdateSubAgentTeamAgentRelationRequest$zodSchema: z.ZodType<
  UpdateSubAgentTeamAgentRelationRequest
> = z.object({
  agentId: z.string().describe("Agent identifier"),
  body: SubAgentTeamAgentRelationUpdate$zodSchema.optional(),
  id: z.string().describe("Resource identifier"),
  projectId: z.string().describe("Project identifier"),
  subAgentId: z.string().describe("Sub-agent identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

export type UpdateSubAgentTeamAgentRelationResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  SubAgentTeamAgentRelationResponse?:
    | SubAgentTeamAgentRelationResponse
    | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const UpdateSubAgentTeamAgentRelationResponse$zodSchema: z.ZodType<
  UpdateSubAgentTeamAgentRelationResponse
> = z.object({
  BadRequest: BadRequest$zodSchema.optional().describe("Bad Request"),
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  Forbidden: Forbidden$zodSchema.optional().describe("Forbidden"),
  InternalServerError: InternalServerError$zodSchema.optional().describe(
    "Internal Server Error",
  ),
  NotFound: NotFound$zodSchema.optional().describe("Not Found"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  SubAgentTeamAgentRelationResponse: SubAgentTeamAgentRelationResponse$zodSchema
    .optional().describe("Sub Agent team agent relation updated successfully"),
  Unauthorized: Unauthorized$zodSchema.optional().describe("Unauthorized"),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional().describe(
    "Unprocessable Entity",
  ),
});
