/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import { type BadRequest, BadRequest$zodSchema } from './badrequest.js';
import { type Forbidden, Forbidden$zodSchema } from './forbidden.js';
import { type InternalServerError, InternalServerError$zodSchema } from './internalservererror.js';
import { type NotFound, NotFound$zodSchema } from './notfound.js';
import {
  type SubAgentToolRelationResponse,
  SubAgentToolRelationResponse$zodSchema,
} from './subagenttoolrelationresponse.js';
import {
  type SubAgentToolRelationUpdate,
  SubAgentToolRelationUpdate$zodSchema,
} from './subagenttoolrelationupdate.js';
import { type Unauthorized, Unauthorized$zodSchema } from './unauthorized.js';
import { type UnprocessableEntity, UnprocessableEntity$zodSchema } from './unprocessableentity.js';

export type UpdateSubagentToolRelationRequest = {
  tenantId: string;
  projectId: string;
  agentId: string;
  id: string;
  body?: SubAgentToolRelationUpdate | undefined;
};

export const UpdateSubagentToolRelationRequest$zodSchema: z.ZodType<
  UpdateSubagentToolRelationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  agentId: z.string().describe('Agent identifier'),
  body: SubAgentToolRelationUpdate$zodSchema.optional(),
  id: z.string().describe('Resource identifier'),
  projectId: z.string().describe('Project identifier'),
  tenantId: z.string().describe('Tenant identifier'),
});

export type UpdateSubagentToolRelationResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  SubAgentToolRelationResponse?: SubAgentToolRelationResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const UpdateSubagentToolRelationResponse$zodSchema: z.ZodType<
  UpdateSubagentToolRelationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  SubAgentToolRelationResponse: SubAgentToolRelationResponse$zodSchema.optional(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
