/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c63aab6bdea0
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { SkillResponse, SkillResponse$zodSchema } from "./skillresponse.js";
import { SkillUpdate, SkillUpdate$zodSchema } from "./skillupdate.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type UpdateSkillRequest = {
  tenantId: string;
  projectId: string;
  id: string;
  body?: SkillUpdate | undefined;
};

export const UpdateSkillRequest$zodSchema: z.ZodType<UpdateSkillRequest> = z
  .object({
    body: SkillUpdate$zodSchema.optional(),
    id: z.string().describe("Resource identifier"),
    projectId: z.string().describe("Project identifier"),
    tenantId: z.string().describe("Tenant identifier"),
  });

export type UpdateSkillResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  SkillResponse?: SkillResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const UpdateSkillResponse$zodSchema: z.ZodType<UpdateSkillResponse> = z
  .object({
    BadRequest: BadRequest$zodSchema.optional(),
    ContentType: z.string(),
    Forbidden: Forbidden$zodSchema.optional(),
    InternalServerError: InternalServerError$zodSchema.optional(),
    NotFound: NotFound$zodSchema.optional(),
    RawResponse: z.custom<Response>(x => x instanceof Response),
    SkillResponse: SkillResponse$zodSchema.optional(),
    StatusCode: z.int(),
    Unauthorized: Unauthorized$zodSchema.optional(),
    UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
  });
