/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import { type BadRequest, BadRequest$zodSchema } from './badrequest.js';
import { type Forbidden, Forbidden$zodSchema } from './forbidden.js';
import { type InternalServerError, InternalServerError$zodSchema } from './internalservererror.js';
import { type NotFound, NotFound$zodSchema } from './notfound.js';
import { type ProjectResponse, ProjectResponse$zodSchema } from './projectresponse.js';
import { type ProjectUpdate, ProjectUpdate$zodSchema } from './projectupdate.js';
import { type Unauthorized, Unauthorized$zodSchema } from './unauthorized.js';
import { type UnprocessableEntity, UnprocessableEntity$zodSchema } from './unprocessableentity.js';

export type UpdateProjectRequest = {
  tenantId: string;
  id: string;
  body?: ProjectUpdate | undefined;
};

export const UpdateProjectRequest$zodSchema: z.ZodType<
  UpdateProjectRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  body: ProjectUpdate$zodSchema.optional(),
  id: z.string().describe('Resource identifier'),
  tenantId: z.string().describe('Tenant identifier'),
});

export type UpdateProjectResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ProjectResponse?: ProjectResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const UpdateProjectResponse$zodSchema: z.ZodType<
  UpdateProjectResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  ProjectResponse: ProjectResponse$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
