/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import {
  CredentialReferenceResponse,
  CredentialReferenceResponse$zodSchema,
} from "./credentialreferenceresponse.js";
import {
  CredentialReferenceUpdate,
  CredentialReferenceUpdate$zodSchema,
} from "./credentialreferenceupdate.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type UpdateCredentialRequest = {
  tenantId: string;
  projectId: string;
  id: string;
  body?: CredentialReferenceUpdate | undefined;
};

export const UpdateCredentialRequest$zodSchema: z.ZodType<
  UpdateCredentialRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  body: CredentialReferenceUpdate$zodSchema.optional(),
  id: z.string().describe("Resource identifier"),
  projectId: z.string().describe("Project identifier"),
  tenantId: z.string().describe("Tenant identifier"),
});

export type UpdateCredentialResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  CredentialReferenceResponse?: CredentialReferenceResponse | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const UpdateCredentialResponse$zodSchema: z.ZodType<
  UpdateCredentialResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  ContentType: z.string(),
  CredentialReferenceResponse: CredentialReferenceResponse$zodSchema.optional(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
