name: Inkeep Source Sync

on:
  push:
    branches:
      - main
    paths:
      - "agents-docs/**"

jobs:
  syncSourceJob:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
      - name: Check for changes
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: changes
        with:
          filters: |
            docs:
              - 'agents-docs/**'
      - name: Sync Source
        if: steps.changes.outputs.docs == 'true'
        uses: inkeep/pr-commenter-action@bac203359f0328cbb89cca8f9ead7a7176f39a61 # v11
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          apiKey: ${{secrets.INKEEP_API_KEY}}
          sourceId: "cmexes6zq0046s6019sayhjst"