name: Version Packages CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  check-version-pr:
    if: contains(github.event.pull_request.title, 'Version Packages')
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve Version Packages PR
        run: |
          echo "This is a Version Packages PR created by Changesets"
          echo "Skipping CI checks as this is an automated release PR"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Author: ${{ github.event.pull_request.user.login }}"

      - name: Create ci status check
        uses: actions/github-script@v7
        with:
          script: |
            // Create a passing ci status check for version packages PRs
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'success',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              description: 'CI skipped for Version Packages PR',
              context: 'ci'
            });